// Device connection status types
export const DEVICE_CONNECTION_STATUS_UPDATED =
  "DEVICE_CONNECTION_STATUS_UPDATED";
export const DEVICE_CONNECTED = "DEVICE_CONNECTED";
export const DEVICE_DISCONNECTED = "DEVICE_DISCONNECTED";
export const DEVICE_CONNECTION_CHANGED = "DEVICE_CONNECTION_CHANGED";
export const RECEIVE_CONNECTED_DEVICES_STATUS =
  "RECEIVE_CONNECTED_DEVICES_STATUS";
export const UPDATE_SINGLE_DEVICE_STATUS = "UPDATE_SINGLE_DEVICE_STATUS";
