// Action Types
export const AUTHORIZE_PUMP_REQUEST = "AUTHORIZE_PUMP_REQUEST";
export const AUTHORIZE_PUMP_SUCCESS = "AUTHORIZE_PUMP_SUCCESS";
export const AUTHORIZE_PUMP_FAILURE = "AUTHORIZE_PUMP_FAILURE";

export const GET_PUMP_STATE_REQUEST = "GET_PUMP_STATE_REQUEST";
export const GET_PUMP_STATE_SUCCESS = "GET_PUMP_STATE_SUCCESS";
export const GET_PUMP_STATE_FAILURE = "GET_PUMP_STATE_FAILURE";

export const STOP_PUMP_REQUEST = "STOP_PUMP_REQUEST";
export const STOP_PUMP_SUCCESS = "STOP_PUMP_SUCCESS";
export const STOP_PUMP_FAILURE = "STOP_PUMP_FAILURE";

export const CLOSE_TRANSACTION_REQUEST = "CLOSE_TRANSACTION_REQUEST";
export const CLOSE_TRANSACTION_SUCCESS = "CLOSE_TRANSACTION_SUCCESS";
export const CLOSE_TRANSACTION_FAILURE = "CLOSE_TRANSACTION_FAILURE";

// Real-time status updates
export const UPDATE_PUMP_STATUS = "UPDATE_PUMP_STATUS";
export const UPDATE_NOZZLE_STATE = "UPDATE_NOZZLE_STATE";
export const UPDATE_FILLING_STATUS = "UPDATE_FILLING_STATUS";
export const UPDATE_PUMP_TRANSACTION_COMPLETED =
  "UPDATE_PUMP_TRANSACTION_COMPLETED";
export const RECEIVE_UPLOAD_STATUS_UPDATE = "RECEIVE_UPLOAD_STATUS_UPDATE";

// Device connection status types
export const DEVICE_CONNECTION_STATUS_UPDATED =
  "DEVICE_CONNECTION_STATUS_UPDATED";
export const DEVICE_CONNECTED = "DEVICE_CONNECTED";
export const DEVICE_DISCONNECTED = "DEVICE_DISCONNECTED";
export const DEVICE_CONNECTION_CHANGED = "DEVICE_CONNECTION_CHANGED";
export const RECEIVE_CONNECTED_DEVICES_STATUS =
  "RECEIVE_CONNECTED_DEVICES_STATUS";
