/**
 * GpsGate API Documentation
 * GpsGate API service
 *
 * The version of the OpenAPI document: v.1
 * Contact: support@gpsgate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApplicationModel model module.
 * @module model/ApplicationModel
 * @version v.1
 */
class ApplicationModel {
    /**
     * Constructs a new <code>ApplicationModel</code>.
     * @alias module:model/ApplicationModel
     * @param created {String} 
     * @param expire {String} 
     * @param expired {Boolean} 
     * @param id {Number} 
     * @param licensesUsed {Number} 
     * @param maxUsers {Number} 
     * @param userCount {Number} 
     */
    constructor(created, expire, expired, id, licensesUsed, maxUsers, userCount) { 
        
        ApplicationModel.initialize(this, created, expire, expired, id, licensesUsed, maxUsers, userCount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, created, expire, expired, id, licensesUsed, maxUsers, userCount) { 
        obj['created'] = created;
        obj['expire'] = expire;
        obj['expired'] = expired;
        obj['id'] = id;
        obj['licensesUsed'] = licensesUsed;
        obj['maxUsers'] = maxUsers;
        obj['userCount'] = userCount;
    }

    /**
     * Constructs a <code>ApplicationModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApplicationModel} obj Optional instance to populate.
     * @return {module:model/ApplicationModel} The populated <code>ApplicationModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApplicationModel();

            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('expire')) {
                obj['expire'] = ApiClient.convertToType(data['expire'], 'String');
            }
            if (data.hasOwnProperty('expired')) {
                obj['expired'] = ApiClient.convertToType(data['expired'], 'Boolean');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('licensesUsed')) {
                obj['licensesUsed'] = ApiClient.convertToType(data['licensesUsed'], 'Number');
            }
            if (data.hasOwnProperty('maxUsers')) {
                obj['maxUsers'] = ApiClient.convertToType(data['maxUsers'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('userCount')) {
                obj['userCount'] = ApiClient.convertToType(data['userCount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApplicationModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApplicationModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApplicationModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['created'] && !(typeof data['created'] === 'string' || data['created'] instanceof String)) {
            throw new Error("Expected the field `created` to be a primitive type in the JSON string but got " + data['created']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['expire'] && !(typeof data['expire'] === 'string' || data['expire'] instanceof String)) {
            throw new Error("Expected the field `expire` to be a primitive type in the JSON string but got " + data['expire']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}

ApplicationModel.RequiredProperties = ["created", "expire", "expired", "id", "licensesUsed", "maxUsers", "userCount"];

/**
 * @member {String} created
 */
ApplicationModel.prototype['created'] = undefined;

/**
 * @member {String} description
 */
ApplicationModel.prototype['description'] = undefined;

/**
 * @member {String} expire
 */
ApplicationModel.prototype['expire'] = undefined;

/**
 * @member {Boolean} expired
 */
ApplicationModel.prototype['expired'] = undefined;

/**
 * @member {Number} id
 */
ApplicationModel.prototype['id'] = undefined;

/**
 * @member {Number} licensesUsed
 */
ApplicationModel.prototype['licensesUsed'] = undefined;

/**
 * @member {Number} maxUsers
 */
ApplicationModel.prototype['maxUsers'] = undefined;

/**
 * @member {String} name
 */
ApplicationModel.prototype['name'] = undefined;

/**
 * @member {Number} userCount
 */
ApplicationModel.prototype['userCount'] = undefined;






export default ApplicationModel;

