/**
 * GpsGate API Documentation
 * GpsGate API service
 *
 * The version of the OpenAPI document: v.1
 * Contact: support@gpsgate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApplicationTrackInfoModel model module.
 * @module model/ApplicationTrackInfoModel
 * @version v.1
 */
class ApplicationTrackInfoModel {
    /**
     * Constructs a new <code>ApplicationTrackInfoModel</code>.
     * @alias module:model/ApplicationTrackInfoModel
     * @param count {Number} 
     * @param created {String} 
     * @param id {Number} 
     * @param updated {String} 
     * @param userId {Number} 
     */
    constructor(count, created, id, updated, userId) { 
        
        ApplicationTrackInfoModel.initialize(this, count, created, id, updated, userId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, count, created, id, updated, userId) { 
        obj['count'] = count;
        obj['created'] = created;
        obj['id'] = id;
        obj['updated'] = updated;
        obj['userId'] = userId;
    }

    /**
     * Constructs a <code>ApplicationTrackInfoModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApplicationTrackInfoModel} obj Optional instance to populate.
     * @return {module:model/ApplicationTrackInfoModel} The populated <code>ApplicationTrackInfoModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApplicationTrackInfoModel();

            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('updated')) {
                obj['updated'] = ApiClient.convertToType(data['updated'], 'String');
            }
            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApplicationTrackInfoModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApplicationTrackInfoModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApplicationTrackInfoModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['created'] && !(typeof data['created'] === 'string' || data['created'] instanceof String)) {
            throw new Error("Expected the field `created` to be a primitive type in the JSON string but got " + data['created']);
        }
        // ensure the json data is a string
        if (data['updated'] && !(typeof data['updated'] === 'string' || data['updated'] instanceof String)) {
            throw new Error("Expected the field `updated` to be a primitive type in the JSON string but got " + data['updated']);
        }

        return true;
    }


}

ApplicationTrackInfoModel.RequiredProperties = ["count", "created", "id", "updated", "userId"];

/**
 * @member {Number} count
 */
ApplicationTrackInfoModel.prototype['count'] = undefined;

/**
 * @member {String} created
 */
ApplicationTrackInfoModel.prototype['created'] = undefined;

/**
 * @member {Number} id
 */
ApplicationTrackInfoModel.prototype['id'] = undefined;

/**
 * @member {String} updated
 */
ApplicationTrackInfoModel.prototype['updated'] = undefined;

/**
 * @member {Number} userId
 */
ApplicationTrackInfoModel.prototype['userId'] = undefined;






export default ApplicationTrackInfoModel;

