/**
 * GpsGate API Documentation
 * GpsGate API service
 *
 * The version of the OpenAPI document: v.1
 * Contact: support@gpsgate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApplicationCreateModel model module.
 * @module model/ApplicationCreateModel
 * @version v.1
 */
class ApplicationCreateModel {
    /**
     * Constructs a new <code>ApplicationCreateModel</code>.
     * @alias module:model/ApplicationCreateModel
     * @param adminUserId {Number} 
     * @param applicationTemplateId {Number} 
     * @param id {Number} 
     */
    constructor(adminUserId, applicationTemplateId, id) { 
        
        ApplicationCreateModel.initialize(this, adminUserId, applicationTemplateId, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, adminUserId, applicationTemplateId, id) { 
        obj['adminUserId'] = adminUserId;
        obj['applicationTemplateId'] = applicationTemplateId;
        obj['id'] = id;
    }

    /**
     * Constructs a <code>ApplicationCreateModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApplicationCreateModel} obj Optional instance to populate.
     * @return {module:model/ApplicationCreateModel} The populated <code>ApplicationCreateModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApplicationCreateModel();

            if (data.hasOwnProperty('adminUserId')) {
                obj['adminUserId'] = ApiClient.convertToType(data['adminUserId'], 'Number');
            }
            if (data.hasOwnProperty('applicationTemplateId')) {
                obj['applicationTemplateId'] = ApiClient.convertToType(data['applicationTemplateId'], 'Number');
            }
            if (data.hasOwnProperty('culture')) {
                obj['culture'] = ApiClient.convertToType(data['culture'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('language')) {
                obj['language'] = ApiClient.convertToType(data['language'], 'String');
            }
            if (data.hasOwnProperty('measurement')) {
                obj['measurement'] = ApiClient.convertToType(data['measurement'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('timeZone')) {
                obj['timeZone'] = ApiClient.convertToType(data['timeZone'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApplicationCreateModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApplicationCreateModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApplicationCreateModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['culture'] && !(typeof data['culture'] === 'string' || data['culture'] instanceof String)) {
            throw new Error("Expected the field `culture` to be a primitive type in the JSON string but got " + data['culture']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['language'] && !(typeof data['language'] === 'string' || data['language'] instanceof String)) {
            throw new Error("Expected the field `language` to be a primitive type in the JSON string but got " + data['language']);
        }
        // ensure the json data is a string
        if (data['measurement'] && !(typeof data['measurement'] === 'string' || data['measurement'] instanceof String)) {
            throw new Error("Expected the field `measurement` to be a primitive type in the JSON string but got " + data['measurement']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['timeZone'] && !(typeof data['timeZone'] === 'string' || data['timeZone'] instanceof String)) {
            throw new Error("Expected the field `timeZone` to be a primitive type in the JSON string but got " + data['timeZone']);
        }

        return true;
    }


}

ApplicationCreateModel.RequiredProperties = ["adminUserId", "applicationTemplateId", "id"];

/**
 * @member {Number} adminUserId
 */
ApplicationCreateModel.prototype['adminUserId'] = undefined;

/**
 * @member {Number} applicationTemplateId
 */
ApplicationCreateModel.prototype['applicationTemplateId'] = undefined;

/**
 * @member {String} culture
 */
ApplicationCreateModel.prototype['culture'] = undefined;

/**
 * @member {String} description
 */
ApplicationCreateModel.prototype['description'] = undefined;

/**
 * @member {Number} id
 */
ApplicationCreateModel.prototype['id'] = undefined;

/**
 * @member {String} language
 */
ApplicationCreateModel.prototype['language'] = undefined;

/**
 * @member {String} measurement
 */
ApplicationCreateModel.prototype['measurement'] = undefined;

/**
 * @member {String} name
 */
ApplicationCreateModel.prototype['name'] = undefined;

/**
 * @member {String} timeZone
 */
ApplicationCreateModel.prototype['timeZone'] = undefined;






export default ApplicationCreateModel;

