/**
 * GpsGate API Documentation
 * GpsGate API service
 *
 * The version of the OpenAPI document: v.1
 * Contact: support@gpsgate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Argument model module.
 * @module model/Argument
 * @version v.1
 */
class Argument {
    /**
     * Constructs a new <code>Argument</code>.
     * @alias module:model/Argument
     * @param argumentID {Number} 
     * @param eventID {Number} 
     */
    constructor(argumentID, eventID) { 
        
        Argument.initialize(this, argumentID, eventID);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, argumentID, eventID) { 
        obj['argumentID'] = argumentID;
        obj['eventID'] = eventID;
    }

    /**
     * Constructs a <code>Argument</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Argument} obj Optional instance to populate.
     * @return {module:model/Argument} The populated <code>Argument</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Argument();

            if (data.hasOwnProperty('argumentID')) {
                obj['argumentID'] = ApiClient.convertToType(data['argumentID'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('eventID')) {
                obj['eventID'] = ApiClient.convertToType(data['eventID'], 'Number');
            }
            if (data.hasOwnProperty('sIValue')) {
                obj['sIValue'] = ApiClient.convertToType(data['sIValue'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('variable')) {
                obj['variable'] = ApiClient.convertToType(data['variable'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Argument</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Argument</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Argument.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['sIValue'] && !(typeof data['sIValue'] === 'string' || data['sIValue'] instanceof String)) {
            throw new Error("Expected the field `sIValue` to be a primitive type in the JSON string but got " + data['sIValue']);
        }
        // ensure the json data is a string
        if (data['value'] && !(typeof data['value'] === 'string' || data['value'] instanceof String)) {
            throw new Error("Expected the field `value` to be a primitive type in the JSON string but got " + data['value']);
        }
        // ensure the json data is a string
        if (data['variable'] && !(typeof data['variable'] === 'string' || data['variable'] instanceof String)) {
            throw new Error("Expected the field `variable` to be a primitive type in the JSON string but got " + data['variable']);
        }

        return true;
    }


}

Argument.RequiredProperties = ["argumentID", "eventID"];

/**
 * @member {Number} argumentID
 */
Argument.prototype['argumentID'] = undefined;

/**
 * @member {String} description
 */
Argument.prototype['description'] = undefined;

/**
 * @member {Number} eventID
 */
Argument.prototype['eventID'] = undefined;

/**
 * @member {String} sIValue
 */
Argument.prototype['sIValue'] = undefined;

/**
 * @member {String} value
 */
Argument.prototype['value'] = undefined;

/**
 * @member {String} variable
 */
Argument.prototype['variable'] = undefined;






export default Argument;

