/**
 * GpsGate API Documentation
 * GpsGate API service
 *
 * The version of the OpenAPI document: v.1
 * Contact: support@gpsgate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BoundingBox model module.
 * @module model/BoundingBox
 * @version v.1
 */
class BoundingBox {
    /**
     * Constructs a new <code>BoundingBox</code>.
     * @alias module:model/BoundingBox
     * @param maxM {Number} 
     * @param maxTime {String} 
     * @param maxX {Number} 
     * @param maxY {Number} 
     * @param maxZ {Number} 
     * @param minM {Number} 
     * @param minTime {String} 
     * @param minX {Number} 
     * @param minY {Number} 
     * @param minZ {Number} 
     */
    constructor(maxM, maxTime, maxX, maxY, maxZ, minM, minTime, minX, minY, minZ) { 
        
        BoundingBox.initialize(this, maxM, maxTime, maxX, maxY, maxZ, minM, minTime, minX, minY, minZ);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, maxM, maxTime, maxX, maxY, maxZ, minM, minTime, minX, minY, minZ) { 
        obj['maxM'] = maxM;
        obj['maxTime'] = maxTime;
        obj['maxX'] = maxX;
        obj['maxY'] = maxY;
        obj['maxZ'] = maxZ;
        obj['minM'] = minM;
        obj['minTime'] = minTime;
        obj['minX'] = minX;
        obj['minY'] = minY;
        obj['minZ'] = minZ;
    }

    /**
     * Constructs a <code>BoundingBox</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BoundingBox} obj Optional instance to populate.
     * @return {module:model/BoundingBox} The populated <code>BoundingBox</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BoundingBox();

            if (data.hasOwnProperty('maxM')) {
                obj['maxM'] = ApiClient.convertToType(data['maxM'], 'Number');
            }
            if (data.hasOwnProperty('maxTime')) {
                obj['maxTime'] = ApiClient.convertToType(data['maxTime'], 'String');
            }
            if (data.hasOwnProperty('maxX')) {
                obj['maxX'] = ApiClient.convertToType(data['maxX'], 'Number');
            }
            if (data.hasOwnProperty('maxY')) {
                obj['maxY'] = ApiClient.convertToType(data['maxY'], 'Number');
            }
            if (data.hasOwnProperty('maxZ')) {
                obj['maxZ'] = ApiClient.convertToType(data['maxZ'], 'Number');
            }
            if (data.hasOwnProperty('minM')) {
                obj['minM'] = ApiClient.convertToType(data['minM'], 'Number');
            }
            if (data.hasOwnProperty('minTime')) {
                obj['minTime'] = ApiClient.convertToType(data['minTime'], 'String');
            }
            if (data.hasOwnProperty('minX')) {
                obj['minX'] = ApiClient.convertToType(data['minX'], 'Number');
            }
            if (data.hasOwnProperty('minY')) {
                obj['minY'] = ApiClient.convertToType(data['minY'], 'Number');
            }
            if (data.hasOwnProperty('minZ')) {
                obj['minZ'] = ApiClient.convertToType(data['minZ'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BoundingBox</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BoundingBox</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of BoundingBox.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['maxTime'] && !(typeof data['maxTime'] === 'string' || data['maxTime'] instanceof String)) {
            throw new Error("Expected the field `maxTime` to be a primitive type in the JSON string but got " + data['maxTime']);
        }
        // ensure the json data is a string
        if (data['minTime'] && !(typeof data['minTime'] === 'string' || data['minTime'] instanceof String)) {
            throw new Error("Expected the field `minTime` to be a primitive type in the JSON string but got " + data['minTime']);
        }

        return true;
    }


}

BoundingBox.RequiredProperties = ["maxM", "maxTime", "maxX", "maxY", "maxZ", "minM", "minTime", "minX", "minY", "minZ"];

/**
 * @member {Number} maxM
 */
BoundingBox.prototype['maxM'] = undefined;

/**
 * @member {String} maxTime
 */
BoundingBox.prototype['maxTime'] = undefined;

/**
 * @member {Number} maxX
 */
BoundingBox.prototype['maxX'] = undefined;

/**
 * @member {Number} maxY
 */
BoundingBox.prototype['maxY'] = undefined;

/**
 * @member {Number} maxZ
 */
BoundingBox.prototype['maxZ'] = undefined;

/**
 * @member {Number} minM
 */
BoundingBox.prototype['minM'] = undefined;

/**
 * @member {String} minTime
 */
BoundingBox.prototype['minTime'] = undefined;

/**
 * @member {Number} minX
 */
BoundingBox.prototype['minX'] = undefined;

/**
 * @member {Number} minY
 */
BoundingBox.prototype['minY'] = undefined;

/**
 * @member {Number} minZ
 */
BoundingBox.prototype['minZ'] = undefined;






export default BoundingBox;

