/**
 * GpsGate API Documentation
 * GpsGate API service
 *
 * The version of the OpenAPI document: v.1
 * Contact: support@gpsgate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Position2D from './Position2D';

/**
 * The CircleShape model module.
 * @module model/CircleShape
 * @version v.1
 */
class CircleShape {
    /**
     * Constructs a new <code>CircleShape</code>.
     * @alias module:model/CircleShape
     * @param radius {Number} 
     */
    constructor(radius) { 
        
        CircleShape.initialize(this, radius);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, radius) { 
        obj['radius'] = radius;
    }

    /**
     * Constructs a <code>CircleShape</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CircleShape} obj Optional instance to populate.
     * @return {module:model/CircleShape} The populated <code>CircleShape</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CircleShape();

            if (data.hasOwnProperty('center')) {
                obj['center'] = Position2D.constructFromObject(data['center']);
            }
            if (data.hasOwnProperty('radius')) {
                obj['radius'] = ApiClient.convertToType(data['radius'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CircleShape</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CircleShape</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CircleShape.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `center`
        if (data['center']) { // data not null
          Position2D.validateJSON(data['center']);
        }

        return true;
    }


}

CircleShape.RequiredProperties = ["radius"];

/**
 * @member {module:model/Position2D} center
 */
CircleShape.prototype['center'] = undefined;

/**
 * @member {Number} radius
 */
CircleShape.prototype['radius'] = undefined;






export default CircleShape;

