/**
 * GpsGate API Documentation
 * GpsGate API service
 *
 * The version of the OpenAPI document: v.1
 * Contact: support@gpsgate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CustomFieldsCustomFieldModel model module.
 * @module model/CustomFieldsCustomFieldModel
 * @version v.1
 */
class CustomFieldsCustomFieldModel {
    /**
     * Constructs a new <code>CustomFieldsCustomFieldModel</code>.
     * @alias module:model/CustomFieldsCustomFieldModel
     * @param id {Number} 
     * @param required {Boolean} 
     * @param type {Number} 
     */
    constructor(id, required, type) { 
        
        CustomFieldsCustomFieldModel.initialize(this, id, required, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, required, type) { 
        obj['id'] = id;
        obj['required'] = required;
        obj['type'] = type;
    }

    /**
     * Constructs a <code>CustomFieldsCustomFieldModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CustomFieldsCustomFieldModel} obj Optional instance to populate.
     * @return {module:model/CustomFieldsCustomFieldModel} The populated <code>CustomFieldsCustomFieldModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomFieldsCustomFieldModel();

            if (data.hasOwnProperty('defaultValue')) {
                obj['defaultValue'] = ApiClient.convertToType(data['defaultValue'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('objectType')) {
                obj['objectType'] = ApiClient.convertToType(data['objectType'], 'String');
            }
            if (data.hasOwnProperty('required')) {
                obj['required'] = ApiClient.convertToType(data['required'], 'Boolean');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CustomFieldsCustomFieldModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CustomFieldsCustomFieldModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CustomFieldsCustomFieldModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['defaultValue'] && !(typeof data['defaultValue'] === 'string' || data['defaultValue'] instanceof String)) {
            throw new Error("Expected the field `defaultValue` to be a primitive type in the JSON string but got " + data['defaultValue']);
        }
        // ensure the json data is a string
        if (data['label'] && !(typeof data['label'] === 'string' || data['label'] instanceof String)) {
            throw new Error("Expected the field `label` to be a primitive type in the JSON string but got " + data['label']);
        }
        // ensure the json data is a string
        if (data['objectType'] && !(typeof data['objectType'] === 'string' || data['objectType'] instanceof String)) {
            throw new Error("Expected the field `objectType` to be a primitive type in the JSON string but got " + data['objectType']);
        }

        return true;
    }


}

CustomFieldsCustomFieldModel.RequiredProperties = ["id", "required", "type"];

/**
 * @member {String} defaultValue
 */
CustomFieldsCustomFieldModel.prototype['defaultValue'] = undefined;

/**
 * @member {Number} id
 */
CustomFieldsCustomFieldModel.prototype['id'] = undefined;

/**
 * @member {String} label
 */
CustomFieldsCustomFieldModel.prototype['label'] = undefined;

/**
 * @member {String} objectType
 */
CustomFieldsCustomFieldModel.prototype['objectType'] = undefined;

/**
 * @member {Boolean} required
 */
CustomFieldsCustomFieldModel.prototype['required'] = undefined;

/**
 * @member {Number} type
 */
CustomFieldsCustomFieldModel.prototype['type'] = undefined;






export default CustomFieldsCustomFieldModel;

