/**
 * GpsGate API Documentation
 * GpsGate API service
 *
 * The version of the OpenAPI document: v.1
 * Contact: support@gpsgate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EventRuleModel model module.
 * @module model/EventRuleModel
 * @version v.1
 */
class EventRuleModel {
    /**
     * Constructs a new <code>EventRuleModel</code>.
     * @alias module:model/EventRuleModel
     * @param applicationID {Number} 
     * @param disabled {Boolean} 
     * @param id {Number} 
     */
    constructor(applicationID, disabled, id) { 
        
        EventRuleModel.initialize(this, applicationID, disabled, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, applicationID, disabled, id) { 
        obj['applicationID'] = applicationID;
        obj['disabled'] = disabled;
        obj['id'] = id;
    }

    /**
     * Constructs a <code>EventRuleModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EventRuleModel} obj Optional instance to populate.
     * @return {module:model/EventRuleModel} The populated <code>EventRuleModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EventRuleModel();

            if (data.hasOwnProperty('applicationID')) {
                obj['applicationID'] = ApiClient.convertToType(data['applicationID'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('disabled')) {
                obj['disabled'] = ApiClient.convertToType(data['disabled'], 'Boolean');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('tagIDs')) {
                obj['tagIDs'] = ApiClient.convertToType(data['tagIDs'], ['Number']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EventRuleModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EventRuleModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EventRuleModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['tagIDs'])) {
            throw new Error("Expected the field `tagIDs` to be an array in the JSON data but got " + data['tagIDs']);
        }

        return true;
    }


}

EventRuleModel.RequiredProperties = ["applicationID", "disabled", "id"];

/**
 * @member {Number} applicationID
 */
EventRuleModel.prototype['applicationID'] = undefined;

/**
 * @member {String} description
 */
EventRuleModel.prototype['description'] = undefined;

/**
 * @member {Boolean} disabled
 */
EventRuleModel.prototype['disabled'] = undefined;

/**
 * @member {Number} id
 */
EventRuleModel.prototype['id'] = undefined;

/**
 * @member {String} name
 */
EventRuleModel.prototype['name'] = undefined;

/**
 * @member {Array.<Number>} tagIDs
 */
EventRuleModel.prototype['tagIDs'] = undefined;






export default EventRuleModel;

