/**
 * GpsGate API Documentation
 * GpsGate API service
 *
 * The version of the OpenAPI document: v.1
 * Contact: support@gpsgate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class GateUserNetStatus.
* @enum {}
* @readonly
*/
export default class GateUserNetStatus {
    
        /**
         * value: "Sending"
         * @const
         */
        "Sending" = "Sending";

    
        /**
         * value: "Connected"
         * @const
         */
        "Connected" = "Connected";

    
        /**
         * value: "Offline"
         * @const
         */
        "Offline" = "Offline";

    
        /**
         * value: "NeverBeenConnected"
         * @const
         */
        "NeverBeenConnected" = "NeverBeenConnected";

    

    /**
    * Returns a <code>GateUserNetStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/GateUserNetStatus} The enum <code>GateUserNetStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

