/**
 * GpsGate API Documentation
 * GpsGate API service
 *
 * The version of the OpenAPI document: v.1
 * Contact: support@gpsgate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CircleShape from './CircleShape';
import PolygonShape from './PolygonShape';
import RouteShape from './RouteShape';
import ShapeType from './ShapeType';

/**
 * The GeofenceModel model module.
 * @module model/GeofenceModel
 * @version v.1
 */
class GeofenceModel {
    /**
     * Constructs a new <code>GeofenceModel</code>.
     * @alias module:model/GeofenceModel
     * @param id {Number} 
     * @param shapeType {module:model/ShapeType} 
     */
    constructor(id, shapeType) { 
        
        GeofenceModel.initialize(this, id, shapeType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, shapeType) { 
        obj['id'] = id;
        obj['shapeType'] = shapeType;
    }

    /**
     * Constructs a <code>GeofenceModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GeofenceModel} obj Optional instance to populate.
     * @return {module:model/GeofenceModel} The populated <code>GeofenceModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GeofenceModel();

            if (data.hasOwnProperty('circleShape')) {
                obj['circleShape'] = CircleShape.constructFromObject(data['circleShape']);
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('polygonShape')) {
                obj['polygonShape'] = PolygonShape.constructFromObject(data['polygonShape']);
            }
            if (data.hasOwnProperty('routeShape')) {
                obj['routeShape'] = RouteShape.constructFromObject(data['routeShape']);
            }
            if (data.hasOwnProperty('shapeType')) {
                obj['shapeType'] = ShapeType.constructFromObject(data['shapeType']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GeofenceModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GeofenceModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GeofenceModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `circleShape`
        if (data['circleShape']) { // data not null
          CircleShape.validateJSON(data['circleShape']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // validate the optional field `polygonShape`
        if (data['polygonShape']) { // data not null
          PolygonShape.validateJSON(data['polygonShape']);
        }
        // validate the optional field `routeShape`
        if (data['routeShape']) { // data not null
          RouteShape.validateJSON(data['routeShape']);
        }

        return true;
    }


}

GeofenceModel.RequiredProperties = ["id", "shapeType"];

/**
 * @member {module:model/CircleShape} circleShape
 */
GeofenceModel.prototype['circleShape'] = undefined;

/**
 * @member {String} description
 */
GeofenceModel.prototype['description'] = undefined;

/**
 * @member {Number} id
 */
GeofenceModel.prototype['id'] = undefined;

/**
 * @member {String} name
 */
GeofenceModel.prototype['name'] = undefined;

/**
 * @member {module:model/PolygonShape} polygonShape
 */
GeofenceModel.prototype['polygonShape'] = undefined;

/**
 * @member {module:model/RouteShape} routeShape
 */
GeofenceModel.prototype['routeShape'] = undefined;

/**
 * @member {module:model/ShapeType} shapeType
 */
GeofenceModel.prototype['shapeType'] = undefined;






export default GeofenceModel;

