/**
 * GpsGate API Documentation
 * GpsGate API service
 *
 * The version of the OpenAPI document: v.1
 * Contact: support@gpsgate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GeofenceGroupModel model module.
 * @module model/GeofenceGroupModel
 * @version v.1
 */
class GeofenceGroupModel {
    /**
     * Constructs a new <code>GeofenceGroupModel</code>.
     * @alias module:model/GeofenceGroupModel
     * @param id {Number} 
     * @param pinned {Boolean} 
     * @param useInGeocoding {Boolean} 
     */
    constructor(id, pinned, useInGeocoding) { 
        
        GeofenceGroupModel.initialize(this, id, pinned, useInGeocoding);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, pinned, useInGeocoding) { 
        obj['id'] = id;
        obj['pinned'] = pinned;
        obj['useInGeocoding'] = useInGeocoding;
    }

    /**
     * Constructs a <code>GeofenceGroupModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GeofenceGroupModel} obj Optional instance to populate.
     * @return {module:model/GeofenceGroupModel} The populated <code>GeofenceGroupModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GeofenceGroupModel();

            if (data.hasOwnProperty('colour')) {
                obj['colour'] = ApiClient.convertToType(data['colour'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('geofenceIds')) {
                obj['geofenceIds'] = ApiClient.convertToType(data['geofenceIds'], ['Number']);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('pinned')) {
                obj['pinned'] = ApiClient.convertToType(data['pinned'], 'Boolean');
            }
            if (data.hasOwnProperty('useInGeocoding')) {
                obj['useInGeocoding'] = ApiClient.convertToType(data['useInGeocoding'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GeofenceGroupModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GeofenceGroupModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GeofenceGroupModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['colour'] && !(typeof data['colour'] === 'string' || data['colour'] instanceof String)) {
            throw new Error("Expected the field `colour` to be a primitive type in the JSON string but got " + data['colour']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['geofenceIds'])) {
            throw new Error("Expected the field `geofenceIds` to be an array in the JSON data but got " + data['geofenceIds']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}

GeofenceGroupModel.RequiredProperties = ["id", "pinned", "useInGeocoding"];

/**
 * @member {String} colour
 */
GeofenceGroupModel.prototype['colour'] = undefined;

/**
 * @member {String} description
 */
GeofenceGroupModel.prototype['description'] = undefined;

/**
 * @member {Array.<Number>} geofenceIds
 */
GeofenceGroupModel.prototype['geofenceIds'] = undefined;

/**
 * @member {Number} id
 */
GeofenceGroupModel.prototype['id'] = undefined;

/**
 * @member {String} name
 */
GeofenceGroupModel.prototype['name'] = undefined;

/**
 * @member {Boolean} pinned
 */
GeofenceGroupModel.prototype['pinned'] = undefined;

/**
 * @member {Boolean} useInGeocoding
 */
GeofenceGroupModel.prototype['useInGeocoding'] = undefined;






export default GeofenceGroupModel;

