/**
 * GpsGate API Documentation
 * GpsGate API service
 *
 * The version of the OpenAPI document: v.1
 * Contact: support@gpsgate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Position from './Position';

/**
 * The Location model module.
 * @module model/Location
 * @version v.1
 */
class Location {
    /**
     * Constructs a new <code>Location</code>.
     * @alias module:model/Location
     */
    constructor() { 
        
        Location.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Location</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Location} obj Optional instance to populate.
     * @return {module:model/Location} The populated <code>Location</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Location();

            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('administrativeAreaName')) {
                obj['administrativeAreaName'] = ApiClient.convertToType(data['administrativeAreaName'], 'String');
            }
            if (data.hasOwnProperty('cityName')) {
                obj['cityName'] = ApiClient.convertToType(data['cityName'], 'String');
            }
            if (data.hasOwnProperty('countryName')) {
                obj['countryName'] = ApiClient.convertToType(data['countryName'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('formattedResult')) {
                obj['formattedResult'] = ApiClient.convertToType(data['formattedResult'], 'String');
            }
            if (data.hasOwnProperty('neighborhood')) {
                obj['neighborhood'] = ApiClient.convertToType(data['neighborhood'], 'String');
            }
            if (data.hasOwnProperty('position')) {
                obj['position'] = Position.constructFromObject(data['position']);
            }
            if (data.hasOwnProperty('postalCodeNumber')) {
                obj['postalCodeNumber'] = ApiClient.convertToType(data['postalCodeNumber'], 'String');
            }
            if (data.hasOwnProperty('streetBox')) {
                obj['streetBox'] = ApiClient.convertToType(data['streetBox'], 'String');
            }
            if (data.hasOwnProperty('streetName')) {
                obj['streetName'] = ApiClient.convertToType(data['streetName'], 'String');
            }
            if (data.hasOwnProperty('streetNumber')) {
                obj['streetNumber'] = ApiClient.convertToType(data['streetNumber'], 'String');
            }
            if (data.hasOwnProperty('subAdministrativeAreaName')) {
                obj['subAdministrativeAreaName'] = ApiClient.convertToType(data['subAdministrativeAreaName'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Location</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Location</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['address'] && !(typeof data['address'] === 'string' || data['address'] instanceof String)) {
            throw new Error("Expected the field `address` to be a primitive type in the JSON string but got " + data['address']);
        }
        // ensure the json data is a string
        if (data['administrativeAreaName'] && !(typeof data['administrativeAreaName'] === 'string' || data['administrativeAreaName'] instanceof String)) {
            throw new Error("Expected the field `administrativeAreaName` to be a primitive type in the JSON string but got " + data['administrativeAreaName']);
        }
        // ensure the json data is a string
        if (data['cityName'] && !(typeof data['cityName'] === 'string' || data['cityName'] instanceof String)) {
            throw new Error("Expected the field `cityName` to be a primitive type in the JSON string but got " + data['cityName']);
        }
        // ensure the json data is a string
        if (data['countryName'] && !(typeof data['countryName'] === 'string' || data['countryName'] instanceof String)) {
            throw new Error("Expected the field `countryName` to be a primitive type in the JSON string but got " + data['countryName']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['formattedResult'] && !(typeof data['formattedResult'] === 'string' || data['formattedResult'] instanceof String)) {
            throw new Error("Expected the field `formattedResult` to be a primitive type in the JSON string but got " + data['formattedResult']);
        }
        // ensure the json data is a string
        if (data['neighborhood'] && !(typeof data['neighborhood'] === 'string' || data['neighborhood'] instanceof String)) {
            throw new Error("Expected the field `neighborhood` to be a primitive type in the JSON string but got " + data['neighborhood']);
        }
        // validate the optional field `position`
        if (data['position']) { // data not null
          Position.validateJSON(data['position']);
        }
        // ensure the json data is a string
        if (data['postalCodeNumber'] && !(typeof data['postalCodeNumber'] === 'string' || data['postalCodeNumber'] instanceof String)) {
            throw new Error("Expected the field `postalCodeNumber` to be a primitive type in the JSON string but got " + data['postalCodeNumber']);
        }
        // ensure the json data is a string
        if (data['streetBox'] && !(typeof data['streetBox'] === 'string' || data['streetBox'] instanceof String)) {
            throw new Error("Expected the field `streetBox` to be a primitive type in the JSON string but got " + data['streetBox']);
        }
        // ensure the json data is a string
        if (data['streetName'] && !(typeof data['streetName'] === 'string' || data['streetName'] instanceof String)) {
            throw new Error("Expected the field `streetName` to be a primitive type in the JSON string but got " + data['streetName']);
        }
        // ensure the json data is a string
        if (data['streetNumber'] && !(typeof data['streetNumber'] === 'string' || data['streetNumber'] instanceof String)) {
            throw new Error("Expected the field `streetNumber` to be a primitive type in the JSON string but got " + data['streetNumber']);
        }
        // ensure the json data is a string
        if (data['subAdministrativeAreaName'] && !(typeof data['subAdministrativeAreaName'] === 'string' || data['subAdministrativeAreaName'] instanceof String)) {
            throw new Error("Expected the field `subAdministrativeAreaName` to be a primitive type in the JSON string but got " + data['subAdministrativeAreaName']);
        }

        return true;
    }


}



/**
 * @member {String} address
 */
Location.prototype['address'] = undefined;

/**
 * @member {String} administrativeAreaName
 */
Location.prototype['administrativeAreaName'] = undefined;

/**
 * @member {String} cityName
 */
Location.prototype['cityName'] = undefined;

/**
 * @member {String} countryName
 */
Location.prototype['countryName'] = undefined;

/**
 * @member {String} description
 */
Location.prototype['description'] = undefined;

/**
 * @member {String} formattedResult
 */
Location.prototype['formattedResult'] = undefined;

/**
 * @member {String} neighborhood
 */
Location.prototype['neighborhood'] = undefined;

/**
 * @member {module:model/Position} position
 */
Location.prototype['position'] = undefined;

/**
 * @member {String} postalCodeNumber
 */
Location.prototype['postalCodeNumber'] = undefined;

/**
 * @member {String} streetBox
 */
Location.prototype['streetBox'] = undefined;

/**
 * @member {String} streetName
 */
Location.prototype['streetName'] = undefined;

/**
 * @member {String} streetNumber
 */
Location.prototype['streetNumber'] = undefined;

/**
 * @member {String} subAdministrativeAreaName
 */
Location.prototype['subAdministrativeAreaName'] = undefined;






export default Location;

