/**
 * GpsGate API Documentation
 * GpsGate API service
 *
 * The version of the OpenAPI document: v.1
 * Contact: support@gpsgate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MessageProviderModel model module.
 * @module model/MessageProviderModel
 * @version v.1
 */
class MessageProviderModel {
    /**
     * Constructs a new <code>MessageProviderModel</code>.
     * @alias module:model/MessageProviderModel
     * @param callInterval {Number} 
     * @param customLong {Number} 
     * @param defaultProvider {Boolean} 
     * @param enabled {Boolean} 
     * @param id {Number} 
     * @param isStarted {Boolean} 
     * @param timeout {Number} 
     * @param typeID {Number} 
     */
    constructor(callInterval, customLong, defaultProvider, enabled, id, isStarted, timeout, typeID) { 
        
        MessageProviderModel.initialize(this, callInterval, customLong, defaultProvider, enabled, id, isStarted, timeout, typeID);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, callInterval, customLong, defaultProvider, enabled, id, isStarted, timeout, typeID) { 
        obj['callInterval'] = callInterval;
        obj['customLong'] = customLong;
        obj['defaultProvider'] = defaultProvider;
        obj['enabled'] = enabled;
        obj['id'] = id;
        obj['isStarted'] = isStarted;
        obj['timeout'] = timeout;
        obj['typeID'] = typeID;
    }

    /**
     * Constructs a <code>MessageProviderModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MessageProviderModel} obj Optional instance to populate.
     * @return {module:model/MessageProviderModel} The populated <code>MessageProviderModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MessageProviderModel();

            if (data.hasOwnProperty('callInterval')) {
                obj['callInterval'] = ApiClient.convertToType(data['callInterval'], 'Number');
            }
            if (data.hasOwnProperty('customLong')) {
                obj['customLong'] = ApiClient.convertToType(data['customLong'], 'Number');
            }
            if (data.hasOwnProperty('customString')) {
                obj['customString'] = ApiClient.convertToType(data['customString'], 'String');
            }
            if (data.hasOwnProperty('defaultProvider')) {
                obj['defaultProvider'] = ApiClient.convertToType(data['defaultProvider'], 'Boolean');
            }
            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('isStarted')) {
                obj['isStarted'] = ApiClient.convertToType(data['isStarted'], 'Boolean');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('routeLabel')) {
                obj['routeLabel'] = ApiClient.convertToType(data['routeLabel'], 'String');
            }
            if (data.hasOwnProperty('timeout')) {
                obj['timeout'] = ApiClient.convertToType(data['timeout'], 'Number');
            }
            if (data.hasOwnProperty('typeID')) {
                obj['typeID'] = ApiClient.convertToType(data['typeID'], 'Number');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MessageProviderModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MessageProviderModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MessageProviderModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['customString'] && !(typeof data['customString'] === 'string' || data['customString'] instanceof String)) {
            throw new Error("Expected the field `customString` to be a primitive type in the JSON string but got " + data['customString']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['password'] && !(typeof data['password'] === 'string' || data['password'] instanceof String)) {
            throw new Error("Expected the field `password` to be a primitive type in the JSON string but got " + data['password']);
        }
        // ensure the json data is a string
        if (data['routeLabel'] && !(typeof data['routeLabel'] === 'string' || data['routeLabel'] instanceof String)) {
            throw new Error("Expected the field `routeLabel` to be a primitive type in the JSON string but got " + data['routeLabel']);
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }

        return true;
    }


}

MessageProviderModel.RequiredProperties = ["callInterval", "customLong", "defaultProvider", "enabled", "id", "isStarted", "timeout", "typeID"];

/**
 * @member {Number} callInterval
 */
MessageProviderModel.prototype['callInterval'] = undefined;

/**
 * @member {Number} customLong
 */
MessageProviderModel.prototype['customLong'] = undefined;

/**
 * @member {String} customString
 */
MessageProviderModel.prototype['customString'] = undefined;

/**
 * @member {Boolean} defaultProvider
 */
MessageProviderModel.prototype['defaultProvider'] = undefined;

/**
 * @member {Boolean} enabled
 */
MessageProviderModel.prototype['enabled'] = undefined;

/**
 * @member {Number} id
 */
MessageProviderModel.prototype['id'] = undefined;

/**
 * @member {Boolean} isStarted
 */
MessageProviderModel.prototype['isStarted'] = undefined;

/**
 * @member {String} name
 */
MessageProviderModel.prototype['name'] = undefined;

/**
 * @member {String} password
 */
MessageProviderModel.prototype['password'] = undefined;

/**
 * @member {String} routeLabel
 */
MessageProviderModel.prototype['routeLabel'] = undefined;

/**
 * @member {Number} timeout
 */
MessageProviderModel.prototype['timeout'] = undefined;

/**
 * @member {Number} typeID
 */
MessageProviderModel.prototype['typeID'] = undefined;

/**
 * @member {String} url
 */
MessageProviderModel.prototype['url'] = undefined;

/**
 * @member {String} username
 */
MessageProviderModel.prototype['username'] = undefined;






export default MessageProviderModel;

