/**
 * GpsGate API Documentation
 * GpsGate API service
 *
 * The version of the OpenAPI document: v.1
 * Contact: support@gpsgate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MSISDN model module.
 * @module model/MSISDN
 * @version v.1
 */
class MSISDN {
    /**
     * Constructs a new <code>MSISDN</code>.
     * @alias module:model/MSISDN
     */
    constructor() { 
        
        MSISDN.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MSISDN</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MSISDN} obj Optional instance to populate.
     * @return {module:model/MSISDN} The populated <code>MSISDN</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MSISDN();

            if (data.hasOwnProperty('raw')) {
                obj['raw'] = ApiClient.convertToType(data['raw'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MSISDN</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MSISDN</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['raw'] && !(typeof data['raw'] === 'string' || data['raw'] instanceof String)) {
            throw new Error("Expected the field `raw` to be a primitive type in the JSON string but got " + data['raw']);
        }

        return true;
    }


}



/**
 * @member {String} raw
 */
MSISDN.prototype['raw'] = undefined;






export default MSISDN;

