/**
 * GpsGate API Documentation
 * GpsGate API service
 *
 * The version of the OpenAPI document: v.1
 * Contact: support@gpsgate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OneWireBag model module.
 * @module model/OneWireBag
 * @version v.1
 */
class OneWireBag {
    /**
     * Constructs a new <code>OneWireBag</code>.
     * @alias module:model/OneWireBag
     * @param deviceDefinitionID {Number} 
     * @param deviceID {Number} 
     */
    constructor(deviceDefinitionID, deviceID) { 
        
        OneWireBag.initialize(this, deviceDefinitionID, deviceID);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, deviceDefinitionID, deviceID) { 
        obj['deviceDefinitionID'] = deviceDefinitionID;
        obj['deviceID'] = deviceID;
    }

    /**
     * Constructs a <code>OneWireBag</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OneWireBag} obj Optional instance to populate.
     * @return {module:model/OneWireBag} The populated <code>OneWireBag</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OneWireBag();

            if (data.hasOwnProperty('deviceDefinitionID')) {
                obj['deviceDefinitionID'] = ApiClient.convertToType(data['deviceDefinitionID'], 'Number');
            }
            if (data.hasOwnProperty('deviceID')) {
                obj['deviceID'] = ApiClient.convertToType(data['deviceID'], 'Number');
            }
            if (data.hasOwnProperty('oneWireID')) {
                obj['oneWireID'] = ApiClient.convertToType(data['oneWireID'], 'String');
            }
            if (data.hasOwnProperty('variableName')) {
                obj['variableName'] = ApiClient.convertToType(data['variableName'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OneWireBag</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OneWireBag</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of OneWireBag.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['oneWireID'] && !(typeof data['oneWireID'] === 'string' || data['oneWireID'] instanceof String)) {
            throw new Error("Expected the field `oneWireID` to be a primitive type in the JSON string but got " + data['oneWireID']);
        }
        // ensure the json data is a string
        if (data['variableName'] && !(typeof data['variableName'] === 'string' || data['variableName'] instanceof String)) {
            throw new Error("Expected the field `variableName` to be a primitive type in the JSON string but got " + data['variableName']);
        }

        return true;
    }


}

OneWireBag.RequiredProperties = ["deviceDefinitionID", "deviceID"];

/**
 * @member {Number} deviceDefinitionID
 */
OneWireBag.prototype['deviceDefinitionID'] = undefined;

/**
 * @member {Number} deviceID
 */
OneWireBag.prototype['deviceID'] = undefined;

/**
 * @member {String} oneWireID
 */
OneWireBag.prototype['oneWireID'] = undefined;

/**
 * @member {String} variableName
 */
OneWireBag.prototype['variableName'] = undefined;






export default OneWireBag;

