/**
 * GpsGate API Documentation
 * GpsGate API service
 *
 * The version of the OpenAPI document: v.1
 * Contact: support@gpsgate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Position2D from './Position2D';

/**
 * The PolygonShape model module.
 * @module model/PolygonShape
 * @version v.1
 */
class PolygonShape {
    /**
     * Constructs a new <code>PolygonShape</code>.
     * @alias module:model/PolygonShape
     */
    constructor() { 
        
        PolygonShape.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PolygonShape</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PolygonShape} obj Optional instance to populate.
     * @return {module:model/PolygonShape} The populated <code>PolygonShape</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PolygonShape();

            if (data.hasOwnProperty('vertices')) {
                obj['vertices'] = ApiClient.convertToType(data['vertices'], [Position2D]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PolygonShape</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PolygonShape</code>.
     */
    static validateJSON(data) {
        if (data['vertices']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['vertices'])) {
                throw new Error("Expected the field `vertices` to be an array in the JSON data but got " + data['vertices']);
            }
            // validate the optional field `vertices` (array)
            for (const item of data['vertices']) {
                Position2D.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/Position2D>} vertices
 */
PolygonShape.prototype['vertices'] = undefined;






export default PolygonShape;

