/**
 * GpsGate API Documentation
 * GpsGate API service
 *
 * The version of the OpenAPI document: v.1
 * Contact: support@gpsgate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Location from './Location';

/**
 * The ReverseGeocodeResult model module.
 * @module model/ReverseGeocodeResult
 * @version v.1
 */
class ReverseGeocodeResult {
    /**
     * Constructs a new <code>ReverseGeocodeResult</code>.
     * @alias module:model/ReverseGeocodeResult
     */
    constructor() { 
        
        ReverseGeocodeResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ReverseGeocodeResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReverseGeocodeResult} obj Optional instance to populate.
     * @return {module:model/ReverseGeocodeResult} The populated <code>ReverseGeocodeResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReverseGeocodeResult();

            if (data.hasOwnProperty('geocoderProviderSource')) {
                obj['geocoderProviderSource'] = ApiClient.convertToType(data['geocoderProviderSource'], 'String');
            }
            if (data.hasOwnProperty('location')) {
                obj['location'] = Location.constructFromObject(data['location']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ReverseGeocodeResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ReverseGeocodeResult</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['geocoderProviderSource'] && !(typeof data['geocoderProviderSource'] === 'string' || data['geocoderProviderSource'] instanceof String)) {
            throw new Error("Expected the field `geocoderProviderSource` to be a primitive type in the JSON string but got " + data['geocoderProviderSource']);
        }
        // validate the optional field `location`
        if (data['location']) { // data not null
          Location.validateJSON(data['location']);
        }

        return true;
    }


}



/**
 * @member {String} geocoderProviderSource
 */
ReverseGeocodeResult.prototype['geocoderProviderSource'] = undefined;

/**
 * @member {module:model/Location} location
 */
ReverseGeocodeResult.prototype['location'] = undefined;






export default ReverseGeocodeResult;

