/**
 * GpsGate API Documentation
 * GpsGate API service
 *
 * The version of the OpenAPI document: v.1
 * Contact: support@gpsgate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Position2D from './Position2D';

/**
 * The RouteShape model module.
 * @module model/RouteShape
 * @version v.1
 */
class RouteShape {
    /**
     * Constructs a new <code>RouteShape</code>.
     * @alias module:model/RouteShape
     * @param radius {Number} 
     */
    constructor(radius) { 
        
        RouteShape.initialize(this, radius);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, radius) { 
        obj['radius'] = radius;
    }

    /**
     * Constructs a <code>RouteShape</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RouteShape} obj Optional instance to populate.
     * @return {module:model/RouteShape} The populated <code>RouteShape</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RouteShape();

            if (data.hasOwnProperty('radius')) {
                obj['radius'] = ApiClient.convertToType(data['radius'], 'Number');
            }
            if (data.hasOwnProperty('vertices')) {
                obj['vertices'] = ApiClient.convertToType(data['vertices'], [Position2D]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RouteShape</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RouteShape</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RouteShape.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['vertices']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['vertices'])) {
                throw new Error("Expected the field `vertices` to be an array in the JSON data but got " + data['vertices']);
            }
            // validate the optional field `vertices` (array)
            for (const item of data['vertices']) {
                Position2D.validateJSON(item);
            };
        }

        return true;
    }


}

RouteShape.RequiredProperties = ["radius"];

/**
 * @member {Number} radius
 */
RouteShape.prototype['radius'] = undefined;

/**
 * @member {Array.<module:model/Position2D>} vertices
 */
RouteShape.prototype['vertices'] = undefined;






export default RouteShape;

