/**
 * GpsGate API Documentation
 * GpsGate API service
 *
 * The version of the OpenAPI document: v.1
 * Contact: support@gpsgate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ShapeType.
* @enum {}
* @readonly
*/
export default class ShapeType {
    
        /**
         * value: "Polygon"
         * @const
         */
        "Polygon" = "Polygon";

    
        /**
         * value: "Circle"
         * @const
         */
        "Circle" = "Circle";

    
        /**
         * value: "Route"
         * @const
         */
        "Route" = "Route";

    

    /**
    * Returns a <code>ShapeType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ShapeType} The enum <code>ShapeType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

