/**
 * GpsGate API Documentation
 * GpsGate API service
 *
 * The version of the OpenAPI document: v.1
 * Contact: support@gpsgate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Position from './Position';
import Velocity from './Velocity';

/**
 * The TrackPoint model module.
 * @module model/TrackPoint
 * @version v.1
 */
class TrackPoint {
    /**
     * Constructs a new <code>TrackPoint</code>.
     * @alias module:model/TrackPoint
     * @param uTC {String} 
     * @param valid {Boolean} 
     */
    constructor(uTC, valid) { 
        
        TrackPoint.initialize(this, uTC, valid);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, uTC, valid) { 
        obj['uTC'] = uTC;
        obj['valid'] = valid;
    }

    /**
     * Constructs a <code>TrackPoint</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TrackPoint} obj Optional instance to populate.
     * @return {module:model/TrackPoint} The populated <code>TrackPoint</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TrackPoint();

            if (data.hasOwnProperty('position')) {
                obj['position'] = Position.constructFromObject(data['position']);
            }
            if (data.hasOwnProperty('uTC')) {
                obj['uTC'] = ApiClient.convertToType(data['uTC'], 'String');
            }
            if (data.hasOwnProperty('valid')) {
                obj['valid'] = ApiClient.convertToType(data['valid'], 'Boolean');
            }
            if (data.hasOwnProperty('velocity')) {
                obj['velocity'] = Velocity.constructFromObject(data['velocity']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TrackPoint</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TrackPoint</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TrackPoint.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `position`
        if (data['position']) { // data not null
          Position.validateJSON(data['position']);
        }
        // ensure the json data is a string
        if (data['uTC'] && !(typeof data['uTC'] === 'string' || data['uTC'] instanceof String)) {
            throw new Error("Expected the field `uTC` to be a primitive type in the JSON string but got " + data['uTC']);
        }
        // validate the optional field `velocity`
        if (data['velocity']) { // data not null
          Velocity.validateJSON(data['velocity']);
        }

        return true;
    }


}

TrackPoint.RequiredProperties = ["uTC", "valid"];

/**
 * @member {module:model/Position} position
 */
TrackPoint.prototype['position'] = undefined;

/**
 * @member {String} uTC
 */
TrackPoint.prototype['uTC'] = undefined;

/**
 * @member {Boolean} valid
 */
TrackPoint.prototype['valid'] = undefined;

/**
 * @member {module:model/Velocity} velocity
 */
TrackPoint.prototype['velocity'] = undefined;






export default TrackPoint;

