/**
 * GpsGate API Documentation
 * GpsGate API service
 *
 * The version of the OpenAPI document: v.1
 * Contact: support@gpsgate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Position from './Position';
import Velocity from './Velocity';

/**
 * The TrackModel model module.
 * @module model/TrackModel
 * @version v.1
 */
class TrackModel {
    /**
     * Constructs a new <code>TrackModel</code>.
     * @alias module:model/TrackModel
     * @param serverUtc {String} 
     * @param trackInfoId {Number} 
     * @param uTC {String} 
     * @param valid {Boolean} 
     */
    constructor(serverUtc, trackInfoId, uTC, valid) { 
        
        TrackModel.initialize(this, serverUtc, trackInfoId, uTC, valid);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, serverUtc, trackInfoId, uTC, valid) { 
        obj['serverUtc'] = serverUtc;
        obj['trackInfoId'] = trackInfoId;
        obj['uTC'] = uTC;
        obj['valid'] = valid;
    }

    /**
     * Constructs a <code>TrackModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TrackModel} obj Optional instance to populate.
     * @return {module:model/TrackModel} The populated <code>TrackModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TrackModel();

            if (data.hasOwnProperty('position')) {
                obj['position'] = Position.constructFromObject(data['position']);
            }
            if (data.hasOwnProperty('serverUtc')) {
                obj['serverUtc'] = ApiClient.convertToType(data['serverUtc'], 'String');
            }
            if (data.hasOwnProperty('trackInfoId')) {
                obj['trackInfoId'] = ApiClient.convertToType(data['trackInfoId'], 'Number');
            }
            if (data.hasOwnProperty('uTC')) {
                obj['uTC'] = ApiClient.convertToType(data['uTC'], 'String');
            }
            if (data.hasOwnProperty('valid')) {
                obj['valid'] = ApiClient.convertToType(data['valid'], 'Boolean');
            }
            if (data.hasOwnProperty('variables')) {
                obj['variables'] = ApiClient.convertToType(data['variables'], ['String']);
            }
            if (data.hasOwnProperty('velocity')) {
                obj['velocity'] = Velocity.constructFromObject(data['velocity']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TrackModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TrackModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TrackModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `position`
        if (data['position']) { // data not null
          Position.validateJSON(data['position']);
        }
        // ensure the json data is a string
        if (data['serverUtc'] && !(typeof data['serverUtc'] === 'string' || data['serverUtc'] instanceof String)) {
            throw new Error("Expected the field `serverUtc` to be a primitive type in the JSON string but got " + data['serverUtc']);
        }
        // ensure the json data is a string
        if (data['uTC'] && !(typeof data['uTC'] === 'string' || data['uTC'] instanceof String)) {
            throw new Error("Expected the field `uTC` to be a primitive type in the JSON string but got " + data['uTC']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['variables'])) {
            throw new Error("Expected the field `variables` to be an array in the JSON data but got " + data['variables']);
        }
        // validate the optional field `velocity`
        if (data['velocity']) { // data not null
          Velocity.validateJSON(data['velocity']);
        }

        return true;
    }


}

TrackModel.RequiredProperties = ["serverUtc", "trackInfoId", "uTC", "valid"];

/**
 * @member {module:model/Position} position
 */
TrackModel.prototype['position'] = undefined;

/**
 * @member {String} serverUtc
 */
TrackModel.prototype['serverUtc'] = undefined;

/**
 * @member {Number} trackInfoId
 */
TrackModel.prototype['trackInfoId'] = undefined;

/**
 * @member {String} uTC
 */
TrackModel.prototype['uTC'] = undefined;

/**
 * @member {Boolean} valid
 */
TrackModel.prototype['valid'] = undefined;

/**
 * @member {Array.<String>} variables
 */
TrackModel.prototype['variables'] = undefined;

/**
 * @member {module:model/Velocity} velocity
 */
TrackModel.prototype['velocity'] = undefined;






export default TrackModel;

