/**
 * GpsGate API Documentation
 * GpsGate API service
 *
 * The version of the OpenAPI document: v.1
 * Contact: support@gpsgate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DeviceModel from './DeviceModel';
import TrackPoint from './TrackPoint';
import UserIconModel from './UserIconModel';

/**
 * The UserModel model module.
 * @module model/UserModel
 * @version v.1
 */
class UserModel {
    /**
     * Constructs a new <code>UserModel</code>.
     * @alias module:model/UserModel
     * @param calculatedSpeed {Number} 
     * @param deviceActivity {String} 
     * @param id {Number} 
     * @param userTemplateID {Number} 
     */
    constructor(calculatedSpeed, deviceActivity, id, userTemplateID) { 
        
        UserModel.initialize(this, calculatedSpeed, deviceActivity, id, userTemplateID);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, calculatedSpeed, deviceActivity, id, userTemplateID) { 
        obj['calculatedSpeed'] = calculatedSpeed;
        obj['deviceActivity'] = deviceActivity;
        obj['id'] = id;
        obj['userTemplateID'] = userTemplateID;
    }

    /**
     * Constructs a <code>UserModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserModel} obj Optional instance to populate.
     * @return {module:model/UserModel} The populated <code>UserModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserModel();

            if (data.hasOwnProperty('calculatedSpeed')) {
                obj['calculatedSpeed'] = ApiClient.convertToType(data['calculatedSpeed'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('deviceActivity')) {
                obj['deviceActivity'] = ApiClient.convertToType(data['deviceActivity'], 'String');
            }
            if (data.hasOwnProperty('devices')) {
                obj['devices'] = ApiClient.convertToType(data['devices'], [DeviceModel]);
            }
            if (data.hasOwnProperty('driverID')) {
                obj['driverID'] = ApiClient.convertToType(data['driverID'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('icon')) {
                obj['icon'] = UserIconModel.constructFromObject(data['icon']);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('lastTransport')) {
                obj['lastTransport'] = ApiClient.convertToType(data['lastTransport'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('phoneNumber')) {
                obj['phoneNumber'] = ApiClient.convertToType(data['phoneNumber'], 'String');
            }
            if (data.hasOwnProperty('surname')) {
                obj['surname'] = ApiClient.convertToType(data['surname'], 'String');
            }
            if (data.hasOwnProperty('trackPoint')) {
                obj['trackPoint'] = TrackPoint.constructFromObject(data['trackPoint']);
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('userTemplateID')) {
                obj['userTemplateID'] = ApiClient.convertToType(data['userTemplateID'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UserModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['deviceActivity'] && !(typeof data['deviceActivity'] === 'string' || data['deviceActivity'] instanceof String)) {
            throw new Error("Expected the field `deviceActivity` to be a primitive type in the JSON string but got " + data['deviceActivity']);
        }
        if (data['devices']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['devices'])) {
                throw new Error("Expected the field `devices` to be an array in the JSON data but got " + data['devices']);
            }
            // validate the optional field `devices` (array)
            for (const item of data['devices']) {
                DeviceModel.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['driverID'] && !(typeof data['driverID'] === 'string' || data['driverID'] instanceof String)) {
            throw new Error("Expected the field `driverID` to be a primitive type in the JSON string but got " + data['driverID']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // validate the optional field `icon`
        if (data['icon']) { // data not null
          UserIconModel.validateJSON(data['icon']);
        }
        // ensure the json data is a string
        if (data['lastTransport'] && !(typeof data['lastTransport'] === 'string' || data['lastTransport'] instanceof String)) {
            throw new Error("Expected the field `lastTransport` to be a primitive type in the JSON string but got " + data['lastTransport']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['phoneNumber'] && !(typeof data['phoneNumber'] === 'string' || data['phoneNumber'] instanceof String)) {
            throw new Error("Expected the field `phoneNumber` to be a primitive type in the JSON string but got " + data['phoneNumber']);
        }
        // ensure the json data is a string
        if (data['surname'] && !(typeof data['surname'] === 'string' || data['surname'] instanceof String)) {
            throw new Error("Expected the field `surname` to be a primitive type in the JSON string but got " + data['surname']);
        }
        // validate the optional field `trackPoint`
        if (data['trackPoint']) { // data not null
          TrackPoint.validateJSON(data['trackPoint']);
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }

        return true;
    }


}

UserModel.RequiredProperties = ["calculatedSpeed", "deviceActivity", "id", "userTemplateID"];

/**
 * @member {Number} calculatedSpeed
 */
UserModel.prototype['calculatedSpeed'] = undefined;

/**
 * @member {String} description
 */
UserModel.prototype['description'] = undefined;

/**
 * @member {String} deviceActivity
 */
UserModel.prototype['deviceActivity'] = undefined;

/**
 * @member {Array.<module:model/DeviceModel>} devices
 */
UserModel.prototype['devices'] = undefined;

/**
 * @member {String} driverID
 */
UserModel.prototype['driverID'] = undefined;

/**
 * @member {String} email
 */
UserModel.prototype['email'] = undefined;

/**
 * @member {module:model/UserIconModel} icon
 */
UserModel.prototype['icon'] = undefined;

/**
 * @member {Number} id
 */
UserModel.prototype['id'] = undefined;

/**
 * @member {String} lastTransport
 */
UserModel.prototype['lastTransport'] = undefined;

/**
 * @member {String} name
 */
UserModel.prototype['name'] = undefined;

/**
 * @member {String} phoneNumber
 */
UserModel.prototype['phoneNumber'] = undefined;

/**
 * @member {String} surname
 */
UserModel.prototype['surname'] = undefined;

/**
 * @member {module:model/TrackPoint} trackPoint
 */
UserModel.prototype['trackPoint'] = undefined;

/**
 * @member {String} username
 */
UserModel.prototype['username'] = undefined;

/**
 * @member {Number} userTemplateID
 */
UserModel.prototype['userTemplateID'] = undefined;






export default UserModel;

