/**
 * GpsGate API Documentation
 * GpsGate API service
 *
 * The version of the OpenAPI document: v.1
 * Contact: support@gpsgate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Position from './Position';
import VariableStatusModel from './VariableStatusModel';
import Velocity from './Velocity';

/**
 * The UserStatusModel model module.
 * @module model/UserStatusModel
 * @version v.1
 */
class UserStatusModel {
    /**
     * Constructs a new <code>UserStatusModel</code>.
     * @alias module:model/UserStatusModel
     * @param id {Number} 
     * @param uTC {String} 
     */
    constructor(id, uTC) { 
        
        UserStatusModel.initialize(this, id, uTC);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, uTC) { 
        obj['id'] = id;
        obj['uTC'] = uTC;
    }

    /**
     * Constructs a <code>UserStatusModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserStatusModel} obj Optional instance to populate.
     * @return {module:model/UserStatusModel} The populated <code>UserStatusModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserStatusModel();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('position')) {
                obj['position'] = Position.constructFromObject(data['position']);
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('uTC')) {
                obj['uTC'] = ApiClient.convertToType(data['uTC'], 'String');
            }
            if (data.hasOwnProperty('variables')) {
                obj['variables'] = ApiClient.convertToType(data['variables'], [VariableStatusModel]);
            }
            if (data.hasOwnProperty('velocity')) {
                obj['velocity'] = Velocity.constructFromObject(data['velocity']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserStatusModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserStatusModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UserStatusModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `position`
        if (data['position']) { // data not null
          Position.validateJSON(data['position']);
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }
        // ensure the json data is a string
        if (data['uTC'] && !(typeof data['uTC'] === 'string' || data['uTC'] instanceof String)) {
            throw new Error("Expected the field `uTC` to be a primitive type in the JSON string but got " + data['uTC']);
        }
        if (data['variables']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['variables'])) {
                throw new Error("Expected the field `variables` to be an array in the JSON data but got " + data['variables']);
            }
            // validate the optional field `variables` (array)
            for (const item of data['variables']) {
                VariableStatusModel.validateJSON(item);
            };
        }
        // validate the optional field `velocity`
        if (data['velocity']) { // data not null
          Velocity.validateJSON(data['velocity']);
        }

        return true;
    }


}

UserStatusModel.RequiredProperties = ["id", "uTC"];

/**
 * @member {Number} id
 */
UserStatusModel.prototype['id'] = undefined;

/**
 * @member {module:model/Position} position
 */
UserStatusModel.prototype['position'] = undefined;

/**
 * @member {String} username
 */
UserStatusModel.prototype['username'] = undefined;

/**
 * @member {String} uTC
 */
UserStatusModel.prototype['uTC'] = undefined;

/**
 * @member {Array.<module:model/VariableStatusModel>} variables
 */
UserStatusModel.prototype['variables'] = undefined;

/**
 * @member {module:model/Velocity} velocity
 */
UserStatusModel.prototype['velocity'] = undefined;






export default UserStatusModel;

