/**
 * GpsGate API Documentation
 * GpsGate API service
 *
 * The version of the OpenAPI document: v.1
 * Contact: support@gpsgate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GateUserNetStatus from './GateUserNetStatus';

/**
 * The ViewModel model module.
 * @module model/ViewModel
 * @version v.1
 */
class ViewModel {
    /**
     * Constructs a new <code>ViewModel</code>.
     * @alias module:model/ViewModel
     * @param applicationID {Number} 
     * @param id {Number} 
     * @param matchAllTags {Boolean} 
     * @param statusFilter {module:model/GateUserNetStatus} 
     */
    constructor(applicationID, id, matchAllTags, statusFilter) { 
        
        ViewModel.initialize(this, applicationID, id, matchAllTags, statusFilter);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, applicationID, id, matchAllTags, statusFilter) { 
        obj['applicationID'] = applicationID;
        obj['id'] = id;
        obj['matchAllTags'] = matchAllTags;
        obj['statusFilter'] = statusFilter;
    }

    /**
     * Constructs a <code>ViewModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ViewModel} obj Optional instance to populate.
     * @return {module:model/ViewModel} The populated <code>ViewModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ViewModel();

            if (data.hasOwnProperty('applicationID')) {
                obj['applicationID'] = ApiClient.convertToType(data['applicationID'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('matchAllTags')) {
                obj['matchAllTags'] = ApiClient.convertToType(data['matchAllTags'], 'Boolean');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('statusFilter')) {
                obj['statusFilter'] = GateUserNetStatus.constructFromObject(data['statusFilter']);
            }
            if (data.hasOwnProperty('tagIDs')) {
                obj['tagIDs'] = ApiClient.convertToType(data['tagIDs'], ['Number']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ViewModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ViewModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ViewModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['tagIDs'])) {
            throw new Error("Expected the field `tagIDs` to be an array in the JSON data but got " + data['tagIDs']);
        }

        return true;
    }


}

ViewModel.RequiredProperties = ["applicationID", "id", "matchAllTags", "statusFilter"];

/**
 * @member {Number} applicationID
 */
ViewModel.prototype['applicationID'] = undefined;

/**
 * @member {String} description
 */
ViewModel.prototype['description'] = undefined;

/**
 * @member {Number} id
 */
ViewModel.prototype['id'] = undefined;

/**
 * @member {Boolean} matchAllTags
 */
ViewModel.prototype['matchAllTags'] = undefined;

/**
 * @member {String} name
 */
ViewModel.prototype['name'] = undefined;

/**
 * @member {module:model/GateUserNetStatus} statusFilter
 */
ViewModel.prototype['statusFilter'] = undefined;

/**
 * @member {Array.<Number>} tagIDs
 */
ViewModel.prototype['tagIDs'] = undefined;






export default ViewModel;

