using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FMS.Application.Helpers
{
    public   enum PtsErrorCode
    {
        NotFound = 1,
        InvalidJsonRequest = 2,
        NoData = 3,
        NoDataForResponse = 4,
        JsonRequestTooLong = 5,
        NoPermissions = 6,
        NoSdFound = 7,
        PowerDownDetected = 8,
        SdNotMounted = 9,
        FileUploadProcessRunning = 10,
        SdError = 11,
        NoCalibrationChartFound = 12,
        CouldNotCheckFile = 13,
        CouldNotDeleteFile = 14,
        IncorrectPumpsConfiguration = 15,
        IncorrectProbesConfiguration = 16,
        CouldNotGetDateTime = 17,
        CouldNotGetPumpNumber = 18,
        CouldNotGetPumpTransactionNumber = 19,
        PumpNumberOutOfRange = 20,
        PumpTransactionNumberOutOfRange = 21,
        PumpTransactionNotFound = 22,
        TankNumberOutOfRange = 23,
        CouldNotGetTankNumber = 24,
        CouldNotGetTransactionNumber = 25,
        TransactionNumberOutOfRange = 26,
        TransactionNumberNotMatch = 27,
        TransactionNumberAlreadyExists = 28,
        CouldNotGetNozzleNumber = 29,
        CouldNotGetFuelGradeId = 30,
        CouldNotGetNozzleNumberFuelGradeId = 31,
        CouldNotGetNozzleNumberFromGradeId = 32,
        NozzleNumberOutOfRange = 33,
        CouldNotGetType = 34,
        CouldNotGetName = 35,
        TypeOutOfRange = 36,
        CouldNotGetDoseValue = 37,
        CouldNotGetPriceValue = 38,
        DuplicatedAuthorizationRequest = 39,
        PumpBusyByOtherUser = 40,
        PumpBusyWithOtherRequest = 41,
        PumpBusyWithFilling = 42,
        PumpNotInFillingProcess = 43,
        CouldNotGetStateValue = 44,
        StateValueOutOfRange = 45,
        UserNotMatch = 46,
        DateOutOfRange = 47,
        TimeOutOfRange = 48,
        CouldNotGetHeight = 49,
        CouldNotGetProbeNumber = 50,
        ProbeNumberOutOfRange = 51,
        PumpIsNotConfigured = 52,
        RestoreConfigurationFailed = 53,
        ConfigurationFileNotFound = 54,
        CalibrationChartNotConfigured = 55,
        TankNotConfigured = 56,
        PumpGradeNotCorrespondToTank = 57,
        IncorrectTanksConfiguration = 58,
        IncorrectPriceBoardsConfiguration = 59,
        IncorrectReadersConfiguration = 60,
        CouldNotGetTag = 61,
        CouldNotGetReaderNumber = 62,
        ReaderNumberOutOfRange = 63,
        ReaderNotConfigured = 64,
        TankProductHeightIsCriticalLow = 65,
        CouldNotGetPriceBoardNumber = 66,
        PriceBoardNumberOutOfRange = 67,
        PriceBoardNotConfigured = 68,
        PumpStatusNotEndOfTransaction = 69,
        TagIsNotValid = 70,
        DateTimeIncorrectFormat = 71,
        NoFreeUsersToAdd = 72,
        UserLoginUsed = 73,
        UserIdOutOfRange = 74,
        CannotDeleteLastUser = 75,
        TagAlreadyExists = 76,
        TagNotExists = 77,
        RepeatedAuthorizePumpPriceDifferent = 78,
        CannotUseDataUploadWebsocketsSameTime = 79,
        NoUserWithConfigurationPermissionConfigured = 80
    }
}
