<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-FMS.PTS.WindowsService-07e3bc7d-55f6-45e7-b19d-7ee6c11c74b2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Consumers\**" />
    <Content Remove="Consumers\**" />
    <EmbeddedResource Remove="Consumers\**" />
    <None Remove="Consumers\**" />
  </ItemGroup>

  <!-- Ensure appsettings files are copied to output -->
  <ItemGroup>
    <Content Update="appsettings*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="automapper" Version="13.0.1" />
    <PackageReference Include="MediatR" Version="12.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.StackExchangeRedis" Version="8.0.4" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="9.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Scrutor" Version="6.0.1" />
    <PackageReference Include="Serilog" Version="4.1.0" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="8.0.4" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.24" />
    <PackageReference Include="WatsonWebsocket" Version="4.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FMS.Application\FMS.Application.csproj" />
    <ProjectReference Include="..\FMS.Domain\FMS.Domain.csproj" />
    <ProjectReference Include="..\FMS.Infrastructure\FMS.Infrastructure.csproj" />
    <ProjectReference Include="..\FMS.BackgroundServices\FMS.BackgroundServices.csproj" />
    <ProjectReference Include="..\FMS.Devices.Fueling\FMS.Devices.Fueling.csproj" />
  </ItemGroup>
</Project>
