// <auto-generated />
using System;
using FMS.Sales.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FMS.Sales.Persistence.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    partial class SalesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FMS.Sales.Domain.Entities.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("discount_type");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("discount_value");

                    b.Property<int?>("DurationInCycles")
                        .HasColumnType("integer")
                        .HasColumnName("duration_in_cycles");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int?>("MaxRedemptions")
                        .HasColumnType("integer")
                        .HasColumnName("max_redemptions");

                    b.Property<int>("Redemptions")
                        .HasColumnType("integer")
                        .HasColumnName("redemptions");

                    b.Property<DateTime?>("ValidFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from_utc");

                    b.Property<DateTime?>("ValidUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until_utc");

                    b.HasKey("Id")
                        .HasName("pk_sales_coupon");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_sales_coupon_code");

                    b.ToTable("sales_coupon", (string)null);
                });

            modelBuilder.Entity("FMS.Sales.Domain.Entities.Currency", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DecimalDigits")
                        .HasColumnType("integer")
                        .HasColumnName("decimal_digits");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("symbol");

                    b.HasKey("Code")
                        .HasName("pk_sales_currency");

                    b.ToTable("sales_currency", (string)null);
                });

            modelBuilder.Entity("FMS.Sales.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount_paid");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("discount_amount");

                    b.Property<DateTime>("DueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at_utc");

                    b.Property<string>("ExternalInvoiceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_invoice_id");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("invoice_number");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at_utc");

                    b.Property<DateTime>("PeriodEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_end_utc");

                    b.Property<DateTime>("PeriodStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("tax_amount");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("pk_sales_invoice");

                    b.HasIndex("CurrencyCode")
                        .HasDatabaseName("ix_sales_invoice_currency_code");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_sales_invoice_invoice_number");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("ix_sales_invoice_subscription_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_sales_invoice_tenant_id");

                    b.ToTable("sales_invoice", (string)null);
                });

            modelBuilder.Entity("FMS.Sales.Domain.Entities.InvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<string>("ItemKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("item_key");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint")
                        .HasColumnName("quantity");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_sales_invoice_line");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_sales_invoice_line_invoice_id");

                    b.ToTable("sales_invoice_line", (string)null);
                });

            modelBuilder.Entity("FMS.Sales.Domain.Entities.ManualSale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at_utc");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("approved_by");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("billing_cycle");

                    b.Property<string>("CompanyAddress")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("company_address");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("contact_phone");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("customer_name");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("notes");

                    b.Property<string>("PaymentTerms")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("payment_terms");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<decimal?>("PriceOverride")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("price_override");

                    b.Property<Guid?>("ProvisionedSubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("provisioned_subscription_id");

                    b.Property<Guid?>("ProvisionedTenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("provisioned_tenant_id");

                    b.Property<string>("PurchaseOrderNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("purchase_order_number");

                    b.Property<string>("SalesRep")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("sales_rep");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_sales_manual_sale");

                    b.HasIndex("CurrencyCode")
                        .HasDatabaseName("ix_sales_manual_sale_currency_code");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_sales_manual_sale_plan_id");

                    b.ToTable("sales_manual_sale", (string)null);
                });

            modelBuilder.Entity("FMS.Sales.Domain.Entities.MeteredPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("metric");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_sales_metered_price");

                    b.HasIndex("CurrencyCode")
                        .HasDatabaseName("ix_sales_metered_price_currency_code");

                    b.HasIndex("PlanId", "CurrencyCode", "Metric")
                        .IsUnique()
                        .HasDatabaseName("ix_sales_metered_price_plan_id_currency_code_metric");

                    b.ToTable("sales_metered_price", (string)null);
                });

            modelBuilder.Entity("FMS.Sales.Domain.Entities.OnboardingRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("billing_cycle");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("company_name");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<Guid?>("ProvisionedSubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("provisioned_subscription_id");

                    b.Property<Guid?>("ProvisionedTenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("provisioned_tenant_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("StripeCheckoutSessionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("stripe_checkout_session_id");

                    b.HasKey("Id")
                        .HasName("pk_sales_onboarding_request");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_sales_onboarding_request_email");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_sales_onboarding_request_plan_id");

                    b.ToTable("sales_onboarding_request", (string)null);
                });

            modelBuilder.Entity("FMS.Sales.Domain.Entities.SalesPipelineFollowUp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at_utc");

                    b.Property<Guid?>("ManualSaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("manual_sale_id");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("note");

                    b.Property<Guid?>("OnboardingRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("onboarding_request_id");

                    b.HasKey("Id")
                        .HasName("pk_sales_pipeline_follow_up");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_sales_pipeline_follow_up_created_at_utc");

                    b.HasIndex("ManualSaleId")
                        .HasDatabaseName("ix_sales_pipeline_follow_up_manual_sale_id");

                    b.HasIndex("OnboardingRequestId")
                        .HasDatabaseName("ix_sales_pipeline_follow_up_onboarding_request_id");

                    b.ToTable("sales_pipeline_follow_up", (string)null);
                });

            modelBuilder.Entity("FMS.Sales.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("AttemptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempted_at_utc");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("ExternalPaymentId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_payment_id");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<string>("ManualReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("manual_reference");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("notes");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("provider");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_sales_payment");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_sales_payment_invoice_id");

                    b.ToTable("sales_payment", (string)null);
                });

            modelBuilder.Entity("FMS.Sales.Domain.Entities.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_public");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_sales_plan");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_sales_plan_code");

                    b.ToTable("sales_plan", (string)null);
                });

            modelBuilder.Entity("FMS.Sales.Domain.Entities.PlanFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FeatureKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("feature_key");

                    b.Property<string>("FeatureValue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("feature_value");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.HasKey("Id")
                        .HasName("pk_sales_plan_feature");

                    b.HasIndex("PlanId", "FeatureKey")
                        .IsUnique()
                        .HasDatabaseName("ix_sales_plan_feature_plan_id_feature_key");

                    b.ToTable("sales_plan_feature", (string)null);
                });

            modelBuilder.Entity("FMS.Sales.Domain.Entities.PlanPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("billing_cycle");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.HasKey("Id")
                        .HasName("pk_sales_plan_price");

                    b.HasIndex("CurrencyCode")
                        .HasDatabaseName("ix_sales_plan_price_currency_code");

                    b.HasIndex("PlanId", "CurrencyCode", "BillingCycle")
                        .IsUnique()
                        .HasDatabaseName("ix_sales_plan_price_plan_id_currency_code_billing_cycle");

                    b.ToTable("sales_plan_price", (string)null);
                });

            modelBuilder.Entity("FMS.Sales.Domain.Entities.PlanQuota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("IncludedUnits")
                        .HasColumnType("bigint")
                        .HasColumnName("included_units");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("metric");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.HasKey("Id")
                        .HasName("pk_sales_plan_quota");

                    b.HasIndex("PlanId", "Metric")
                        .IsUnique()
                        .HasDatabaseName("ix_sales_plan_quota_plan_id_metric");

                    b.ToTable("sales_plan_quota", (string)null);
                });

            modelBuilder.Entity("FMS.Sales.Domain.Entities.SalesAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("actor");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity_type");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.HasKey("Id")
                        .HasName("pk_sales_audit_log");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_sales_audit_log_entity_type_entity_id");

                    b.ToTable("sales_audit_log", (string)null);
                });

            modelBuilder.Entity("FMS.Sales.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("billing_cycle");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<Guid?>("CouponId")
                        .HasColumnType("uuid")
                        .HasColumnName("coupon_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<DateTime>("CurrentPeriodEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_end_utc");

                    b.Property<DateTime>("CurrentPeriodStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_start_utc");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<string>("ExternalCustomerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_customer_id");

                    b.Property<string>("ExternalSubscriptionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_subscription_id");

                    b.Property<string>("PaymentProvider")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("payment_provider");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<DateTime>("StartAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("TrialEndAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_end_at_utc");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_sales_subscription");

                    b.HasIndex("CouponId")
                        .HasDatabaseName("ix_sales_subscription_coupon_id");

                    b.HasIndex("CurrencyCode")
                        .HasDatabaseName("ix_sales_subscription_currency_code");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_sales_subscription_plan_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_sales_subscription_tenant_id");

                    b.ToTable("sales_subscription", (string)null);
                });

            modelBuilder.Entity("FMS.Sales.Domain.Entities.SubscriptionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<string>("ItemKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("item_key");

                    b.Property<string>("Metric")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("metric");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_sales_subscription_item");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("ix_sales_subscription_item_subscription_id");

                    b.ToTable("sales_subscription_item", (string)null);
                });

            modelBuilder.Entity("FMS.Sales.Domain.Entities.UsageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("metric");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint")
                        .HasColumnName("quantity");

                    b.Property<DateOnly>("RecordedDate")
                        .HasColumnType("date")
                        .HasColumnName("recorded_date");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_sales_usage_record");

                    b.HasIndex("TenantId", "Metric", "RecordedDate")
                        .IsUnique()
                        .HasDatabaseName("ix_sales_usage_record_tenant_id_metric_recorded_date");

                    b.ToTable("sales_usage_record", (string)null);
                });

            modelBuilder.Entity("FMS.Sales.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("FMS.Sales.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_invoice_sales_currency_currency_code");

                    b.HasOne("FMS.Sales.Domain.Entities.Subscription", "Subscription")
                        .WithMany("Invoices")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_sales_invoice_subscription_subscription_id");

                    b.Navigation("Currency");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("FMS.Sales.Domain.Entities.InvoiceLine", b =>
                {
                    b.HasOne("FMS.Sales.Domain.Entities.Invoice", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_invoice_line_sales_invoice_invoice_id");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("FMS.Sales.Domain.Entities.ManualSale", b =>
                {
                    b.HasOne("FMS.Sales.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_manual_sale_sales_currency_currency_code");

                    b.HasOne("FMS.Sales.Domain.Entities.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_manual_sale_plan_plan_id");

                    b.Navigation("Currency");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("FMS.Sales.Domain.Entities.MeteredPrice", b =>
                {
                    b.HasOne("FMS.Sales.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_metered_price_sales_currency_currency_code");

                    b.HasOne("FMS.Sales.Domain.Entities.Plan", "Plan")
                        .WithMany("MeteredPrices")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_metered_price_plan_plan_id");

                    b.Navigation("Currency");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("FMS.Sales.Domain.Entities.OnboardingRequest", b =>
                {
                    b.HasOne("FMS.Sales.Domain.Entities.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_onboarding_request_plan_plan_id");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("FMS.Sales.Domain.Entities.SalesPipelineFollowUp", b =>
                {
                    b.HasOne("FMS.Sales.Domain.Entities.ManualSale", "ManualSale")
                        .WithMany("FollowUps")
                        .HasForeignKey("ManualSaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_sales_pipeline_follow_up_sales_manual_sale_manual_sale_id");

                    b.HasOne("FMS.Sales.Domain.Entities.OnboardingRequest", "OnboardingRequest")
                        .WithMany("FollowUps")
                        .HasForeignKey("OnboardingRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_sales_pipeline_follow_up_sales_onboarding_request_onboard");

                    b.Navigation("ManualSale");

                    b.Navigation("OnboardingRequest");
                });

            modelBuilder.Entity("FMS.Sales.Domain.Entities.Payment", b =>
                {
                    b.HasOne("FMS.Sales.Domain.Entities.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_payment_sales_invoice_invoice_id");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("FMS.Sales.Domain.Entities.PlanFeature", b =>
                {
                    b.HasOne("FMS.Sales.Domain.Entities.Plan", "Plan")
                        .WithMany("Features")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_plan_feature_sales_plan_plan_id");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("FMS.Sales.Domain.Entities.PlanPrice", b =>
                {
                    b.HasOne("FMS.Sales.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_plan_price_sales_currency_currency_code");

                    b.HasOne("FMS.Sales.Domain.Entities.Plan", "Plan")
                        .WithMany("Prices")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_plan_price_sales_plan_plan_id");

                    b.Navigation("Currency");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("FMS.Sales.Domain.Entities.PlanQuota", b =>
                {
                    b.HasOne("FMS.Sales.Domain.Entities.Plan", "Plan")
                        .WithMany("Quotas")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_plan_quota_sales_plan_plan_id");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("FMS.Sales.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("FMS.Sales.Domain.Entities.Coupon", "Coupon")
                        .WithMany()
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_sales_subscription_sales_coupon_coupon_id");

                    b.HasOne("FMS.Sales.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_subscription_sales_currency_currency_code");

                    b.HasOne("FMS.Sales.Domain.Entities.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_subscription_sales_plan_plan_id");

                    b.Navigation("Coupon");

                    b.Navigation("Currency");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("FMS.Sales.Domain.Entities.SubscriptionItem", b =>
                {
                    b.HasOne("FMS.Sales.Domain.Entities.Subscription", "Subscription")
                        .WithMany("Items")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_subscription_item_sales_subscription_subscription_id");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("FMS.Sales.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("FMS.Sales.Domain.Entities.ManualSale", b =>
                {
                    b.Navigation("FollowUps");
                });

            modelBuilder.Entity("FMS.Sales.Domain.Entities.OnboardingRequest", b =>
                {
                    b.Navigation("FollowUps");
                });

            modelBuilder.Entity("FMS.Sales.Domain.Entities.Plan", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("MeteredPrices");

                    b.Navigation("Prices");

                    b.Navigation("Quotas");
                });

            modelBuilder.Entity("FMS.Sales.Domain.Entities.Subscription", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
