using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using FMS.Application.Common;
using FMS.Application.Features.Notification.DTOs;
using FMS.Application.Features.Notification.Enums;
using FMS.Application.Features.Notification.Services;
using FMS.Application.Infrastructure.Communication.SignalR;
using FMS.Application.Services;
using FMS.Domain.Entities;
using FMS.Persistence.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Moq;
using Xunit;

namespace FMS.Testing.NotificationTests {
    public class NotificationServiceTests {
        private static GpsdataContext CreateInMemoryContext (string dbName) {
            var options = new DbContextOptionsBuilder<GpsdataContext> ()
                .UseInMemoryDatabase (databaseName: dbName)
                .EnableSensitiveDataLogging ()
                .Options;

            var ctx = new GpsdataContext (options);
            ctx.Database.EnsureCreated ();
            return ctx;
        }

        private static void SeedCategory (GpsdataContext ctx, string name, int id) {
            // Id is auto-generated by InMemory provider if not set, but we want deterministic Ids
            ctx.NotificationCategories.Add (new NotificationCategory {
                Id = id,
                    Name = name,
                    DefaultPriority = "Medium",
                    IsActive = true,
                    DisplayOrder = 1,
                    CreatedBy = "test"
            });
            ctx.SaveChanges ();
        }

        private static User SeedUser (GpsdataContext ctx, string id, string email = "user@test.local", string phone = "+15550000001") {
            var user = new User {
            Id = id,
            UserName = id,
            Email = email,
            PhoneNumber = phone,
            EmailConfirmed = true,
            PhoneNumberConfirmed = true
            };
            ctx.Users.Add (user);
            ctx.SaveChanges ();
            return user;
        }

        private static NotificationService CreateService (
            GpsdataContext ctx,
            out Mock<ISignalRNotificationService> signalR,
            out Mock<IEmailService> email,
            out Mock<ISmsService> sms,
            out Mock<ISystemUserService> systemUser,
            out Mock<INotificationRecipientResolver> resolver
        ) {
            var logger = new Mock<ILogger<NotificationService>> ();

            signalR = new Mock<ISignalRNotificationService> ();
            signalR.Setup (s => s.SendUserNotificationAsync (It.IsAny<string> (), It.IsAny<string> (), It.IsAny<string> (), It.IsAny<object> ()))
                .Returns (Task.CompletedTask);

            email = new Mock<IEmailService> ();
            email.Setup (e => e.SendEmailAsync (It.IsAny<string> (), It.IsAny<string> (), It.IsAny<string> (), It.IsAny<bool> (), It.IsAny<CancellationToken> ()))
                .ReturnsAsync (true);

            sms = new Mock<ISmsService> ();
            sms.Setup (s => s.SendSmsAsync (It.IsAny<string> (), It.IsAny<string> (), It.IsAny<CancellationToken> ()))
                .ReturnsAsync (true);

            systemUser = new Mock<ISystemUserService> ();
            systemUser.Setup (s => s.GetSystemUserIdAsync (It.IsAny<CancellationToken> ()))
                .ReturnsAsync (FMSResponse<string>.Success ("system", "ok"));

            resolver = new Mock<INotificationRecipientResolver> ();

            return new NotificationService (
                ctx,
                logger.Object,
                signalR.Object,
                email.Object,
                sms.Object,
                systemUser.Object,
                resolver.Object,
                null // use default InMemoryCategoryMetadataProvider
            );
        }

        [Fact]
        public async Task CreateNotification_CreatesRecipients_And_SendsImmediately () {
            var dbName = nameof (CreateNotification_CreatesRecipients_And_SendsImmediately);
            await using var ctx = CreateInMemoryContext (dbName);

            // Seed categories and user
            SeedCategory (ctx, WellKnownCategories.Generic.ToString (), (int) WellKnownCategories.Generic);
            var user = SeedUser (ctx, "user-1", email: "user1@example.com", phone: "+15550000002");

            // Arrange service and recipient resolver
            var service = CreateService (ctx, out var signalR, out var email, out var sms, out var systemUser, out var resolver);

            resolver.Setup (r => r.ResolveRecipientsAsync (It.IsAny<CreateNotificationRequest> (), It.IsAny<CancellationToken> ()))
                .ReturnsAsync (new List<ResolvedNotificationRecipient> {
                    new () { UserId = user.Id, DeliveryMethods = new List<string> { "system", "email", "sms" } }
                });

            var request = new CreateNotificationRequest {
                Type = NotificationType.Info,
                CategoryId = (int) WellKnownCategories.Generic,
                Priority = NotificationPriority.Medium,
                Title = "Test Title",
                Message = "Test Message",
                TriggerSource = "UnitTest",
                TriggeredBy = user.Id
            };

            // Act
            var result = await service.CreateNotificationAsync (request);

            // Assert
            Assert.True (result.IsSuccess, result.Message);
            var notification = await ctx.Notifications
                .Include (n => n.Recipients)
                .FirstOrDefaultAsync (n => n.Id == result.Data);
            Assert.NotNull (notification);
            Assert.Equal ("Sent", notification!.Status); // should auto-send
            Assert.Equal (3, notification.Recipients.Count);
            Assert.All (notification.Recipients, r => Assert.Equal ("Sent", r.DeliveryStatus));

            // Verify delivery methods were invoked
            signalR.Verify (s => s.SendUserNotificationAsync (user.Id, It.IsAny<string> (), It.IsAny<string> (), It.IsAny<object> ()), Times.Once);
            email.Verify (e => e.SendEmailAsync (user.Email!, It.IsAny<string> (), It.IsAny<string> (), true, It.IsAny<CancellationToken> ()), Times.Once);
            sms.Verify (s => s.SendSmsAsync (user.PhoneNumber!, It.IsAny<string> (), It.IsAny<CancellationToken> ()), Times.Once);
        }

        [Fact]
        public async Task CreateNotification_FallsBackToSystem_When_CategoryMissing () {
            var dbName = nameof (CreateNotification_FallsBackToSystem_When_CategoryMissing);
            await using var ctx = CreateInMemoryContext (dbName);

            // Only seed System category; Generic is missing to trigger fallback
            SeedCategory (ctx, WellKnownCategories.System.ToString (), (int) WellKnownCategories.System);
            var user = SeedUser (ctx, "user-2");

            var service = CreateService (ctx, out var signalR, out var email, out var sms, out var systemUser, out var resolver);
            resolver.Setup (r => r.ResolveRecipientsAsync (It.IsAny<CreateNotificationRequest> (), It.IsAny<CancellationToken> ()))
                .ReturnsAsync (new List<ResolvedNotificationRecipient> {
                    new () { UserId = user.Id, DeliveryMethods = new List<string> { "system" } }
                });

            var request = new CreateNotificationRequest {
                Type = NotificationType.Info,
                    CategoryId = (int) WellKnownCategories.Generic, // missing; should fallback to System
                    Priority = NotificationPriority.Low,
                    Title = "Fallback Title",
                    Message = "Fallback Message",
                    TriggerSource = "UnitTest",
                    TriggeredBy = user.Id
            };

            var result = await service.CreateNotificationAsync (request);
            Assert.True (result.IsSuccess, result.Message);

            var created = await ctx.Notifications.FirstAsync (n => n.Id == result.Data);
            // Category string is the requested category name
            Assert.Equal (WellKnownCategories.Generic.ToString (), created.Category);
            // But FK should point to System category due to fallback
            Assert.Equal ((int) WellKnownCategories.System, created.NotificationCategoryId);
        }

        [Fact]
        public async Task CreateNotification_NoRecipients_StillCompletes_And_MarksSent () {
            var dbName = nameof (CreateNotification_NoRecipients_StillCompletes_And_MarksSent);
            await using var ctx = CreateInMemoryContext (dbName);
            SeedCategory (ctx, WellKnownCategories.Generic.ToString (), (int) WellKnownCategories.Generic);
            var user = SeedUser (ctx, "user-3");

            var service = CreateService (ctx, out var signalR, out var email, out var sms, out var systemUser, out var resolver);
            resolver.Setup (r => r.ResolveRecipientsAsync (It.IsAny<CreateNotificationRequest> (), It.IsAny<CancellationToken> ()))
                .ReturnsAsync (new List<ResolvedNotificationRecipient> ()); // no recipients

            var request = new CreateNotificationRequest {
                Type = NotificationType.Info,
                CategoryId = (int) WellKnownCategories.Generic,
                Priority = NotificationPriority.Medium,
                Title = "No Recipients",
                Message = "Should still mark as sent",
                TriggerSource = "UnitTest",
                TriggeredBy = user.Id
            };

            var result = await service.CreateNotificationAsync (request);
            Assert.True (result.IsSuccess, result.Message);

            var created = await ctx.Notifications.Include (n => n.Recipients).FirstAsync (n => n.Id == result.Data);
            Assert.Equal ("Sent", created.Status);
            Assert.Empty (created.Recipients);

            // No transports should be invoked
            signalR.Verify (s => s.SendUserNotificationAsync (It.IsAny<string> (), It.IsAny<string> (), It.IsAny<string> (), It.IsAny<object> ()), Times.Never);
            email.Verify (e => e.SendEmailAsync (It.IsAny<string> (), It.IsAny<string> (), It.IsAny<string> (), It.IsAny<bool> (), It.IsAny<CancellationToken> ()), Times.Never);
            sms.Verify (s => s.SendSmsAsync (It.IsAny<string> (), It.IsAny<string> (), It.IsAny<CancellationToken> ()), Times.Never);
        }

        [Fact]
        public async Task SendScheduledNotifications_ProcessesDueItems () {
            var dbName = nameof (SendScheduledNotifications_ProcessesDueItems);
            await using var ctx = CreateInMemoryContext (dbName);

            SeedCategory (ctx, WellKnownCategories.Generic.ToString (), (int) WellKnownCategories.Generic);
            var user = SeedUser (ctx, "user-4");

            // Seed a scheduled notification with one recipient
            var notification = new Notification {
                NotificationId = Guid.NewGuid ().ToString (),
                Type = NotificationType.Info.ToString (),
                Category = WellKnownCategories.Generic.ToString (),
                NotificationCategoryId = (int) WellKnownCategories.Generic,
                Priority = NotificationPriority.Low.ToString (),
                Title = "Scheduled",
                Message = "Scheduled message",
                TriggerSource = "UnitTest",
                Status = "Scheduled",
                ScheduledAt = DateTime.UtcNow.AddMinutes (-1)
            };
            ctx.Notifications.Add (notification);
            await ctx.SaveChangesAsync ();

            ctx.NotificationRecipients.Add (new NotificationRecipient {
                NotificationId = notification.Id,
                    UserId = user.Id,
                    DeliveryMethod = "system",
                    RecipientAddress = user.Id
            });
            await ctx.SaveChangesAsync ();

            var service = CreateService (ctx, out var signalR, out var email, out var sms, out var systemUser, out var resolver);

            // Act
            var res = await service.SendScheduledNotificationsAsync ();

            // Assert
            Assert.True (res.IsSuccess, res.Message);
            var updated = await ctx.Notifications.Include (n => n.Recipients).FirstAsync (n => n.Id == notification.Id);
            Assert.Equal ("Sent", updated.Status);
            Assert.All (updated.Recipients, r => Assert.Equal ("Sent", r.DeliveryStatus));
            signalR.Verify (s => s.SendUserNotificationAsync (user.Id, It.IsAny<string> (), It.IsAny<string> (), It.IsAny<object> ()), Times.Once);
        }
    }
}