// Dashboard Data
export const FETCH_ATG_DASHBOARD_START = "FETCH_ATG_DASHBOARD_START";
export const FETCH_ATG_DASHBOARD_SUCCESS = "FETCH_ATG_DASHBOARD_SUCCESS";
export const FETCH_ATG_DASHBOARD_ERROR = "FETCH_ATG_DASHBOARD_ERROR";

// PTS Device Data
export const FETCH_PTS_DEVICE_START = "FETCH_PTS_DEVICE_START";
export const FETCH_PTS_DEVICE_SUCCESS = "FETCH_PTS_DEVICE_SUCCESS";
export const FETCH_PTS_DEVICE_ERROR = "FETCH_PTS_DEVICE_ERROR";

// Fueling Transaction
export const START_FUELING_TRANSACTION = "START_FUELING_TRANSACTION";
export const START_FUELING_TRANSACTION_SUCCESS =
  "START_FUELING_TRANSACTION_SUCCESS";
export const START_FUELING_TRANSACTION_ERROR =
  "START_FUELING_TRANSACTION_ERROR";

export const COMPLETE_FUELING_TRANSACTION = "COMPLETE_FUELING_TRANSACTION";
export const COMPLETE_FUELING_TRANSACTION_SUCCESS =
  "COMPLETE_FUELING_TRANSACTION_SUCCESS";
export const COMPLETE_FUELING_TRANSACTION_ERROR =
  "COMPLETE_FUELING_TRANSACTION_ERROR";
