/**
 * GpsGate API Documentation
 * GpsGate API service
 *
 * The version of the OpenAPI document: v.1
 * Contact: support@gpsgate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import APIModel from './model/APIModel';
import AccumulatorModel from './model/AccumulatorModel';
import AccumulatorTypeModel from './model/AccumulatorTypeModel';
import ApiKey from './model/ApiKey';
import ApplicationCreateModel from './model/ApplicationCreateModel';
import ApplicationModel from './model/ApplicationModel';
import ApplicationTemplateModel from './model/ApplicationTemplateModel';
import ApplicationTrackInfoModel from './model/ApplicationTrackInfoModel';
import Argument from './model/Argument';
import BoundingBox from './model/BoundingBox';
import CircleShape from './model/CircleShape';
import Credentials from './model/Credentials';
import CustomFieldModel from './model/CustomFieldModel';
import CustomFieldsCustomFieldModel from './model/CustomFieldsCustomFieldModel';
import DeviceCreateModel from './model/DeviceCreateModel';
import DeviceMapperModel from './model/DeviceMapperModel';
import DeviceModel from './model/DeviceModel';
import DeviceTypeModel from './model/DeviceTypeModel';
import EventModel from './model/EventModel';
import EventRuleModel from './model/EventRuleModel';
import GateUserNetStatus from './model/GateUserNetStatus';
import GeocodeResult from './model/GeocodeResult';
import GeofenceGroupModel from './model/GeofenceGroupModel';
import GeofenceModel from './model/GeofenceModel';
import JobModel from './model/JobModel';
import Location from './model/Location';
import MSISDN from './model/MSISDN';
import MessageProviderModel from './model/MessageProviderModel';
import MessageProviderTypeModel from './model/MessageProviderTypeModel';
import OneWireBag from './model/OneWireBag';
import PolygonShape from './model/PolygonShape';
import Position from './model/Position';
import Position2D from './model/Position2D';
import ReverseGeocodeResult from './model/ReverseGeocodeResult';
import RoleModel from './model/RoleModel';
import RouteModel from './model/RouteModel';
import RouteShape from './model/RouteShape';
import ShapeType from './model/ShapeType';
import TagModel from './model/TagModel';
import TokenModel from './model/TokenModel';
import TrackInfoModel from './model/TrackInfoModel';
import TrackModel from './model/TrackModel';
import TrackPoint from './model/TrackPoint';
import UserCreateModel from './model/UserCreateModel';
import UserCustomFieldModel from './model/UserCustomFieldModel';
import UserEditModel from './model/UserEditModel';
import UserIconModel from './model/UserIconModel';
import UserModel from './model/UserModel';
import UserStatusModel from './model/UserStatusModel';
import UserTypeModel from './model/UserTypeModel';
import VariableModel from './model/VariableModel';
import VariableStatusModel from './model/VariableStatusModel';
import Velocity from './model/Velocity';
import ViewModel from './model/ViewModel';
import AccumulatorApi from './api/AccumulatorApi';
import ApplicationApi from './api/ApplicationApi';
import DevicesApi from './api/DevicesApi';
import DispatchApi from './api/DispatchApi';
import EventsApi from './api/EventsApi';
import GeocodingApi from './api/GeocodingApi';
import GeofenceGroupsApi from './api/GeofenceGroupsApi';
import GeofenceGroupsGeofenceApi from './api/GeofenceGroupsGeofenceApi';
import GeofencesApi from './api/GeofencesApi';
import MessageProviderTypesApi from './api/MessageProviderTypesApi';
import MessageProvidersApi from './api/MessageProvidersApi';
import RolesApi from './api/RolesApi';
import TagsApi from './api/TagsApi';
import TokensApi from './api/TokensApi';
import TrackInfosApi from './api/TrackInfosApi';
import TracksApi from './api/TracksApi';
import UsersApi from './api/UsersApi';
import VariablesApi from './api/VariablesApi';
import ViewsApi from './api/ViewsApi';


/**
* GpsGate API service.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var GpsGateApiDocumentation = require('index'); // See note below*.
* var xxxSvc = new GpsGateApiDocumentation.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new GpsGateApiDocumentation.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new GpsGateApiDocumentation.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new GpsGateApiDocumentation.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The APIModel model constructor.
     * @property {module:model/APIModel}
     */
    APIModel,

    /**
     * The AccumulatorModel model constructor.
     * @property {module:model/AccumulatorModel}
     */
    AccumulatorModel,

    /**
     * The AccumulatorTypeModel model constructor.
     * @property {module:model/AccumulatorTypeModel}
     */
    AccumulatorTypeModel,

    /**
     * The ApiKey model constructor.
     * @property {module:model/ApiKey}
     */
    ApiKey,

    /**
     * The ApplicationCreateModel model constructor.
     * @property {module:model/ApplicationCreateModel}
     */
    ApplicationCreateModel,

    /**
     * The ApplicationModel model constructor.
     * @property {module:model/ApplicationModel}
     */
    ApplicationModel,

    /**
     * The ApplicationTemplateModel model constructor.
     * @property {module:model/ApplicationTemplateModel}
     */
    ApplicationTemplateModel,

    /**
     * The ApplicationTrackInfoModel model constructor.
     * @property {module:model/ApplicationTrackInfoModel}
     */
    ApplicationTrackInfoModel,

    /**
     * The Argument model constructor.
     * @property {module:model/Argument}
     */
    Argument,

    /**
     * The BoundingBox model constructor.
     * @property {module:model/BoundingBox}
     */
    BoundingBox,

    /**
     * The CircleShape model constructor.
     * @property {module:model/CircleShape}
     */
    CircleShape,

    /**
     * The Credentials model constructor.
     * @property {module:model/Credentials}
     */
    Credentials,

    /**
     * The CustomFieldModel model constructor.
     * @property {module:model/CustomFieldModel}
     */
    CustomFieldModel,

    /**
     * The CustomFieldsCustomFieldModel model constructor.
     * @property {module:model/CustomFieldsCustomFieldModel}
     */
    CustomFieldsCustomFieldModel,

    /**
     * The DeviceCreateModel model constructor.
     * @property {module:model/DeviceCreateModel}
     */
    DeviceCreateModel,

    /**
     * The DeviceMapperModel model constructor.
     * @property {module:model/DeviceMapperModel}
     */
    DeviceMapperModel,

    /**
     * The DeviceModel model constructor.
     * @property {module:model/DeviceModel}
     */
    DeviceModel,

    /**
     * The DeviceTypeModel model constructor.
     * @property {module:model/DeviceTypeModel}
     */
    DeviceTypeModel,

    /**
     * The EventModel model constructor.
     * @property {module:model/EventModel}
     */
    EventModel,

    /**
     * The EventRuleModel model constructor.
     * @property {module:model/EventRuleModel}
     */
    EventRuleModel,

    /**
     * The GateUserNetStatus model constructor.
     * @property {module:model/GateUserNetStatus}
     */
    GateUserNetStatus,

    /**
     * The GeocodeResult model constructor.
     * @property {module:model/GeocodeResult}
     */
    GeocodeResult,

    /**
     * The GeofenceGroupModel model constructor.
     * @property {module:model/GeofenceGroupModel}
     */
    GeofenceGroupModel,

    /**
     * The GeofenceModel model constructor.
     * @property {module:model/GeofenceModel}
     */
    GeofenceModel,

    /**
     * The JobModel model constructor.
     * @property {module:model/JobModel}
     */
    JobModel,

    /**
     * The Location model constructor.
     * @property {module:model/Location}
     */
    Location,

    /**
     * The MSISDN model constructor.
     * @property {module:model/MSISDN}
     */
    MSISDN,

    /**
     * The MessageProviderModel model constructor.
     * @property {module:model/MessageProviderModel}
     */
    MessageProviderModel,

    /**
     * The MessageProviderTypeModel model constructor.
     * @property {module:model/MessageProviderTypeModel}
     */
    MessageProviderTypeModel,

    /**
     * The OneWireBag model constructor.
     * @property {module:model/OneWireBag}
     */
    OneWireBag,

    /**
     * The PolygonShape model constructor.
     * @property {module:model/PolygonShape}
     */
    PolygonShape,

    /**
     * The Position model constructor.
     * @property {module:model/Position}
     */
    Position,

    /**
     * The Position2D model constructor.
     * @property {module:model/Position2D}
     */
    Position2D,

    /**
     * The ReverseGeocodeResult model constructor.
     * @property {module:model/ReverseGeocodeResult}
     */
    ReverseGeocodeResult,

    /**
     * The RoleModel model constructor.
     * @property {module:model/RoleModel}
     */
    RoleModel,

    /**
     * The RouteModel model constructor.
     * @property {module:model/RouteModel}
     */
    RouteModel,

    /**
     * The RouteShape model constructor.
     * @property {module:model/RouteShape}
     */
    RouteShape,

    /**
     * The ShapeType model constructor.
     * @property {module:model/ShapeType}
     */
    ShapeType,

    /**
     * The TagModel model constructor.
     * @property {module:model/TagModel}
     */
    TagModel,

    /**
     * The TokenModel model constructor.
     * @property {module:model/TokenModel}
     */
    TokenModel,

    /**
     * The TrackInfoModel model constructor.
     * @property {module:model/TrackInfoModel}
     */
    TrackInfoModel,

    /**
     * The TrackModel model constructor.
     * @property {module:model/TrackModel}
     */
    TrackModel,

    /**
     * The TrackPoint model constructor.
     * @property {module:model/TrackPoint}
     */
    TrackPoint,

    /**
     * The UserCreateModel model constructor.
     * @property {module:model/UserCreateModel}
     */
    UserCreateModel,

    /**
     * The UserCustomFieldModel model constructor.
     * @property {module:model/UserCustomFieldModel}
     */
    UserCustomFieldModel,

    /**
     * The UserEditModel model constructor.
     * @property {module:model/UserEditModel}
     */
    UserEditModel,

    /**
     * The UserIconModel model constructor.
     * @property {module:model/UserIconModel}
     */
    UserIconModel,

    /**
     * The UserModel model constructor.
     * @property {module:model/UserModel}
     */
    UserModel,

    /**
     * The UserStatusModel model constructor.
     * @property {module:model/UserStatusModel}
     */
    UserStatusModel,

    /**
     * The UserTypeModel model constructor.
     * @property {module:model/UserTypeModel}
     */
    UserTypeModel,

    /**
     * The VariableModel model constructor.
     * @property {module:model/VariableModel}
     */
    VariableModel,

    /**
     * The VariableStatusModel model constructor.
     * @property {module:model/VariableStatusModel}
     */
    VariableStatusModel,

    /**
     * The Velocity model constructor.
     * @property {module:model/Velocity}
     */
    Velocity,

    /**
     * The ViewModel model constructor.
     * @property {module:model/ViewModel}
     */
    ViewModel,

    /**
    * The AccumulatorApi service constructor.
    * @property {module:api/AccumulatorApi}
    */
    AccumulatorApi,

    /**
    * The ApplicationApi service constructor.
    * @property {module:api/ApplicationApi}
    */
    ApplicationApi,

    /**
    * The DevicesApi service constructor.
    * @property {module:api/DevicesApi}
    */
    DevicesApi,

    /**
    * The DispatchApi service constructor.
    * @property {module:api/DispatchApi}
    */
    DispatchApi,

    /**
    * The EventsApi service constructor.
    * @property {module:api/EventsApi}
    */
    EventsApi,

    /**
    * The GeocodingApi service constructor.
    * @property {module:api/GeocodingApi}
    */
    GeocodingApi,

    /**
    * The GeofenceGroupsApi service constructor.
    * @property {module:api/GeofenceGroupsApi}
    */
    GeofenceGroupsApi,

    /**
    * The GeofenceGroupsGeofenceApi service constructor.
    * @property {module:api/GeofenceGroupsGeofenceApi}
    */
    GeofenceGroupsGeofenceApi,

    /**
    * The GeofencesApi service constructor.
    * @property {module:api/GeofencesApi}
    */
    GeofencesApi,

    /**
    * The MessageProviderTypesApi service constructor.
    * @property {module:api/MessageProviderTypesApi}
    */
    MessageProviderTypesApi,

    /**
    * The MessageProvidersApi service constructor.
    * @property {module:api/MessageProvidersApi}
    */
    MessageProvidersApi,

    /**
    * The RolesApi service constructor.
    * @property {module:api/RolesApi}
    */
    RolesApi,

    /**
    * The TagsApi service constructor.
    * @property {module:api/TagsApi}
    */
    TagsApi,

    /**
    * The TokensApi service constructor.
    * @property {module:api/TokensApi}
    */
    TokensApi,

    /**
    * The TrackInfosApi service constructor.
    * @property {module:api/TrackInfosApi}
    */
    TrackInfosApi,

    /**
    * The TracksApi service constructor.
    * @property {module:api/TracksApi}
    */
    TracksApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi,

    /**
    * The VariablesApi service constructor.
    * @property {module:api/VariablesApi}
    */
    VariablesApi,

    /**
    * The ViewsApi service constructor.
    * @property {module:api/ViewsApi}
    */
    ViewsApi
};
