import React ,{useEffect,useCallback,useRef,useState} from "react";
import {useDispatch,useSelector} from "react-redux";
import {fetchEmployees,createEmployee,updateEmployee,deleteEmployee} from "../../actions/employeeActions";
import {fetchVehicleList } from "../../actions/vehicleActions";
import { fetchpermissionbyUserId } from '../../actions/permissionActions';
import { fetchUsers } from '../../actions/userActions';
import {fetchSiteList} from '../../actions/siteActions';
import EmployeevehicleTagbox from "./../../components/employee/employeeVehicleTagBox";

import DataGrid, { Paging,
    HeaderFilter, SearchPanel, Toolbar, Item as TItems,
    Editing, FilterRow, Column, Lookup, Sorting, RequiredRule ,
    Form,Popup ,  Grouping,
    GroupPanel ,Summary ,SortByGroupSummaryInfo ,GroupItem , FilterPanel,
    FilterBuilderPopup
   } from 'devextreme-react/data-grid';

   import Button from 'devextreme-react/button';
   import notify from 'devextreme/ui/notify';  
   import LoadIndicator from 'devextreme-react/load-indicator';

const EmployeePage = () => {


    const dispatch = useDispatch();
    const employees = useSelector(state => state.employee.employees);
    const loading = useSelector(state => state.employee.loading);
    const error = useSelector(state => state.employee.error);
    const vehicles = useSelector(state => state.vehicle.vehicles);
    const permissions = useSelector(state => state.permission.permissions);
    const user = useSelector(state => state.auth.user);
    const sites= useSelector((state) => state.site.sites);
    const gridRef = useRef(null);
    const [saving, setSaving] = useState(false);
    const [selectedVehicles, setSelectedVehicles] = useState([]);

 

    const fetchData = useCallback(async () => {
        try {
             await Promise.all([
                dispatch(fetchEmployees()),
                dispatch(fetchVehicleList()),
                dispatch(fetchUsers()),
                dispatch(fetchSiteList()),
                dispatch(fetchpermissionbyUserId(user.id))

             
            ]);
        } catch (error) {
            console.error(error);
        }
    }
    , [dispatch, user.id]);

    useEffect(() => {
        fetchData();
    }
    , [fetchData]);
   
    const onRowInserted = async (e) => {
        try {
            const newData = { ...e.data, vehicles: e.data.vehicles || [] }; // Ensure vehicles is an array        
            // Remove the ID generated by DataGrid
            delete newData.id;
           console.log('New data:', newData);   
    
            const response = await dispatch(createEmployee(newData));
            
            if (response && response.success) {
                console.log('Employee created:', response);
                await dispatch(fetchEmployees());
              //  dispatch(fetchEmployees());
                e.component.navigateToRow(e.key)
                notify('Employee added successfully', 'success', 3000);

            } else {
                throw new Error('Employee creation failed');

            }
        } catch (error) {
            e.cancel = true;
            console.log('Error:', error);
            const errorMessage = error.response?.message || error.message || 'Error processing operation.';
            notify(errorMessage, 'error', 3000);
        }
    };


    const onRowUpdated = async (e) => {
        try{

            const updatedData = { ...e.data };
        
        // Ensure vehicles are in the correct format
        if (updatedData.vehicles && Array.isArray(updatedData.vehicles)) {
            updatedData.vehicles = updatedData.vehicles.map(v => 
                typeof v === 'object' && v.vehicleId ? v.vehicleId : v
            );
        } else {
            updatedData.vehicles = [];
        }

      var response = await  dispatch(updateEmployee(e.key, e.data));
      if(response && response.success)
      {
        dispatch(fetchEmployees());
        notify('Employee updated successfully','success',3000);
        e.component.navigateToRow(e.key)
      }else{
        e.cancel = true;
        notify(response.message, 'error', 3000);
      
      }
        }
        catch(error){
            e.cancel = true;

            const errorMessage = error.response?.data?.message || 'Error processing operation.';
            notify(errorMessage, 'error', 3000);
        }
    }

    const onRowRemoved = (e) => {
        try{
        dispatch(deleteEmployee(e.key));
        notify('Employee deleted successfully','success',3000);
        }
        catch(error){
            e.cancel = true;
            const errorMessage = error.response?.data?.message || 'Error processing operation.';
            notify(errorMessage, 'error', 3000);
        }
    }


    const calculateFilterExpression = (filterValue, selectedFilterOperation, target) => {
        if (target === 'search' && typeof (filterValue) === 'string') {
            return [this.dataField, 'contains', filterValue];
        }
        return function (data) {
            console.log('Filter value:', filterValue);
            return (data.vehicles || []).indexOf(filterValue) !== -1;
        }
    };
    
    
    const vehicleTemplate = (container, options) => {
        const noBreakSpace = '\u00A0';
        const text = (options.value || []).map(vehicleId => {
            const vehicle = vehicles.find(v => v.vehicleId === vehicleId);
            return vehicle ? vehicle.hyoungNo : vehicleId;
        }).join(', ');
        container.textContent = text || noBreakSpace;
        container.title = text;
    };

    const addRow = () => {
        gridRef.current.instance.addRow();
   };
   const refresh = useCallback(() => {
    gridRef.current?.instance.refresh();
}, []);

const canEdit = permissions.includes('_editEmployee');
const canDelete = permissions.includes('_deleteEmployee');
const canCreate = permissions.includes('_createEmployee');

const handleTagBoxValueChanged = (newValue) => {
    setSelectedVehicles(newValue);
};

if (loading || saving) {
    return (
      <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh' }}>
        <LoadIndicator width={'24px'} height={'24px'} visible={true} />
      </div>
    );
}

return (
<div>
<h2 className={'content-block'}>Employees</h2>

<div className={'content-block'}>
                <DataGrid
                 ref={gridRef}
                 dataSource={employees}
                    showBorders={true}
                    keyExpr={'id'}
                    allowColumnReordering={true}
                    allowColumnResizing={true}
                    columnAutoWidth={true}
                    rowAlernationEnable={true}
                    repaintChangesOnly={true}
                    onRowInserted={onRowInserted}
                    onRowUpdated={onRowUpdated}
                    onRowRemoved={onRowRemoved}

                 >
                    <Paging enabled={true} defaultPageSize={30} />
                    <FilterRow visible={true} />
                    <HeaderFilter visible={true} />  
                    <SearchPanel visible placeholder='Data Search' />
                    <Sorting mode="multiple" />
                    <Editing
                        mode="row"
                        allowUpdating={canEdit}
                        allowAdding={canCreate}
                        allowDeleting={canDelete}
                        selectTextOnEditStart={true}
                        startEditAction="dblClick"
                        newRowPosition={'first'}

                    ></Editing>
                      <Toolbar>
                        <TItems location='before' locateInMenu='auto'>
                            <Button
                                icon='plus'
                                text='Add Employee'
                                type='default'
                                stylingMode='contained'
                                onClick={addRow}
                                visible ={canCreate}
                            />
                        </TItems>
                        <TItems
                            location='after'
                            locateInMenu='auto'
                            showText='inMenu'
                            widget='dxButton'
                        >
                            <Button
                                icon='refresh'
                                text='Refresh'
                                stylingMode='text'
                                onClick={refresh}
                            />
                        </TItems>

                        <TItems location='after' locateInMenu='auto'>
                            <div className='separator' />
                        </TItems>
                        <TItems name='searchPanel' locateInMenu='auto' />
                    </Toolbar> 
                <Column dataField="id" allowEditing={false} visible={true} defaultSortOrder={"dsc"} />
                <Column dataField="fullName" caption="Full Names" width={200}>
                    <RequiredRule />
                </Column>
                <Column dataField="nationalId" caption="National ID" alignment="left" width={100} >
                    <RequiredRule />
                </Column>
                <Column dataField="employeephoneNumber" caption="Phone No" />
                <Column dataField="employeeWorkNo" caption="Work No" />
                <Column dataField="employeestatus" allowEditing={false} ></Column>
                <Column
                    dataField="vehicles"
                    width={300}
                    caption="Default vehicles"
                    allowSorting={false}
                    editCellRender={(cellInfo) => (
                        <EmployeevehicleTagbox
                            value={cellInfo.value}
                            onValueChanged={(newValue) => {
                                cellInfo.setValue(newValue);
                                handleTagBoxValueChanged(newValue); // Ensure parent state is updated
                            }}
                        />
                    )}
                    cellTemplate={vehicleTemplate}
                    calculateFilterExpression={calculateFilterExpression}
                >
        <lookup dataSource={vehicles} valueExpr="vehicleId" displayExpr="hyoungNo" />  
                </Column>
                <Column dataField="siteId" caption="Site" width={150}>
                    <Lookup dataSource={sites} valueExpr="id" displayExpr="name" />
                    <RequiredRule />
                </Column>
                    </DataGrid>

                    </div>


</div>

)
}
export default EmployeePage;    


