import React ,{useEffect,useCallback,useRef,useState} from "react";
import {useDispatch,useSelector} from "react-redux";
import {fetchEmployees,createEmployee,updateEmployee,deleteEmployee} from "../../redux/actions/employeeActions";
import {fetchVehicleList } from "../../redux/actions/vehicleActions";
import { fetchpermissionbyUserId } from '../../redux/actions/permissionActions';
import { fetchUsers } from '../../redux/actions/userActions';
import {fetchSiteList} from '../../redux/actions/siteActions';
import EmployeevehicleTagbox from "./../../components/employee/employeeVehicleTagBox";
import Switch, { SwitchTypes } from 'devextreme-react/switch';
import { format } from 'date-fns';
import DataGrid, { Paging,
    HeaderFilter, SearchPanel,
    Editing, FilterRow, Column, Lookup,Toolbar, Item as TItems , Sorting, RequiredRule ,ColumnChooser,ColumnChooserSelection,
    Form,Popup ,  Grouping,Position,Export,Selection,
    GroupPanel ,Summary ,SortByGroupSummaryInfo ,GroupItem , FilterPanel,
    FilterBuilderPopup,LoadPanel
   } from 'devextreme-react/data-grid';

   import Button from 'devextreme-react/button';
   import notify from 'devextreme/ui/notify';
   import LoadIndicator from 'devextreme-react/load-indicator';
   import { jsPDF } from 'jspdf';
   import { exportDataGrid } from 'devextreme/pdf_exporter';
   import { Workbook } from 'exceljs';
   import saveAs from 'file-saver';
   import { exportDataGrid as exportDataGridToExcel } from 'devextreme/excel_exporter';

const EmployeePage = () => {


    const dispatch = useDispatch();
    const employees = useSelector(state => state.employee.employees);
    const loading = useSelector(state => state.employee.loading);
    const error = useSelector(state => state.employee.error);
    const vehicles = useSelector(state => state.vehicle.vehicles);
    const permissions = useSelector(state => state.permission.permissions);
    const users = useSelector(state => state.user.users);
    const user = useSelector(state => state.auth.user);
    const sites= useSelector((state) => state.site.sites);
    const gridRef = useRef(null);
    const [saving, setSaving] = useState(false);
    const [selectedVehicles, setSelectedVehicles] = useState([]);
    const exportFormats = ['pdf'];
    const employeestatus = ['Active', 'Terminated'];
    const [includeTerminated, setIncludeTerminated] = useState(true);
    const [switchLabel, setSwitchLabel] = useState('Load active employees only');

    const fetchData = useCallback(async () => {
        try {
             await Promise.all([
                dispatch(fetchEmployees(includeTerminated)),
                dispatch(fetchVehicleList()),
                dispatch(fetchUsers()),
                dispatch(fetchSiteList()),
                dispatch(fetchpermissionbyUserId(user.id))


            ]);
        } catch (error) {
            console.error(error);
        }
    }
    , [dispatch, user.id, includeTerminated]);

    useEffect(() => {
        fetchData();
    }
    , [fetchData]);



    const onRowInserted = async (e) => {
        try {
            const newData = { ...e.data,
                         vehicles: e.data.vehicles || [] ,
                         fullName: e.data.fullName.toUpperCase()

            }; // Ensure vehicles is an array
            // Remove the ID generated by DataGrid
            delete newData.id;
           console.log('New data:', newData);

            const response = await dispatch(createEmployee(newData));

            if (response && response.success) {
                console.log('Employee created:', response);
                await dispatch(fetchEmployees());
              //  dispatch(fetchEmployees());
                e.component.navigateToRow(e.key)
                notify('Employee added successfully', 'success', 3000);

            } else {
                throw new Error('Employee creation failed');

            }
        } catch (error) {
            e.cancel = true;
            console.log('Error:', error);
            const errorMessage = error.response?.message || error.message || 'Error processing operation.';
            notify(errorMessage, 'error', 3000);
        }
    };


    const onRowUpdated = async (e) => {
        try{

            const updatedData = { ...e.data ,
                 fullName: e.data.fullName.toUpperCase()
            };

        // Ensure vehicles are in the correct format
        if (updatedData.vehicles && Array.isArray(updatedData.vehicles)) {
            updatedData.vehicles = updatedData.vehicles.map(v =>
                typeof v === 'object' && v.vehicleId ? v.vehicleId : v
            );
        } else {
            updatedData.vehicles = [];
        }

      var response = await  dispatch(updateEmployee(e.key, e.data));
      if(response && response.success)
      {
        dispatch(fetchEmployees());
        notify('Employee updated successfully','success',3000);
        e.component.navigateToRow(e.key)
      }else{
        e.cancel = true;
        notify(response.message, 'error', 3000);

      }
        }
        catch(error){
            e.cancel = true;

            const errorMessage = error.response?.data?.message || 'Error processing operation.';
            notify(errorMessage, 'error', 3000);
        }
    }

    const onRowRemoved = (e) => {
        try{
        dispatch(deleteEmployee(e.key));
        notify('Employee deleted successfully','success',3000);
        }
        catch(error){
            e.cancel = true;
            const errorMessage = error.response?.data?.message || 'Error processing operation.';
            notify(errorMessage, 'error', 3000);
        }
    }


    const calculateFilterExpression = (filterValue, selectedFilterOperation, target) => {
        if (target === 'search' && typeof (filterValue) === 'string') {
            return [this.dataField, 'contains', filterValue];
        }
        return function (data) {
            console.log('Filter value:', filterValue);
            return (data.vehicles || []).indexOf(filterValue) !== -1;
        }
    };


    const vehicleTemplate = (container, options) => {
        const noBreakSpace = '\u00A0';
        const text = (options.value || []).map(vehicleId => {
            const vehicle = vehicles.find(v => v.vehicleId === vehicleId);
            return vehicle ? vehicle.hyoungNo : vehicleId;
        }).join(', ');
        container.textContent = text || noBreakSpace;
        container.title = text;
    };

    const addRow = () => {
        gridRef.current.instance.addRow();
   };
   const refresh = useCallback(() => {
    gridRef.current?.instance.refresh();
  }, []);

  const handleSwitchChange = useCallback((value) => {
    setIncludeTerminated(value);
    setSwitchLabel(value ? 'Load all employees' : 'Load active employees only');
    fetchData();
    refresh();
  }, [fetchData, refresh]);

const canEdit = permissions.includes('_editEmployee');
const canDelete = permissions.includes('_deleteEmployee');
const canCreate = permissions.includes('_createEmployee');

const handleTagBoxValueChanged = (newValue) => {
    setSelectedVehicles(newValue);
};
const formatDateToLocal = (cellInfo) => {
    if (cellInfo.value) {
      const date = new Date(cellInfo.value);
      return format(date, 'dd/MM/yyyy HH:mm');
    }
    return '';
  };

const onExporting = useCallback((e) => {
    const format = e.format;

    if (format === 'xlsx') {
      try {
        const workbook = new Workbook();
        const worksheet = workbook.addWorksheet('Employees');

        notify('Preparing export...', 'info', 2000);

        exportDataGridToExcel({
          component: e.component,
          worksheet,
          autoFilterEnabled: true,
          customizeCell: ({ gridCell, excelCell }) => {
            if (gridCell.rowType === 'data') {
              excelCell.font = { size: 12 };
            }
            if (gridCell.rowType === 'header') {
              excelCell.font = { bold: true };
            }
          }
        }).then(() => {
          workbook.xlsx.writeBuffer()
            .then((buffer) => {
              saveAs(new Blob([buffer], { type: 'application/octet-stream' }), 'Employees.xlsx');
              notify('Export complete', 'success', 2000);
            })
            .catch(err => {
              console.error("Buffer creation error:", err);
              notify('Export failed', 'error', 2000);
            });
        }).catch(err => {
          console.error("exportDataGrid error:", err);
          notify('Export failed', 'error', 2000);
        });
      } catch (error) {
        console.error("General export error:", error);
        notify('Export failed', 'error', 2000);
      }
    } else if (format === 'pdf') {
      const doc = new jsPDF();

      exportDataGrid({
        jsPDFDocument: doc,
        component: e.component,
        indent: 5,
      }).then(() => {
        doc.save('Employees.pdf');
        notify('Export complete', 'success', 2000);
      }).catch(err => {
        console.error("PDF export error:", err);
        notify('Export failed', 'error', 2000);
      });
    }

    e.cancel = true;
  }, []);

if (loading || saving) {
    return (
      <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh' }}>
        <LoadIndicator width={'24px'} height={'24px'} visible={true} />
      </div>
    );
}

return (
<div>
<h2 className={'content-block'}>Employees</h2>

<div className={'content-block'}>


                <DataGrid
                 ref={gridRef}
                 dataSource={employees}
                    showBorders={true}
                    keyExpr={'id'}
                    allowColumnReordering={true}
                    allowColumnResizing={true}
                    columnAutoWidth={true}
                    rowAlernationEnable={true}
                    repaintChangesOnly={true}
                    onRowInserted={onRowInserted}
                    onRowUpdated={onRowUpdated}
                    onRowRemoved={onRowRemoved}
                    onExporting={onExporting}
                 >
                    <ColumnChooser enabled={true} mode="select"  height={200} >
                    <Position
                     my="right top"
                     at="right top"
                    />
                     </ColumnChooser>
                    <LoadPanel enabled={true} />
                    <Export enabled={true} allowExportSelectedData={true} formats ={exportFormats} />
                    <Paging enabled={true} defaultPageSize={20} />
                    <FilterRow visible={true} />
                    <HeaderFilter visible={true} />
                    <Sorting mode="multiple" />
                    <Selection mode="multiple" />

                    <Editing
                        mode="row"
                        allowUpdating={canEdit}
                        allowAdding={canCreate}
                        allowDeleting={canDelete}
                        selectTextOnEditStart={true}
                        startEditAction="dblClick"
                        newRowPosition={'first'}

                    ></Editing>

                    <Toolbar>
                        <TItems location='before' locateInMenu='auto'>
                            <Button
                                icon='plus'
                                text='Add Employee'
                                type='default'
                                stylingMode='contained'
                                onClick={addRow}
                                visible ={canCreate}
                            />
                        </TItems>
                        <TItems location='after' locateInMenu='auto'>
                        <span>{switchLabel}</span>
                         </TItems>
                        <TItems location='after' locateInMenu='auto'>

                            <Switch defaultValue={includeTerminated}
                             value={includeTerminated}
                              onValueChanged={(e) => handleSwitchChange(e.value)} />

                            </TItems>

                        <TItems name="exportButton" locateInMenu={'auto'} />

                        <TItems name="columnChooserButton" />

                          <TItems
                            location='after'
                            showText='inMenu'
                            widget='dxButton'
                        >
                            <Button
                                icon='refresh'
                                text='Refresh'
                                stylingMode='text'
                                onClick={refresh}
                            />
                        </TItems>

                    </Toolbar>

                <Column dataField="id" allowEditing={false} visible={false} defaultSortOrder={"dsc"} />
                <Column dataField="fullName" caption="Full Names" minWidth={200} allowHiding={false}
                calculateCellValue={(data) => data.fullName ? data.fullName.toUpperCase() : ''}
                >
                    <RequiredRule />
                </Column>

                <Column dataField="employeephoneNumber" caption="Phone No"  minWidth={150} hidingPriority={3}/>
                <Column dataField="employeeWorkNo" caption="Work No" minWidth={150} hidingPriority={3}/>
                <Column dataField="employeestatus" caption="Employee Status" minWidth={150} hidingPriority={3}>  <Lookup dataSource={employeestatus} /></Column>
                <Column
                    dataField="vehicles"
                    minWidth={300}
                    hidingPriority={4}
                    caption="Default vehicles"
                    allowSorting={false}
                    allowHiding={false}
                    allowFiltering={false}
                    editCellRender={(cellInfo) => (
                        <EmployeevehicleTagbox
                            value={cellInfo.value}
                            onValueChanged={(newValue) => {
                                cellInfo.setValue(newValue);
                                handleTagBoxValueChanged(newValue); // Ensure parent state is updated
                            }}
                        />
                    )}
                    cellTemplate={vehicleTemplate}
                    calculateFilterExpression={calculateFilterExpression}
                >
                    <lookup dataSource={vehicles} valueExpr="vehicleId" displayExpr="hyoungNo" />
                </Column>
                <Column dataField="siteId" caption="Site" width={150} allowHiding={false} minWidth={150} hidingPriority={5}>
                    <Lookup dataSource={sites} valueExpr="id" displayExpr="name" />
                    <RequiredRule />
                </Column>
                <Column
                     minWidth={100}
                     hidingPriority={1}
                    dataField={'dateCreated'}
                    caption={'Created On'}
                    dataType={'datetime'}
                    visible={false}
                    allowEditing={false}
                    cellRender={formatDateToLocal}
                />
                <Column
                    dataField={'dateModified'}
                    caption={'Updated On'}
                    dataType={'datetime'}
                    visible={false}
                    allowEditing={false}
                    hidingPriority={1}
                    cellRender={formatDateToLocal}
                />
                  <Column dataField={'createdBy'} caption={'Created By'} visible={false} allowEditing={false} hidingPriority={1} >
                    <lookup
                    dataSource = {users}
                    valueExpr="id"
                    displayExpr="userName"

                    /></Column>
                <Column dataField={'modifiedBy'} caption={'Updated By'} visible={false} allowEditing={false} hidingPriority={1}>
                    <lookup
                    dataSource = {users}
                    valueExpr="id"
                    displayExpr="userName"
                    /></Column>
            </DataGrid>

        </div>


</div>

)
}
export default EmployeePage;


