
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const FETCH_PERMISSIONS_SUCCESS = 'FETCH_PERMISSIONS_SUCCESS';
export const FETCH_PERMISSIONS_FAILURE = 'FETCH_PERMISSIONS_FAILURE';

export const FETCH_ROLE_DETAILS_SUCCESS = 'FETCH_ROLE_DETAILS_SUCCESS';
export const FETCH_ROLE_DETAILS_FAILURE = 'FETCH_ROLE_DETAILS_FAILURE';
export const ASSIGN_PERMISSIONS_SUCCESS = 'ASSIGN_PERMISSIONS_SUCCESS';
export const ASSIGN_PERMISSIONS_FAILURE = 'ASSIGN_PERMISSIONS_FAILURE';
export const SET_ROLE_PERMISSIONS = 'SET_ROLE_PERMISSIONS';
export const SET_USERS = 'SET_USERS';
export const CLEAR_PERMISSIONS = 'CLEAR_PERMISSIONS';
export const CLEAR_USERS = 'CLEAR_USERS';

export const UPDATE_ROLE_SUCCESS = 'UPDATE_ROLE_SUCCESS';
export const UPDATE_ROLE_FAILURE = 'UPDATE_ROLE_FAILURE';
export const UPDATE_ROLE_USERS_SUCCESS = 'UPDATE_ROLE_USERS_SUCCESS';
export const UPDATE_ROLE_USERS_FAILURE = 'UPDATE_ROLE_USERS_FAILURE';

export const FETCH_NAVIGATION_ITEMS_SUCCESS = 'FETCH_NAVIGATION_ITEMS_SUCCESS';
export const FETCH_NAVIGATION_ITEMS_FAILURE = 'FETCH_NAVIGATION_ITEMS_FAILURE';
export const CREATE_NAVIGATION_ITEM_SUCCESS = 'CREATE_NAVIGATION_ITEM_SUCCESS';
export const CREATE_NAVIGATION_ITEM_FAILURE = 'CREATE_NAVIGATION_ITEM_FAILURE';
export const UPDATE_NAVIGATION_ITEM_SUCCESS = 'UPDATE_NAVIGATION_ITEM_SUCCESS';
export const UPDATE_NAVIGATION_ITEM_FAILURE = 'UPDATE_NAVIGATION_ITEM_FAILURE';
export const DELETE_NAVIGATION_ITEM_SUCCESS = 'DELETE_NAVIGATION_ITEM_SUCCESS';
export const DELETE_NAVIGATION_ITEM_FAILURE = 'DELETE_NAVIGATION_ITEM_FAILURE';
export const ASSIGN_ROLES_TO_NAVIGATION_ITEM_SUCCESS = 'ASSIGN_ROLES_TO_NAVIGATION_ITEM_SUCCESS';
export const ASSIGN_ROLES_TO_NAVIGATION_ITEM_FAILURE = 'ASSIGN_ROLES_TO_NAVIGATION_ITEM_FAILURE';
