export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";
export const FETCH_PERMISSIONS_SUCCESS = "FETCH_PERMISSIONS_SUCCESS";
export const FETCH_PERMISSIONS_FAILURE = "FETCH_PERMISSIONS_FAILURE";

export const FETCH_ROLE_DETAILS_SUCCESS = "FETCH_ROLE_DETAILS_SUCCESS";
export const FETCH_ROLE_DETAILS_FAILURE = "FETCH_ROLE_DETAILS_FAILURE";
export const ASSIGN_PERMISSIONS_SUCCESS = "ASSIGN_PERMISSIONS_SUCCESS";
export const ASSIGN_PERMISSIONS_FAILURE = "ASSIGN_PERMISSIONS_FAILURE";
export const SET_ROLE_PERMISSIONS = "SET_ROLE_PERMISSIONS";
export const SET_USERS = "SET_USERS";
export const CLEAR_PERMISSIONS = "CLEAR_PERMISSIONS";
export const CLEAR_USERS = "CLEAR_USERS";

export const UPDATE_ROLE_SUCCESS = "UPDATE_ROLE_SUCCESS";
export const UPDATE_ROLE_FAILURE = "UPDATE_ROLE_FAILURE";
export const UPDATE_ROLE_USERS_SUCCESS = "UPDATE_ROLE_USERS_SUCCESS";
export const UPDATE_ROLE_USERS_FAILURE = "UPDATE_ROLE_USERS_FAILURE";

export const FETCH_NAVIGATION_ITEMS_SUCCESS = "FETCH_NAVIGATION_ITEMS_SUCCESS";
export const FETCH_NAVIGATION_ITEMS_FAILURE = "FETCH_NAVIGATION_ITEMS_FAILURE";
export const CREATE_NAVIGATION_ITEM_SUCCESS = "CREATE_NAVIGATION_ITEM_SUCCESS";
export const CREATE_NAVIGATION_ITEM_FAILURE = "CREATE_NAVIGATION_ITEM_FAILURE";
export const UPDATE_NAVIGATION_ITEM_SUCCESS = "UPDATE_NAVIGATION_ITEM_SUCCESS";
export const UPDATE_NAVIGATION_ITEM_FAILURE = "UPDATE_NAVIGATION_ITEM_FAILURE";
export const DELETE_NAVIGATION_ITEM_SUCCESS = "DELETE_NAVIGATION_ITEM_SUCCESS";
export const DELETE_NAVIGATION_ITEM_FAILURE = "DELETE_NAVIGATION_ITEM_FAILURE";
export const ASSIGN_ROLES_TO_NAVIGATION_ITEM_SUCCESS =
  "ASSIGN_ROLES_TO_NAVIGATION_ITEM_SUCCESS";
export const ASSIGN_ROLES_TO_NAVIGATION_ITEM_FAILURE =
  "ASSIGN_ROLES_TO_NAVIGATION_ITEM_FAILURE";

// Device Connection Types
export const FETCH_DEVICE_SUMMARY = "FETCH_DEVICE_SUMMARY";
export const FETCH_DEVICE_SUMMARY_SUCCESS = "FETCH_DEVICE_SUMMARY_SUCCESS";
export const FETCH_DEVICE_SUMMARY_FAILURE = "FETCH_DEVICE_SUMMARY_FAILURE";
export const FETCH_PTS_DEVICE_LIST_SUCCESS = "FETCH_PTS_DEVICE_LIST_SUCCESS";
export const FETCH_PTS_DEVICE_LIST_FAILURE = "FETCH_PTS_DEVICE_LIST_FAILURE";
export const FETCH_ONLINE_DEVICES_SUCCESS = "FETCH_ONLINE_DEVICES_SUCCESS";
export const FETCH_ONLINE_DEVICES_FAILURE = "FETCH_ONLINE_DEVICES_FAILURE";
export const RECEIVE_DEVICE_STATUS = "RECEIVE_DEVICE_STATUS";
export const FETCH_DASHBOARD_METRICS_SUCCESS =
  "FETCH_DASHBOARD_METRICS_SUCCESS";
export const FETCH_DASHBOARD_METRICS_FAILURE =
  "FETCH_DASHBOARD_METRICS_FAILURE";
export const RECEIVE_UPLOAD_STATUS_UPDATE = "RECEIVE_UPLOAD_STATUS_UPDATE";

export const FETCH_PTS_DEVICE_LIST = "FETCH_PTS_DEVICE_LIST";

//SignalR Events for Pump from UploadStatus
export const NOZZLE_STATE_CHANGE = "NOZZLE_STATE_CHANGE";
export const UPLOADSTATUS_TAG_READ = "UPLOADSTATUS_TAG_READ";
export const FILLING_STATUS_UPDATE = "FILLING_STATUS_UPDATE";
export const PUMP_TRANSACTION_COMPLETED = "PUMP_TRANSACTION_COMPLETED";
export const PUMP_OFFLINE = "PUMP_OFFLINE";
export const PROBE_STATUS_UPDATE = "PROBE_STATUS_UPDATE";
export const READER_STATUS_UPDATE = "READER_STATUS_UPDATE";

export const SET_LOADING = "SET_LOADING";

// In your types.js file
export const UPDATE_PUMP_STATUS = "UPDATE_PUMP_STATUS";
export const PROCESS_PUMP_STATE_FROM_UPLOADSTATUS =
  "PROCESS_PUMP_STATE_FROM_UPLOADSTATUS";

export const CLEAR_PTS_DEVICE_LIST = "CLEAR_PTS_DEVICE_LIST";
export const CLEAR_DEVICE_CONNECTIONS = "CLEAR_DEVICE_CONNECTIONS";

export const FUELING_EVENT_TYPES = {
  ADD: "FUELING_EVENT_ADD",
  CLEAR: "FUELING_EVENT_CLEAR",
};

// Active Alarm Types
export const ACTIVE_ALARM_TYPES = {
  // Loading states
  SET_LOADING: 'ACTIVE_ALARM_SET_LOADING',
  SET_ERROR: 'ACTIVE_ALARM_SET_ERROR',
  CLEAR_ERROR: 'ACTIVE_ALARM_CLEAR_ERROR',

  // Alarm CRUD operations
  FETCH_ALARMS_REQUEST: 'ACTIVE_ALARM_FETCH_ALARMS_REQUEST',
  FETCH_ALARMS_SUCCESS: 'ACTIVE_ALARM_FETCH_ALARMS_SUCCESS',
  FETCH_ALARMS_FAILURE: 'ACTIVE_ALARM_FETCH_ALARMS_FAILURE',

  FETCH_ALARM_BY_ID_REQUEST: 'ACTIVE_ALARM_FETCH_BY_ID_REQUEST',
  FETCH_ALARM_BY_ID_SUCCESS: 'ACTIVE_ALARM_FETCH_BY_ID_SUCCESS',
  FETCH_ALARM_BY_ID_FAILURE: 'ACTIVE_ALARM_FETCH_BY_ID_FAILURE',

  CREATE_ALARM_REQUEST: 'ACTIVE_ALARM_CREATE_REQUEST',
  CREATE_ALARM_SUCCESS: 'ACTIVE_ALARM_CREATE_SUCCESS',
  CREATE_ALARM_FAILURE: 'ACTIVE_ALARM_CREATE_FAILURE',

  // Alarm state actions
  ACKNOWLEDGE_ALARM_REQUEST: 'ACTIVE_ALARM_ACKNOWLEDGE_REQUEST',
  ACKNOWLEDGE_ALARM_SUCCESS: 'ACTIVE_ALARM_ACKNOWLEDGE_SUCCESS',
  ACKNOWLEDGE_ALARM_FAILURE: 'ACTIVE_ALARM_ACKNOWLEDGE_FAILURE',

  RESOLVE_ALARM_REQUEST: 'ACTIVE_ALARM_RESOLVE_REQUEST',
  RESOLVE_ALARM_SUCCESS: 'ACTIVE_ALARM_RESOLVE_SUCCESS',
  RESOLVE_ALARM_FAILURE: 'ACTIVE_ALARM_RESOLVE_FAILURE',

  SUPPRESS_ALARM_REQUEST: 'ACTIVE_ALARM_SUPPRESS_REQUEST',
  SUPPRESS_ALARM_SUCCESS: 'ACTIVE_ALARM_SUPPRESS_SUCCESS',
  SUPPRESS_ALARM_FAILURE: 'ACTIVE_ALARM_SUPPRESS_FAILURE',

  ESCALATE_ALARM_REQUEST: 'ACTIVE_ALARM_ESCALATE_REQUEST',
  ESCALATE_ALARM_SUCCESS: 'ACTIVE_ALARM_ESCALATE_SUCCESS',
  ESCALATE_ALARM_FAILURE: 'ACTIVE_ALARM_ESCALATE_FAILURE',

  // Bulk operations
  BULK_ACKNOWLEDGE_REQUEST: 'ACTIVE_ALARM_BULK_ACKNOWLEDGE_REQUEST',
  BULK_ACKNOWLEDGE_SUCCESS: 'ACTIVE_ALARM_BULK_ACKNOWLEDGE_SUCCESS',
  BULK_ACKNOWLEDGE_FAILURE: 'ACTIVE_ALARM_BULK_ACKNOWLEDGE_FAILURE',

  // Statistics
  FETCH_STATISTICS_REQUEST: 'ACTIVE_ALARM_FETCH_STATISTICS_REQUEST',
  FETCH_STATISTICS_SUCCESS: 'ACTIVE_ALARM_FETCH_STATISTICS_SUCCESS',
  FETCH_STATISTICS_FAILURE: 'ACTIVE_ALARM_FETCH_STATISTICS_FAILURE',

  // Auto-processing admin operations
  PROCESS_AUTO_RESOLVE_REQUEST: 'ACTIVE_ALARM_PROCESS_AUTO_RESOLVE_REQUEST',
  PROCESS_AUTO_RESOLVE_SUCCESS: 'ACTIVE_ALARM_PROCESS_AUTO_RESOLVE_SUCCESS',
  PROCESS_AUTO_RESOLVE_FAILURE: 'ACTIVE_ALARM_PROCESS_AUTO_RESOLVE_FAILURE',

  PROCESS_ESCALATION_REQUEST: 'ACTIVE_ALARM_PROCESS_ESCALATION_REQUEST',
  PROCESS_ESCALATION_SUCCESS: 'ACTIVE_ALARM_PROCESS_ESCALATION_SUCCESS',
  PROCESS_ESCALATION_FAILURE: 'ACTIVE_ALARM_PROCESS_ESCALATION_FAILURE',

  // Filter and view state
  SET_FILTERS: 'ACTIVE_ALARM_SET_FILTERS',
  CLEAR_FILTERS: 'ACTIVE_ALARM_CLEAR_FILTERS',
  SET_VIEW_MODE: 'ACTIVE_ALARM_SET_VIEW_MODE',
  SET_PAGINATION: 'ACTIVE_ALARM_SET_PAGINATION',

  // Real-time updates
  ALARM_CREATED: 'ACTIVE_ALARM_CREATED',
  ALARM_UPDATED: 'ACTIVE_ALARM_UPDATED',
  ALARM_STATE_CHANGED: 'ACTIVE_ALARM_STATE_CHANGED',

  // Selection
  SELECT_ALARM: 'ACTIVE_ALARM_SELECT',
  DESELECT_ALARM: 'ACTIVE_ALARM_DESELECT',
  SELECT_MULTIPLE_ALARMS: 'ACTIVE_ALARM_SELECT_MULTIPLE',
  CLEAR_SELECTION: 'ACTIVE_ALARM_CLEAR_SELECTION',
};
