/**
 * GpsGate API Documentation
 * GpsGate API service
 *
 * The version of the OpenAPI document: v.1
 * Contact: support@gpsgate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AccumulatorModel from '../model/AccumulatorModel';
import AccumulatorTypeModel from '../model/AccumulatorTypeModel';

/**
* Accumulator service.
* @module api/AccumulatorApi
* @version v.1
*/
export default class AccumulatorApi {

    /**
    * Constructs a new AccumulatorApi. 
    * @alias module:api/AccumulatorApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getAccumulatorTypes operation.
     * @callback module:api/AccumulatorApi~getAccumulatorTypesCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return a list of AccumulatorTypes.
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {module:api/AccumulatorApi~getAccumulatorTypesCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getAccumulatorTypes(applicationidint, callback) {
      let postBody = null;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling getAccumulatorTypes");
      }

      let pathParams = {
        'applicationid:int': applicationidint
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/accumulatortypes', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAccumulators operation.
     * @callback module:api/AccumulatorApi~getAccumulatorsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return a list of Accumulators. The International System of Units is used (meters for Odometers, seconds for Time based accumulators)
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Object} opts Optional parameters
     * @param {Number} [fromIndex = 0)] The starting index of the page (exclusive)
     * @param {Number} [pageSize = 1000)] The size of the page
     * @param {module:api/AccumulatorApi~getAccumulatorsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getAccumulators(applicationidint, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling getAccumulators");
      }

      let pathParams = {
        'applicationid:int': applicationidint
      };
      let queryParams = {
        'FromIndex': opts['fromIndex'],
        'PageSize': opts['pageSize']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/accumulators', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the putAccumulators operation.
     * @callback module:api/AccumulatorApi~putAccumulatorsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates accumulator values in batch. The International System of Units is used (meters for Odometers, seconds for Time based accumulators)
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Array.<module:model/AccumulatorModel>} accumulators An array of Accumulators. For each entry use either (Id) or (UserId + AccumulatorTypeId) to identify an accumulator. The International System of Units is used (meters for Odometers, seconds for Time based accumulators)
     * @param {module:api/AccumulatorApi~putAccumulatorsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    putAccumulators(applicationidint, accumulators, callback) {
      let postBody = accumulators;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling putAccumulators");
      }
      // verify the required parameter 'accumulators' is set
      if (accumulators === undefined || accumulators === null) {
        throw new Error("Missing the required parameter 'accumulators' when calling putAccumulators");
      }

      let pathParams = {
        'applicationid:int': applicationidint
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/batch/applications/{applicationid:int}/accumulators', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
