/**
 * GpsGate API Documentation
 * GpsGate API service
 *
 * The version of the OpenAPI document: v.1
 * Contact: support@gpsgate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ApplicationCreateModel from '../model/ApplicationCreateModel';
import ApplicationModel from '../model/ApplicationModel';
import ApplicationTemplateModel from '../model/ApplicationTemplateModel';

/**
* Application service.
* @module api/ApplicationApi
* @version v.1
*/
export default class ApplicationApi {

    /**
    * Constructs a new ApplicationApi. 
    * @alias module:api/ApplicationApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getApplicationTemplates operation.
     * @callback module:api/ApplicationApi~getApplicationTemplatesCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return a list of ApplicationTemplates.
     * @param {Object} opts Optional parameters
     * @param {Number} [fromIndex = 0)] The starting index of the page (exclusive)
     * @param {Number} [pageSize = 1000)] The size of the page
     * @param {module:api/ApplicationApi~getApplicationTemplatesCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getApplicationTemplates(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'FromIndex': opts['fromIndex'],
        'PageSize': opts['pageSize']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applicationtemplates', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getApplications operation.
     * @callback module:api/ApplicationApi~getApplicationsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return a list of Applications.
     * @param {Object} opts Optional parameters
     * @param {Number} [fromIndex = 0)] The starting index of the page (exclusive)
     * @param {Number} [pageSize = 1000)] The size of the page
     * @param {module:api/ApplicationApi~getApplicationsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getApplications(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'FromIndex': opts['fromIndex'],
        'PageSize': opts['pageSize']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postApplication operation.
     * @callback module:api/ApplicationApi~postApplicationCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates a new application.
     * @param {module:model/ApplicationCreateModel} application Application Model. <br/><br/><b>TimeZone</b> property of the model should be set to one of the standard time zones available here 'https://en.wikipedia.org/wiki/List_of_tz_database_time_zones' (default is <b>Etc/UTC</b>)<br/><br/><b>Language</b> property of the model should be set to the name of one of the language plugins available on your server (default is <b>English</b>)<br/><br/><b>Measurement</b> property of the model should be set to one of these values: metric, en-us, nautic (default is <b>metric</b>)<br/><br/><b>Culture</b> property of the model should be set to one of the cultures that are specific to a country/region. The names of these cultures follow RFC 4646 (Windows Vista and later). The format is 'languagecode-regioncode' where languagecode is a lowercase two-letter code derived from ISO 639-1 and regioncode is an uppercase two-letter code derived from ISO 3166. For example, <b>en-US</b> for English (United States) is a specific culture.
     * @param {module:api/ApplicationApi~postApplicationCallback} callback The callback function, accepting three arguments: error, data, response
     */
    postApplication(application, callback) {
      let postBody = application;
      // verify the required parameter 'application' is set
      if (application === undefined || application === null) {
        throw new Error("Missing the required parameter 'application' when calling postApplication");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
