/**
 * GpsGate API Documentation
 * GpsGate API service
 *
 * The version of the OpenAPI document: v.1
 * Contact: support@gpsgate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CustomFieldModel from '../model/CustomFieldModel';
import JobModel from '../model/JobModel';
import RouteModel from '../model/RouteModel';

/**
* Dispatch service.
* @module api/DispatchApi
* @version v.1
*/
export default class DispatchApi {

    /**
    * Constructs a new DispatchApi. 
    * @alias module:api/DispatchApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the deleteJobByJobid operation.
     * @callback module:api/DispatchApi~deleteJobByJobidCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a Job
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Number} jobidlong Jobid of the Job you want to work with.
     * @param {module:api/DispatchApi~deleteJobByJobidCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteJobByJobid(applicationidint, jobidlong, callback) {
      let postBody = null;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling deleteJobByJobid");
      }
      // verify the required parameter 'jobidlong' is set
      if (jobidlong === undefined || jobidlong === null) {
        throw new Error("Missing the required parameter 'jobidlong' when calling deleteJobByJobid");
      }

      let pathParams = {
        'applicationid:int': applicationidint,
        'jobid:long': jobidlong
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/dispatch/jobs/{jobid:long}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteRouteByRouteid operation.
     * @callback module:api/DispatchApi~deleteRouteByRouteidCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a Route
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Number} routeidlong Routeid of the Route you want to work with.
     * @param {module:api/DispatchApi~deleteRouteByRouteidCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteRouteByRouteid(applicationidint, routeidlong, callback) {
      let postBody = null;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling deleteRouteByRouteid");
      }
      // verify the required parameter 'routeidlong' is set
      if (routeidlong === undefined || routeidlong === null) {
        throw new Error("Missing the required parameter 'routeidlong' when calling deleteRouteByRouteid");
      }

      let pathParams = {
        'applicationid:int': applicationidint,
        'routeid:long': routeidlong
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/dispatch/routes/{routeid:long}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteUserJobByJobid operation.
     * @callback module:api/DispatchApi~deleteUserJobByJobidCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Remove Job from a user
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Number} jobidlong Jobid of the Job you want to work with.
     * @param {Number} useridint ID of the user.
     * @param {module:api/DispatchApi~deleteUserJobByJobidCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteUserJobByJobid(applicationidint, jobidlong, useridint, callback) {
      let postBody = null;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling deleteUserJobByJobid");
      }
      // verify the required parameter 'jobidlong' is set
      if (jobidlong === undefined || jobidlong === null) {
        throw new Error("Missing the required parameter 'jobidlong' when calling deleteUserJobByJobid");
      }
      // verify the required parameter 'useridint' is set
      if (useridint === undefined || useridint === null) {
        throw new Error("Missing the required parameter 'useridint' when calling deleteUserJobByJobid");
      }

      let pathParams = {
        'applicationid:int': applicationidint,
        'jobid:long': jobidlong,
        'userid:int': useridint
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/dispatch/user/{userid:int}/jobs/{jobid:long}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getCustomFields operation.
     * @callback module:api/DispatchApi~getCustomFieldsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a list of all available Dispatch custom fields
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Object} opts Optional parameters
     * @param {Number} [fromIndex = 0)] The starting index of the page (exclusive)
     * @param {Number} [pageSize = 1000)] The size of the page
     * @param {module:api/DispatchApi~getCustomFieldsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getCustomFields(applicationidint, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling getCustomFields");
      }

      let pathParams = {
        'applicationid:int': applicationidint
      };
      let queryParams = {
        'FromIndex': opts['fromIndex'],
        'PageSize': opts['pageSize']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/dispatch/customfields', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getJobByJobid operation.
     * @callback module:api/DispatchApi~getJobByJobidCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a Job
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Number} jobidlong Jobid of the Job you want to work with.
     * @param {module:api/DispatchApi~getJobByJobidCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getJobByJobid(applicationidint, jobidlong, callback) {
      let postBody = null;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling getJobByJobid");
      }
      // verify the required parameter 'jobidlong' is set
      if (jobidlong === undefined || jobidlong === null) {
        throw new Error("Missing the required parameter 'jobidlong' when calling getJobByJobid");
      }

      let pathParams = {
        'applicationid:int': applicationidint,
        'jobid:long': jobidlong
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/dispatch/jobs/{jobid:long}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getRouteByRouteid operation.
     * @callback module:api/DispatchApi~getRouteByRouteidCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a Route
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Number} routeidlong Routeid of the Route you want to work with.
     * @param {module:api/DispatchApi~getRouteByRouteidCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getRouteByRouteid(applicationidint, routeidlong, callback) {
      let postBody = null;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling getRouteByRouteid");
      }
      // verify the required parameter 'routeidlong' is set
      if (routeidlong === undefined || routeidlong === null) {
        throw new Error("Missing the required parameter 'routeidlong' when calling getRouteByRouteid");
      }

      let pathParams = {
        'applicationid:int': applicationidint,
        'routeid:long': routeidlong
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/dispatch/routes/{routeid:long}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getUserJobs operation.
     * @callback module:api/DispatchApi~getUserJobsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Jobs for a user
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Number} useridint ID of the user.
     * @param {Object} opts Optional parameters
     * @param {Number} [fromIndex = 0)] The starting index of the page (exclusive)
     * @param {Number} [pageSize = 1000)] The size of the page
     * @param {module:api/DispatchApi~getUserJobsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getUserJobs(applicationidint, useridint, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling getUserJobs");
      }
      // verify the required parameter 'useridint' is set
      if (useridint === undefined || useridint === null) {
        throw new Error("Missing the required parameter 'useridint' when calling getUserJobs");
      }

      let pathParams = {
        'applicationid:int': applicationidint,
        'userid:int': useridint
      };
      let queryParams = {
        'FromIndex': opts['fromIndex'],
        'PageSize': opts['pageSize']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/dispatch/user/{userid:int}/jobs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postJob operation.
     * @callback module:api/DispatchApi~postJobCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a Job
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {module:model/JobModel} job Job object
     * @param {module:api/DispatchApi~postJobCallback} callback The callback function, accepting three arguments: error, data, response
     */
    postJob(applicationidint, job, callback) {
      let postBody = job;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling postJob");
      }
      // verify the required parameter 'job' is set
      if (job === undefined || job === null) {
        throw new Error("Missing the required parameter 'job' when calling postJob");
      }

      let pathParams = {
        'applicationid:int': applicationidint
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/dispatch/jobs', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postJobs operation.
     * @callback module:api/DispatchApi~postJobsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create multiple Jobs
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Array.<module:model/JobModel>} jobs An array of Jobs.
     * @param {module:api/DispatchApi~postJobsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    postJobs(applicationidint, jobs, callback) {
      let postBody = jobs;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling postJobs");
      }
      // verify the required parameter 'jobs' is set
      if (jobs === undefined || jobs === null) {
        throw new Error("Missing the required parameter 'jobs' when calling postJobs");
      }

      let pathParams = {
        'applicationid:int': applicationidint
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/batch/applications/{applicationid:int}/dispatch/jobs', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postRoute operation.
     * @callback module:api/DispatchApi~postRouteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a Route
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {module:model/RouteModel} route Route object
     * @param {module:api/DispatchApi~postRouteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    postRoute(applicationidint, route, callback) {
      let postBody = route;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling postRoute");
      }
      // verify the required parameter 'route' is set
      if (route === undefined || route === null) {
        throw new Error("Missing the required parameter 'route' when calling postRoute");
      }

      let pathParams = {
        'applicationid:int': applicationidint
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/dispatch/routes', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postUserJob operation.
     * @callback module:api/DispatchApi~postUserJobCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add a Job to a user
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Number} useridint ID of the user.
     * @param {module:model/JobModel} job Job that is added to the user.
     * @param {module:api/DispatchApi~postUserJobCallback} callback The callback function, accepting three arguments: error, data, response
     */
    postUserJob(applicationidint, useridint, job, callback) {
      let postBody = job;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling postUserJob");
      }
      // verify the required parameter 'useridint' is set
      if (useridint === undefined || useridint === null) {
        throw new Error("Missing the required parameter 'useridint' when calling postUserJob");
      }
      // verify the required parameter 'job' is set
      if (job === undefined || job === null) {
        throw new Error("Missing the required parameter 'job' when calling postUserJob");
      }

      let pathParams = {
        'applicationid:int': applicationidint,
        'userid:int': useridint
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/dispatch/user/{userid:int}/jobs', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the putJobByJobid operation.
     * @callback module:api/DispatchApi~putJobByJobidCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update a Job
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Number} jobidlong Jobid of the Job you want to work with.
     * @param {module:model/JobModel} job Job object
     * @param {module:api/DispatchApi~putJobByJobidCallback} callback The callback function, accepting three arguments: error, data, response
     */
    putJobByJobid(applicationidint, jobidlong, job, callback) {
      let postBody = job;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling putJobByJobid");
      }
      // verify the required parameter 'jobidlong' is set
      if (jobidlong === undefined || jobidlong === null) {
        throw new Error("Missing the required parameter 'jobidlong' when calling putJobByJobid");
      }
      // verify the required parameter 'job' is set
      if (job === undefined || job === null) {
        throw new Error("Missing the required parameter 'job' when calling putJobByJobid");
      }

      let pathParams = {
        'applicationid:int': applicationidint,
        'jobid:long': jobidlong
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/dispatch/jobs/{jobid:long}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the putRouteByRouteid operation.
     * @callback module:api/DispatchApi~putRouteByRouteidCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update a Route
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Number} routeidlong Routeid of the Route you want to work with.
     * @param {module:model/RouteModel} route Route object
     * @param {module:api/DispatchApi~putRouteByRouteidCallback} callback The callback function, accepting three arguments: error, data, response
     */
    putRouteByRouteid(applicationidint, routeidlong, route, callback) {
      let postBody = route;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling putRouteByRouteid");
      }
      // verify the required parameter 'routeidlong' is set
      if (routeidlong === undefined || routeidlong === null) {
        throw new Error("Missing the required parameter 'routeidlong' when calling putRouteByRouteid");
      }
      // verify the required parameter 'route' is set
      if (route === undefined || route === null) {
        throw new Error("Missing the required parameter 'route' when calling putRouteByRouteid");
      }

      let pathParams = {
        'applicationid:int': applicationidint,
        'routeid:long': routeidlong
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/dispatch/routes/{routeid:long}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
