/**
 * GpsGate API Documentation
 * GpsGate API service
 *
 * The version of the OpenAPI document: v.1
 * Contact: support@gpsgate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GeofenceGroupModel from '../model/GeofenceGroupModel';

/**
* GeofenceGroups service.
* @module api/GeofenceGroupsApi
* @version v.1
*/
export default class GeofenceGroupsApi {

    /**
    * Constructs a new GeofenceGroupsApi. 
    * @alias module:api/GeofenceGroupsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the deleteGeofenceGroupByGeofenceGroupid operation.
     * @callback module:api/GeofenceGroupsApi~deleteGeofenceGroupByGeofenceGroupidCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a Geofence Group
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Number} geofencegroupidlong GeofenceGroupid of the GeofenceGroup you want to work with.
     * @param {module:api/GeofenceGroupsApi~deleteGeofenceGroupByGeofenceGroupidCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteGeofenceGroupByGeofenceGroupid(applicationidint, geofencegroupidlong, callback) {
      let postBody = null;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling deleteGeofenceGroupByGeofenceGroupid");
      }
      // verify the required parameter 'geofencegroupidlong' is set
      if (geofencegroupidlong === undefined || geofencegroupidlong === null) {
        throw new Error("Missing the required parameter 'geofencegroupidlong' when calling deleteGeofenceGroupByGeofenceGroupid");
      }

      let pathParams = {
        'applicationid:int': applicationidint,
        'geofencegroupid:long': geofencegroupidlong
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/geofencegroups/{geofencegroupid:long}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getGeofenceGroupByGeofenceGroupid operation.
     * @callback module:api/GeofenceGroupsApi~getGeofenceGroupByGeofenceGroupidCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a Geofence Group by Id
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Number} geofencegroupidlong GeofenceGroupid of the GeofenceGroup you want to work with.
     * @param {module:api/GeofenceGroupsApi~getGeofenceGroupByGeofenceGroupidCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getGeofenceGroupByGeofenceGroupid(applicationidint, geofencegroupidlong, callback) {
      let postBody = null;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling getGeofenceGroupByGeofenceGroupid");
      }
      // verify the required parameter 'geofencegroupidlong' is set
      if (geofencegroupidlong === undefined || geofencegroupidlong === null) {
        throw new Error("Missing the required parameter 'geofencegroupidlong' when calling getGeofenceGroupByGeofenceGroupid");
      }

      let pathParams = {
        'applicationid:int': applicationidint,
        'geofencegroupid:long': geofencegroupidlong
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/geofencegroups/{geofencegroupid:long}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getGeofenceGroups operation.
     * @callback module:api/GeofenceGroupsApi~getGeofenceGroupsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all Geofence Groups in an Application
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Object} opts Optional parameters
     * @param {Number} [fromIndex = 0)] The starting index of the page (exclusive)
     * @param {Number} [pageSize = 1000)] The size of the page
     * @param {module:api/GeofenceGroupsApi~getGeofenceGroupsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getGeofenceGroups(applicationidint, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling getGeofenceGroups");
      }

      let pathParams = {
        'applicationid:int': applicationidint
      };
      let queryParams = {
        'FromIndex': opts['fromIndex'],
        'PageSize': opts['pageSize']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/geofencegroups', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postGeofenceGroup operation.
     * @callback module:api/GeofenceGroupsApi~postGeofenceGroupCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add a new Geofence Group
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {module:model/GeofenceGroupModel} geofencegroup GeofenceGroup object
     * @param {module:api/GeofenceGroupsApi~postGeofenceGroupCallback} callback The callback function, accepting three arguments: error, data, response
     */
    postGeofenceGroup(applicationidint, geofencegroup, callback) {
      let postBody = geofencegroup;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling postGeofenceGroup");
      }
      // verify the required parameter 'geofencegroup' is set
      if (geofencegroup === undefined || geofencegroup === null) {
        throw new Error("Missing the required parameter 'geofencegroup' when calling postGeofenceGroup");
      }

      let pathParams = {
        'applicationid:int': applicationidint
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/geofencegroups', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the putGeofenceGroupByGeofenceGroupid operation.
     * @callback module:api/GeofenceGroupsApi~putGeofenceGroupByGeofenceGroupidCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update a Geofence Group
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Number} geofencegroupidlong GeofenceGroupid of the GeofenceGroup you want to work with.
     * @param {module:model/GeofenceGroupModel} geofencegroup GeofenceGroup object
     * @param {module:api/GeofenceGroupsApi~putGeofenceGroupByGeofenceGroupidCallback} callback The callback function, accepting three arguments: error, data, response
     */
    putGeofenceGroupByGeofenceGroupid(applicationidint, geofencegroupidlong, geofencegroup, callback) {
      let postBody = geofencegroup;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling putGeofenceGroupByGeofenceGroupid");
      }
      // verify the required parameter 'geofencegroupidlong' is set
      if (geofencegroupidlong === undefined || geofencegroupidlong === null) {
        throw new Error("Missing the required parameter 'geofencegroupidlong' when calling putGeofenceGroupByGeofenceGroupid");
      }
      // verify the required parameter 'geofencegroup' is set
      if (geofencegroup === undefined || geofencegroup === null) {
        throw new Error("Missing the required parameter 'geofencegroup' when calling putGeofenceGroupByGeofenceGroupid");
      }

      let pathParams = {
        'applicationid:int': applicationidint,
        'geofencegroupid:long': geofencegroupidlong
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/geofencegroups/{geofencegroupid:long}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
