/**
 * GpsGate API Documentation
 * GpsGate API service
 *
 * The version of the OpenAPI document: v.1
 * Contact: support@gpsgate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import APIModel from '../model/APIModel';
import GeofenceModel from '../model/GeofenceModel';

/**
* GeofenceGroupsGeofence service.
* @module api/GeofenceGroupsGeofenceApi
* @version v.1
*/
export default class GeofenceGroupsGeofenceApi {

    /**
    * Constructs a new GeofenceGroupsGeofenceApi. 
    * @alias module:api/GeofenceGroupsGeofenceApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the deleteGeofenceWithinGeofenceGroupByGeofenceId operation.
     * @callback module:api/GeofenceGroupsGeofenceApi~deleteGeofenceWithinGeofenceGroupByGeofenceIdCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Remove a Geofence from a Geofence Group
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Number} geofenceidint ID of the Geofence you want to work with.
     * @param {Number} geofencegroupidint ID of the Geofence Group you want to work with.
     * @param {module:api/GeofenceGroupsGeofenceApi~deleteGeofenceWithinGeofenceGroupByGeofenceIdCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteGeofenceWithinGeofenceGroupByGeofenceId(applicationidint, geofenceidint, geofencegroupidint, callback) {
      let postBody = null;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling deleteGeofenceWithinGeofenceGroupByGeofenceId");
      }
      // verify the required parameter 'geofenceidint' is set
      if (geofenceidint === undefined || geofenceidint === null) {
        throw new Error("Missing the required parameter 'geofenceidint' when calling deleteGeofenceWithinGeofenceGroupByGeofenceId");
      }
      // verify the required parameter 'geofencegroupidint' is set
      if (geofencegroupidint === undefined || geofencegroupidint === null) {
        throw new Error("Missing the required parameter 'geofencegroupidint' when calling deleteGeofenceWithinGeofenceGroupByGeofenceId");
      }

      let pathParams = {
        'applicationid:int': applicationidint,
        'geofenceid:int': geofenceidint,
        'geofencegroupid:int': geofencegroupidint
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/geofencegroups/{geofencegroupid:int}/geofences/{geofenceid:int}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getGeofencesWithinGeofenceGroup operation.
     * @callback module:api/GeofenceGroupsGeofenceApi~getGeofencesWithinGeofenceGroupCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Geofences within a Geofence Group
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Number} geofencegroupidint ID of the Geofence Group you want to work with.
     * @param {Object} opts Optional parameters
     * @param {Number} [fromIndex = 0)] The starting index of the page (exclusive)
     * @param {Number} [pageSize = 1000)] The size of the page
     * @param {module:api/GeofenceGroupsGeofenceApi~getGeofencesWithinGeofenceGroupCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getGeofencesWithinGeofenceGroup(applicationidint, geofencegroupidint, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling getGeofencesWithinGeofenceGroup");
      }
      // verify the required parameter 'geofencegroupidint' is set
      if (geofencegroupidint === undefined || geofencegroupidint === null) {
        throw new Error("Missing the required parameter 'geofencegroupidint' when calling getGeofencesWithinGeofenceGroup");
      }

      let pathParams = {
        'applicationid:int': applicationidint,
        'geofencegroupid:int': geofencegroupidint
      };
      let queryParams = {
        'FromIndex': opts['fromIndex'],
        'PageSize': opts['pageSize']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/geofencegroups/{geofencegroupid:int}/geofences', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postGeofenceWithinGeofenceGroup operation.
     * @callback module:api/GeofenceGroupsGeofenceApi~postGeofenceWithinGeofenceGroupCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add a Geofence to a Geofence Group
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Number} geofencegroupidint ID of the Geofence Group you want to work with.
     * @param {module:model/APIModel} id ID of the Geofence that is added to the Geofence Group.
     * @param {module:api/GeofenceGroupsGeofenceApi~postGeofenceWithinGeofenceGroupCallback} callback The callback function, accepting three arguments: error, data, response
     */
    postGeofenceWithinGeofenceGroup(applicationidint, geofencegroupidint, id, callback) {
      let postBody = id;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling postGeofenceWithinGeofenceGroup");
      }
      // verify the required parameter 'geofencegroupidint' is set
      if (geofencegroupidint === undefined || geofencegroupidint === null) {
        throw new Error("Missing the required parameter 'geofencegroupidint' when calling postGeofenceWithinGeofenceGroup");
      }
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling postGeofenceWithinGeofenceGroup");
      }

      let pathParams = {
        'applicationid:int': applicationidint,
        'geofencegroupid:int': geofencegroupidint
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/geofencegroups/{geofencegroupid:int}/geofences', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
