/**
 * GpsGate API Documentation
 * GpsGate API service
 *
 * The version of the OpenAPI document: v.1
 * Contact: support@gpsgate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import MessageProviderTypeModel from '../model/MessageProviderTypeModel';

/**
* MessageProviderTypes service.
* @module api/MessageProviderTypesApi
* @version v.1
*/
export default class MessageProviderTypesApi {

    /**
    * Constructs a new MessageProviderTypesApi. 
    * @alias module:api/MessageProviderTypesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getMessageProviderTypes operation.
     * @callback module:api/MessageProviderTypesApi~getMessageProviderTypesCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return a list of Message Provider Types.
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {module:api/MessageProviderTypesApi~getMessageProviderTypesCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getMessageProviderTypes(applicationidint, callback) {
      let postBody = null;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling getMessageProviderTypes");
      }

      let pathParams = {
        'applicationid:int': applicationidint
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/messageprovidertypes', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
