/**
 * GpsGate API Documentation
 * GpsGate API service
 *
 * The version of the OpenAPI document: v.1
 * Contact: support@gpsgate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import MessageProviderModel from '../model/MessageProviderModel';

/**
* MessageProviders service.
* @module api/MessageProvidersApi
* @version v.1
*/
export default class MessageProvidersApi {

    /**
    * Constructs a new MessageProvidersApi. 
    * @alias module:api/MessageProvidersApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the deleteMessageProviderByMessageProviderid operation.
     * @callback module:api/MessageProvidersApi~deleteMessageProviderByMessageProvideridCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a Message Provider
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Number} messageprovideridlong MessageProviderid of the MessageProvider you want to work with.
     * @param {module:api/MessageProvidersApi~deleteMessageProviderByMessageProvideridCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteMessageProviderByMessageProviderid(applicationidint, messageprovideridlong, callback) {
      let postBody = null;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling deleteMessageProviderByMessageProviderid");
      }
      // verify the required parameter 'messageprovideridlong' is set
      if (messageprovideridlong === undefined || messageprovideridlong === null) {
        throw new Error("Missing the required parameter 'messageprovideridlong' when calling deleteMessageProviderByMessageProviderid");
      }

      let pathParams = {
        'applicationid:int': applicationidint,
        'messageproviderid:long': messageprovideridlong
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/messageproviders/{messageproviderid:long}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getMessageProviderByMessageProviderid operation.
     * @callback module:api/MessageProvidersApi~getMessageProviderByMessageProvideridCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return a Message Provider by ID.
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Number} messageprovideridlong MessageProviderid of the MessageProvider you want to work with.
     * @param {module:api/MessageProvidersApi~getMessageProviderByMessageProvideridCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getMessageProviderByMessageProviderid(applicationidint, messageprovideridlong, callback) {
      let postBody = null;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling getMessageProviderByMessageProviderid");
      }
      // verify the required parameter 'messageprovideridlong' is set
      if (messageprovideridlong === undefined || messageprovideridlong === null) {
        throw new Error("Missing the required parameter 'messageprovideridlong' when calling getMessageProviderByMessageProviderid");
      }

      let pathParams = {
        'applicationid:int': applicationidint,
        'messageproviderid:long': messageprovideridlong
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/messageproviders/{messageproviderid:long}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getMessageProviders operation.
     * @callback module:api/MessageProvidersApi~getMessageProvidersCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return a list of Message Providers.
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Object} opts Optional parameters
     * @param {Number} [fromIndex = 0)] The starting index of the page (exclusive)
     * @param {Number} [pageSize = 1000)] The size of the page
     * @param {module:api/MessageProvidersApi~getMessageProvidersCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getMessageProviders(applicationidint, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling getMessageProviders");
      }

      let pathParams = {
        'applicationid:int': applicationidint
      };
      let queryParams = {
        'FromIndex': opts['fromIndex'],
        'PageSize': opts['pageSize']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/messageproviders', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postMessageProvider operation.
     * @callback module:api/MessageProvidersApi~postMessageProviderCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add a Message Provider
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {module:model/MessageProviderModel} messageprovider MessageProvider object
     * @param {module:api/MessageProvidersApi~postMessageProviderCallback} callback The callback function, accepting three arguments: error, data, response
     */
    postMessageProvider(applicationidint, messageprovider, callback) {
      let postBody = messageprovider;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling postMessageProvider");
      }
      // verify the required parameter 'messageprovider' is set
      if (messageprovider === undefined || messageprovider === null) {
        throw new Error("Missing the required parameter 'messageprovider' when calling postMessageProvider");
      }

      let pathParams = {
        'applicationid:int': applicationidint
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/messageproviders', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the putMessageProviderByMessageProviderid operation.
     * @callback module:api/MessageProvidersApi~putMessageProviderByMessageProvideridCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update a Message Provider
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Number} messageprovideridlong MessageProviderid of the MessageProvider you want to work with.
     * @param {module:model/MessageProviderModel} messageprovider MessageProvider object
     * @param {module:api/MessageProvidersApi~putMessageProviderByMessageProvideridCallback} callback The callback function, accepting three arguments: error, data, response
     */
    putMessageProviderByMessageProviderid(applicationidint, messageprovideridlong, messageprovider, callback) {
      let postBody = messageprovider;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling putMessageProviderByMessageProviderid");
      }
      // verify the required parameter 'messageprovideridlong' is set
      if (messageprovideridlong === undefined || messageprovideridlong === null) {
        throw new Error("Missing the required parameter 'messageprovideridlong' when calling putMessageProviderByMessageProviderid");
      }
      // verify the required parameter 'messageprovider' is set
      if (messageprovider === undefined || messageprovider === null) {
        throw new Error("Missing the required parameter 'messageprovider' when calling putMessageProviderByMessageProviderid");
      }

      let pathParams = {
        'applicationid:int': applicationidint,
        'messageproviderid:long': messageprovideridlong
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/messageproviders/{messageproviderid:long}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
