/**
 * GpsGate API Documentation
 * GpsGate API service
 *
 * The version of the OpenAPI document: v.1
 * Contact: support@gpsgate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import APIModel from '../model/APIModel';
import TagModel from '../model/TagModel';
import UserModel from '../model/UserModel';

/**
* Tags service.
* @module api/TagsApi
* @version v.1
*/
export default class TagsApi {

    /**
    * Constructs a new TagsApi. 
    * @alias module:api/TagsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the deleteUserWithinTagByUserid operation.
     * @callback module:api/TagsApi~deleteUserWithinTagByUseridCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Remove a user from a tag
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Number} useridlong Userid of the User you want to work with.
     * @param {Number} tagidint Id of the target tag.
     * @param {module:api/TagsApi~deleteUserWithinTagByUseridCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteUserWithinTagByUserid(applicationidint, useridlong, tagidint, callback) {
      let postBody = null;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling deleteUserWithinTagByUserid");
      }
      // verify the required parameter 'useridlong' is set
      if (useridlong === undefined || useridlong === null) {
        throw new Error("Missing the required parameter 'useridlong' when calling deleteUserWithinTagByUserid");
      }
      // verify the required parameter 'tagidint' is set
      if (tagidint === undefined || tagidint === null) {
        throw new Error("Missing the required parameter 'tagidint' when calling deleteUserWithinTagByUserid");
      }

      let pathParams = {
        'applicationid:int': applicationidint,
        'userid:long': useridlong,
        'tagid:int': tagidint
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/tags/{tagid:int}/users/{userid:long}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getTags operation.
     * @callback module:api/TagsApi~getTagsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a list of Tags
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Object} opts Optional parameters
     * @param {Number} [fromIndex = 0)] The starting index of the page (exclusive)
     * @param {Number} [pageSize = 1000)] The size of the page
     * @param {module:api/TagsApi~getTagsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getTags(applicationidint, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling getTags");
      }

      let pathParams = {
        'applicationid:int': applicationidint
      };
      let queryParams = {
        'FromIndex': opts['fromIndex'],
        'PageSize': opts['pageSize']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/tags', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getUsersWithinTag operation.
     * @callback module:api/TagsApi~getUsersWithinTagCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get users within a tag
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Number} tagidint Id of the target tag.
     * @param {Object} opts Optional parameters
     * @param {Number} [fromIndex = 0)] The starting index of the page (exclusive)
     * @param {Number} [pageSize = 1000)] The size of the page
     * @param {module:api/TagsApi~getUsersWithinTagCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getUsersWithinTag(applicationidint, tagidint, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling getUsersWithinTag");
      }
      // verify the required parameter 'tagidint' is set
      if (tagidint === undefined || tagidint === null) {
        throw new Error("Missing the required parameter 'tagidint' when calling getUsersWithinTag");
      }

      let pathParams = {
        'applicationid:int': applicationidint,
        'tagid:int': tagidint
      };
      let queryParams = {
        'FromIndex': opts['fromIndex'],
        'PageSize': opts['pageSize']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/tags/{tagid:int}/users', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postTag operation.
     * @callback module:api/TagsApi~postTagCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add a Tag
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {module:model/TagModel} tag Tag object
     * @param {module:api/TagsApi~postTagCallback} callback The callback function, accepting three arguments: error, data, response
     */
    postTag(applicationidint, tag, callback) {
      let postBody = tag;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling postTag");
      }
      // verify the required parameter 'tag' is set
      if (tag === undefined || tag === null) {
        throw new Error("Missing the required parameter 'tag' when calling postTag");
      }

      let pathParams = {
        'applicationid:int': applicationidint
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/tags', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postUserWithinTag operation.
     * @callback module:api/TagsApi~postUserWithinTagCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add a user to a tag
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Number} tagidint Id of the target tag.
     * @param {module:model/APIModel} id ID of the user that is added to the tag.
     * @param {module:api/TagsApi~postUserWithinTagCallback} callback The callback function, accepting three arguments: error, data, response
     */
    postUserWithinTag(applicationidint, tagidint, id, callback) {
      let postBody = id;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling postUserWithinTag");
      }
      // verify the required parameter 'tagidint' is set
      if (tagidint === undefined || tagidint === null) {
        throw new Error("Missing the required parameter 'tagidint' when calling postUserWithinTag");
      }
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling postUserWithinTag");
      }

      let pathParams = {
        'applicationid:int': applicationidint,
        'tagid:int': tagidint
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/tags/{tagid:int}/users', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the putTagByTagid operation.
     * @callback module:api/TagsApi~putTagByTagidCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update a Tag
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Number} tagidlong Tagid of the Tag you want to work with.
     * @param {module:model/TagModel} tag Tag object
     * @param {module:api/TagsApi~putTagByTagidCallback} callback The callback function, accepting three arguments: error, data, response
     */
    putTagByTagid(applicationidint, tagidlong, tag, callback) {
      let postBody = tag;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling putTagByTagid");
      }
      // verify the required parameter 'tagidlong' is set
      if (tagidlong === undefined || tagidlong === null) {
        throw new Error("Missing the required parameter 'tagidlong' when calling putTagByTagid");
      }
      // verify the required parameter 'tag' is set
      if (tag === undefined || tag === null) {
        throw new Error("Missing the required parameter 'tag' when calling putTagByTagid");
      }

      let pathParams = {
        'applicationid:int': applicationidint,
        'tagid:long': tagidlong
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/tags/{tagid:long}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
