/**
 * GpsGate API Documentation
 * GpsGate API service
 *
 * The version of the OpenAPI document: v.1
 * Contact: support@gpsgate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import UserCreateModel from '../model/UserCreateModel';
import UserCustomFieldModel from '../model/UserCustomFieldModel';
import UserEditModel from '../model/UserEditModel';
import UserModel from '../model/UserModel';
import UserStatusModel from '../model/UserStatusModel';
import UserTypeModel from '../model/UserTypeModel';

/**
* Users service.
* @module api/UsersApi
* @version v.1
*/
export default class UsersApi {

    /**
    * Constructs a new UsersApi. 
    * @alias module:api/UsersApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getCustomFields operation.
     * @callback module:api/UsersApi~getCustomFieldsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns a list of user custom fields.
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Number} useridint ID of the user.
     * @param {module:api/UsersApi~getCustomFieldsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getCustomFields(applicationidint, useridint, callback) {
      let postBody = null;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling getCustomFields");
      }
      // verify the required parameter 'useridint' is set
      if (useridint === undefined || useridint === null) {
        throw new Error("Missing the required parameter 'useridint' when calling getCustomFields");
      }

      let pathParams = {
        'applicationid:int': applicationidint,
        'userid:int': useridint
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/users/{userid:int}/customfields', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getStatus operation.
     * @callback module:api/UsersApi~getStatusCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the latest position and variables for a user
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Number} useridint ID of the user.
     * @param {module:api/UsersApi~getStatusCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getStatus(applicationidint, useridint, callback) {
      let postBody = null;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling getStatus");
      }
      // verify the required parameter 'useridint' is set
      if (useridint === undefined || useridint === null) {
        throw new Error("Missing the required parameter 'useridint' when calling getStatus");
      }

      let pathParams = {
        'applicationid:int': applicationidint,
        'userid:int': useridint
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/users/{userid:int}/status', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getUserByUserId operation.
     * @callback module:api/UsersApi~getUserByUserIdCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return a User by UserId.
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Number} useridint UserId of the User you want to work with.
     * @param {Object} opts Optional parameters
     * @param {module:model/String} [identifier = 'UserId')] 
     * @param {module:api/UsersApi~getUserByUserIdCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getUserByUserId(applicationidint, useridint, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling getUserByUserId");
      }
      // verify the required parameter 'useridint' is set
      if (useridint === undefined || useridint === null) {
        throw new Error("Missing the required parameter 'useridint' when calling getUserByUserId");
      }

      let pathParams = {
        'applicationid:int': applicationidint,
        'userid:int': useridint
      };
      let queryParams = {
        'Identifier': opts['identifier']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/users/{userid:int}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getUserByUsername operation.
     * @callback module:api/UsersApi~getUserByUsernameCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return a User by Username.
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {String} usernamestring Username of the User you want to work with.
     * @param {Object} opts Optional parameters
     * @param {module:model/String} [identifier = 'Username')] 
     * @param {module:api/UsersApi~getUserByUsernameCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getUserByUsername(applicationidint, usernamestring, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling getUserByUsername");
      }
      // verify the required parameter 'usernamestring' is set
      if (usernamestring === undefined || usernamestring === null) {
        throw new Error("Missing the required parameter 'usernamestring' when calling getUserByUsername");
      }

      let pathParams = {
        'applicationid:int': applicationidint,
        'username:string': usernamestring
      };
      let queryParams = {
        'Identifier': opts['identifier']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/users/{username:string}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getUserTypes operation.
     * @callback module:api/UsersApi~getUserTypesCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return a list of UserTypes.
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {module:api/UsersApi~getUserTypesCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getUserTypes(applicationidint, callback) {
      let postBody = null;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling getUserTypes");
      }

      let pathParams = {
        'applicationid:int': applicationidint
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/usertypes', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getUsers operation.
     * @callback module:api/UsersApi~getUsersCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return a list of Users.
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Object} opts Optional parameters
     * @param {Number} [fromIndex = 0)] The starting index of the page (exclusive)
     * @param {Number} [pageSize = 1000)] The size of the page
     * @param {Number} [viewId] Filters the result set by ViewId
     * @param {String} [updatesFrom] Returns all users that has been active after or equal to this timestamp (As defined by date-time - <a href=\"https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14\"><b>RFC3339</b></a>)<br/>Sample date-time: <b>1996-12-19T16:39:57-08:00</b> <br/>This represents 39 minutes and 57 seconds after the 16th hour of December 19th, 1996 with an offset of -08:00 from UTC (Pacific Standard Time). Note that this is equivalent to <b>1996-12-20T00:39:57Z</b> in UTC.
     * @param {module:api/UsersApi~getUsersCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getUsers(applicationidint, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling getUsers");
      }

      let pathParams = {
        'applicationid:int': applicationidint
      };
      let queryParams = {
        'FromIndex': opts['fromIndex'],
        'PageSize': opts['pageSize'],
        'ViewId': opts['viewId'],
        'UpdatesFrom': opts['updatesFrom']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/users', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getUsersStatus operation.
     * @callback module:api/UsersApi~getUsersStatusCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the latest position and variables for users within an application
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Object} opts Optional parameters
     * @param {Number} [fromIndex = 0)] The starting index of the page (exclusive)
     * @param {Number} [pageSize = 1000)] The size of the page
     * @param {String} [updatesFrom] Returns status of all users that has been active after or equal to this timestamp (As defined by date-time - <a href=\"https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14\"><b>RFC3339</b></a>)<br/>Sample date-time: <b>1996-12-19T16:39:57-08:00</b> <br/>This represents 39 minutes and 57 seconds after the 16th hour of December 19th, 1996 with an offset of -08:00 from UTC (Pacific Standard Time). Note that this is equivalent to <b>1996-12-20T00:39:57Z</b> in UTC.
     * @param {module:api/UsersApi~getUsersStatusCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getUsersStatus(applicationidint, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling getUsersStatus");
      }

      let pathParams = {
        'applicationid:int': applicationidint
      };
      let queryParams = {
        'FromIndex': opts['fromIndex'],
        'PageSize': opts['pageSize'],
        'UpdatesFrom': opts['updatesFrom']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/usersstatus', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the patchUsers operation.
     * @callback module:api/UsersApi~patchUsersCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add existing users to an application
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Array.<Number>} idsOfUsers An array of Users Ids.
     * @param {module:api/UsersApi~patchUsersCallback} callback The callback function, accepting three arguments: error, data, response
     */
    patchUsers(applicationidint, idsOfUsers, callback) {
      let postBody = idsOfUsers;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling patchUsers");
      }
      // verify the required parameter 'idsOfUsers' is set
      if (idsOfUsers === undefined || idsOfUsers === null) {
        throw new Error("Missing the required parameter 'idsOfUsers' when calling patchUsers");
      }

      let pathParams = {
        'applicationid:int': applicationidint
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/batch/applications/{applicationid:int}/users', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postUser operation.
     * @callback module:api/UsersApi~postUserCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add a User.
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {module:model/UserCreateModel} user User object
     * @param {module:api/UsersApi~postUserCallback} callback The callback function, accepting three arguments: error, data, response
     */
    postUser(applicationidint, user, callback) {
      let postBody = user;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling postUser");
      }
      // verify the required parameter 'user' is set
      if (user === undefined || user === null) {
        throw new Error("Missing the required parameter 'user' when calling postUser");
      }

      let pathParams = {
        'applicationid:int': applicationidint
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/users', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the putCustomFieldByCustomFieldName operation.
     * @callback module:api/UsersApi~putCustomFieldByCustomFieldNameCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates a user custom field.
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Number} useridint ID of the user.
     * @param {String} customfieldnamestring CustomFieldName of the CustomField you want to work with.
     * @param {module:model/UserCustomFieldModel} customfield CustomField object
     * @param {module:api/UsersApi~putCustomFieldByCustomFieldNameCallback} callback The callback function, accepting three arguments: error, data, response
     */
    putCustomFieldByCustomFieldName(applicationidint, useridint, customfieldnamestring, customfield, callback) {
      let postBody = customfield;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling putCustomFieldByCustomFieldName");
      }
      // verify the required parameter 'useridint' is set
      if (useridint === undefined || useridint === null) {
        throw new Error("Missing the required parameter 'useridint' when calling putCustomFieldByCustomFieldName");
      }
      // verify the required parameter 'customfieldnamestring' is set
      if (customfieldnamestring === undefined || customfieldnamestring === null) {
        throw new Error("Missing the required parameter 'customfieldnamestring' when calling putCustomFieldByCustomFieldName");
      }
      // verify the required parameter 'customfield' is set
      if (customfield === undefined || customfield === null) {
        throw new Error("Missing the required parameter 'customfield' when calling putCustomFieldByCustomFieldName");
      }

      let pathParams = {
        'applicationid:int': applicationidint,
        'userid:int': useridint,
        'customfieldname:string': customfieldnamestring
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/users/{userid:int}/customfields/{customfieldname:string}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the putCustomFields operation.
     * @callback module:api/UsersApi~putCustomFieldsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates a list of a user's custom fields.
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Number} useridint ID of the user.
     * @param {Array.<module:model/UserCustomFieldModel>} customfields An array of CustomFields.
     * @param {module:api/UsersApi~putCustomFieldsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    putCustomFields(applicationidint, useridint, customfields, callback) {
      let postBody = customfields;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling putCustomFields");
      }
      // verify the required parameter 'useridint' is set
      if (useridint === undefined || useridint === null) {
        throw new Error("Missing the required parameter 'useridint' when calling putCustomFields");
      }
      // verify the required parameter 'customfields' is set
      if (customfields === undefined || customfields === null) {
        throw new Error("Missing the required parameter 'customfields' when calling putCustomFields");
      }

      let pathParams = {
        'applicationid:int': applicationidint,
        'userid:int': useridint
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/batch/applications/{applicationid:int}/users/{userid:int}/customfields', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the putUserByUserId operation.
     * @callback module:api/UsersApi~putUserByUserIdCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update a User
     * @param {Number} applicationidint ID of the application you want to work with.
     * @param {Number} useridint UserId of the User you want to work with.
     * @param {module:model/UserEditModel} user User object
     * @param {module:api/UsersApi~putUserByUserIdCallback} callback The callback function, accepting three arguments: error, data, response
     */
    putUserByUserId(applicationidint, useridint, user, callback) {
      let postBody = user;
      // verify the required parameter 'applicationidint' is set
      if (applicationidint === undefined || applicationidint === null) {
        throw new Error("Missing the required parameter 'applicationidint' when calling putUserByUserId");
      }
      // verify the required parameter 'useridint' is set
      if (useridint === undefined || useridint === null) {
        throw new Error("Missing the required parameter 'useridint' when calling putUserByUserId");
      }
      // verify the required parameter 'user' is set
      if (user === undefined || user === null) {
        throw new Error("Missing the required parameter 'user' when calling putUserByUserId");
      }

      let pathParams = {
        'applicationid:int': applicationidint,
        'userid:int': useridint
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/applications/{applicationid:int}/users/{userid:int}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
