// Enhanced PDF Export Function with Professional Layout
// This function will replace the existing onExportToPDF function

const enhancedPDFExport = useCallback(() => {
    try {
        // Show column selection popup first
        setColumnSelectionVisible(true);
    } catch (error) {
        console.error('Error opening column selection:', error);
        notify({
            message: 'Error opening column selection: ' + error.message,
            type: 'error',
            displayTime: 5000
        });
    }
}, []);

// Function to generate PDF with selected columns
const generatePDFReport = useCallback((selectedCols) => {
    try {
        notify('Preparing professional PDF report...', 'info', 2000);

        const doc = new jsPDF({
            orientation: 'landscape',
            unit: 'mm',
            format: 'a4'
        });

        // Set up document properties
        doc.setProperties({
            title: 'HYoung FMS - Pump Transactions Report',
            subject: 'Pump Transactions Report',
            author: user?.userName || user?.email || 'FMS User',
            creator: 'HYoung Fuel Management System'
        });

        const pageWidth = doc.internal.pageSize.getWidth();
        const pageHeight = doc.internal.pageSize.getHeight();

        // Add company logo and header
        try {
            // Company name and system title (left side)
            doc.setFontSize(14);
            doc.setFont('helvetica', 'bold');
            doc.setTextColor(0, 51, 153); // Blue color
            doc.text('HYoung', 15, 15);

            doc.setFontSize(10);
            doc.setFont('helvetica', 'normal');
            doc.setTextColor(70, 70, 70);
            doc.text('Fuel Management System', 15, 20);

            // Report title (center)
            doc.setFontSize(16);
            doc.setFont('helvetica', 'bold');
            doc.setTextColor(0, 0, 0);
            doc.text('Pump Transactions Report', pageWidth / 2, 15, { align: 'center' });

            // Solid line under header
            doc.setLineWidth(0.3);
            doc.setDrawColor(0, 0, 0);
            doc.line(15, 25, pageWidth - 15, 25);

            // Generation info (right side)
            const now = new Date();
            doc.setFontSize(9);
            doc.setFont('helvetica', 'normal');
            doc.setTextColor(100, 100, 100);
            doc.text(`Generated on: ${now.toLocaleDateString('en-GB')}, ${now.toLocaleTimeString('en-GB')}`, pageWidth - 15, 30, { align: 'right' });
            doc.text(`Generated by: ${user?.userName || user?.email || 'System User'}`, pageWidth - 15, 35, { align: 'right' });
        } catch (logoError) {
            console.warn('Could not add header elements:', logoError);
        }

        let yPos = 45;

        // Applied Filters Section
        const filterInfo = [];
        if (filterValues.ptsId) filterInfo.push(`PTS ID: ${filterValues.ptsId}`);
        if (filterValues.vehicleId) filterInfo.push(`Vehicle ID: ${filterValues.vehicleId}`);
        if (filterValues.tankId) filterInfo.push(`Tank ID: ${filterValues.tankId}`);
        if (filterValues.startDate || filterValues.endDate) {
            const start = filterValues.startDate ? new Date(filterValues.startDate).toLocaleDateString('en-GB') : 'N/A';
            const end = filterValues.endDate ? new Date(filterValues.endDate).toLocaleDateString('en-GB') : 'N/A';
            filterInfo.push(`Date Range: ${start} to ${end}`);
        }
        if (filterValues.processedOnly !== null) {
            filterInfo.push(`Status: ${filterValues.processedOnly ? 'Processed Only' : 'Unprocessed Only'}`);
        }

        if (filterInfo.length > 0) {
            doc.setFontSize(10);
            doc.setFont('helvetica', 'bold');
            doc.setTextColor(0, 0, 0);
            doc.text('Applied Filters:', 15, yPos);
            yPos += 5;

            doc.setFont('helvetica', 'normal');
            doc.setTextColor(60, 60, 60);
            filterInfo.forEach(info => {
                doc.text(`• ${info}`, 20, yPos);
                yPos += 4;
            });
            yPos += 5;
        }

        // Summary Statistics Section
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(0, 0, 0);
        doc.text('Summary Statistics', 15, yPos);
        yPos += 8;

        const summaryData = [
            ['Total Transactions', summaryStats.count.toString()],
            ['Total Volume', `${summaryStats.totalVolume.toFixed(2)} L`],
            ['Total Amount', `KES ${summaryStats.totalAmount.toFixed(2)}`],
            ['Processed Transactions', summaryStats.processedCount.toString()],
            ['Pending Transactions', summaryStats.pendingCount.toString()],
            ['Processing Rate', `${summaryStats.count > 0 ? ((summaryStats.processedCount / summaryStats.count) * 100).toFixed(1) : 0}%`]
        ];

        // Check if autoTable is available and add summary table
        if (typeof doc.autoTable === 'function') {
            doc.autoTable({
                startY: yPos,
                body: summaryData,
                columns: [
                    { header: 'Metric', dataKey: 0 },
                    { header: 'Value', dataKey: 1 }
                ],
                styles: {
                    fontSize: 9,
                    cellPadding: 3,
                    font: 'helvetica'
                },
                headStyles: {
                    fillColor: [0, 51, 153],
                    textColor: 255,
                    fontStyle: 'bold',
                    fontSize: 10
                },
                alternateRowStyles: {
                    fillColor: [245, 248, 255]
                },
                margin: { left: 15, right: 15 },
                tableWidth: 'auto'
            });

            yPos = doc.lastAutoTable.finalY + 15;
        } else {
            // Fallback if autoTable not available
            summaryData.forEach(([metric, value]) => {
                doc.text(`${metric}: ${value}`, 20, yPos);
                yPos += 5;
            });
            yPos += 10;
        }

        // Transaction Details Section
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(0, 0, 0);
        doc.text('Transaction Details', 15, yPos);
        yPos += 10;

        // Limit to 50 rows as requested
        const limitedTransactions = (pumpTransactions || []).slice(0, 50);

        if (limitedTransactions.length === 0) {
            doc.setFontSize(10);
            doc.setFont('helvetica', 'italic');
            doc.setTextColor(150, 150, 150);
            doc.text('No transactions found with current filters.', 20, yPos);
        } else {
            // Add note about row limit
            if (pumpTransactions && pumpTransactions.length > 50) {
                doc.setFontSize(9);
                doc.setFont('helvetica', 'italic');
                doc.setTextColor(200, 100, 0);
                doc.text(`Note: Showing first 50 of ${pumpTransactions.length} transactions. Use filters to narrow results.`, 15, yPos);
                yPos += 8;
            }

            // Define available columns with their configurations
            const availableColumns = {
                ptsId: { header: 'PTS ID', width: 20 },
                vehicleName: { header: 'Vehicle', width: 25 },
                tankName: { header: 'Tank', width: 20 },
                pump: { header: 'Pump', width: 15 },
                nozzle: { header: 'Nozzle', width: 15 },
                tag: { header: 'Tag', width: 20 },
                volume: { header: 'Volume (L)', width: 20, align: 'right' },
                price: { header: 'Price (KES)', width: 20, align: 'right' },
                amount: { header: 'Amount (KES)', width: 22, align: 'right' },
                dateTime: { header: 'Date/Time', width: 35 },
                hasBeenProcessed: { header: 'Status', width: 18, align: 'center' }
            };

            // Use selected columns
            const columnsToShow = Object.keys(selectedCols).filter(col => selectedCols[col]);
            const tableColumns = columnsToShow.map(col => availableColumns[col]);
            const tableHeaders = tableColumns.map(col => col.header);

            // Prepare table data
            const tableData = limitedTransactions.map(transaction => {
                const row = {};
                columnsToShow.forEach(col => {
                    switch (col) {
                        case 'ptsId':
                            row[col] = transaction.ptsId || '';
                            break;
                        case 'vehicleName':
                            row[col] = transaction.vehicleName || transaction.vehicleNumberPlate || 'N/A';
                            break;
                        case 'tankName':
                            row[col] = transaction.tankName || '';
                            break;
                        case 'pump':
                            row[col] = transaction.pump || '';
                            break;
                        case 'nozzle':
                            row[col] = transaction.nozzle || '';
                            break;
                        case 'tag':
                            row[col] = transaction.tag || '';
                            break;
                        case 'volume':
                            row[col] = (transaction.volume || 0).toFixed(2);
                            break;
                        case 'price':
                            row[col] = `${(transaction.price || 0).toFixed(2)}`;
                            break;
                        case 'amount':
                            row[col] = `${(transaction.amount || 0).toFixed(2)}`;
                            break;
                        case 'dateTime':
                            row[col] = transaction.dateTime ?
                                new Date(transaction.dateTime).toLocaleDateString('en-GB') + ' ' +
                                new Date(transaction.dateTime).toLocaleTimeString('en-GB', { hour12: false }) : '';
                            break;
                        case 'hasBeenProcessed':
                            row[col] = transaction.hasBeenProcessed ? 'Processed' : 'Pending';
                            break;
                        default:
                            row[col] = '';
                    }
                });
                return Object.values(row);
            });

            // Create column styles
            const columnStyles = {};
            columnsToShow.forEach((col, index) => {
                const config = availableColumns[col];
                if (config.align) {
                    columnStyles[index] = { halign: config.align };
                }
            });

            doc.autoTable({
                startY: yPos,
                head: [tableHeaders],
                body: tableData,
                styles: {
                    fontSize: 8,
                    cellPadding: 2,
                    overflow: 'linebreak',
                    font: 'helvetica'
                },
                headStyles: {
                    fillColor: [0, 51, 153],
                    textColor: 255,
                    fontStyle: 'bold',
                    fontSize: 9
                },
                columnStyles: columnStyles,
                alternateRowStyles: {
                    fillColor: [248, 250, 252]
                },
                margin: { left: 10, right: 10 },
                didDrawPage: (data) => {
                    // Add page footer
                    const pageNumber = doc.internal.getCurrentPageInfo().pageNumber;
                    const totalPages = doc.internal.getNumberOfPages();

                    doc.setFontSize(8);
                    doc.setFont('helvetica', 'normal');
                    doc.setTextColor(100, 100, 100);
                    doc.text(
                        `Page ${pageNumber} of ${totalPages}`,
                        pageWidth / 2,
                        pageHeight - 10,
                        { align: 'center' }
                    );

                    // Add footer line
                    doc.setLineWidth(0.1);
                    doc.setDrawColor(200, 200, 200);
                    doc.line(15, pageHeight - 15, pageWidth - 15, pageHeight - 15);
                }
            });
        }

        // Generate filename with timestamp
        const now = new Date();
        const timestamp = now.toISOString().slice(0, 19).replace(/:/g, '-');
        const filename = `HYoung_FMS_Pump_Transactions_${timestamp}.pdf`;

        // Save the PDF
        doc.save(filename);

        notify({
            message: 'PDF report generated successfully!',
            type: 'success',
            displayTime: 3000
        });

    } catch (error) {
        console.error('Error generating PDF:', error);
        notify({
            message: 'Error generating PDF report: ' + error.message,
            type: 'error',
            displayTime: 5000
        });
    }
}, [filterValues, summaryStats, pumpTransactions, user]);
