// Action type constants for Dashboard Preferences & Ticker Templates
export const DASHBOARD_PREF_TYPES = {
  FETCH_PREFERENCES_REQUEST: 'DASHBOARD/FETCH_PREFERENCES_REQUEST',
  FETCH_PREFERENCES_SUCCESS: 'DASHBOARD/FETCH_PREFERENCES_SUCCESS',
  FETCH_PREFERENCES_FAILURE: 'DASHBOARD/FETCH_PREFERENCES_FAILURE',

  SAVE_PREFERENCES_REQUEST: 'DASHBOARD/SAVE_PREFERENCES_REQUEST',
  SAVE_PREFERENCES_SUCCESS: 'DASHBOARD/SAVE_PREFERENCES_SUCCESS',
  SAVE_PREFERENCES_FAILURE: 'DASHBOARD/SAVE_PREFERENCES_FAILURE',

  FETCH_TEMPLATES_REQUEST: 'DASHBOARD/FETCH_TEMPLATES_REQUEST',
  FETCH_TEMPLATES_SUCCESS: 'DASHBOARD/FETCH_TEMPLATES_SUCCESS',
  FETCH_TEMPLATES_FAILURE: 'DASHBOARD/FETCH_TEMPLATES_FAILURE',

  TOGGLE_TICKER: 'DASHBOARD/TOGGLE_TICKER',
  SET_TICKER_ORDER: 'DASHBOARD/SET_TICKER_ORDER',
  SET_SITE_FILTERS: 'DASHBOARD/SET_SITE_FILTERS',
  SET_TANK_FILTERS: 'DASHBOARD/SET_TANK_FILTERS',
  SET_VEHICLE_FILTERS: 'DASHBOARD/SET_VEHICLE_FILTERS',
  SET_TICKER_SIZES: 'DASHBOARD/SET_TICKER_SIZES',
  SET_LAYOUT_SETTINGS: 'DASHBOARD/SET_LAYOUT_SETTINGS',
  LOCAL_UPDATE: 'DASHBOARD/LOCAL_UPDATE',
  CLEAR_ERROR: 'DASHBOARD/CLEAR_ERROR'
};
