/**
 * Issue Tracker Redux Action Types
 * All action types for the Issue Tracker module
 */

// Issue CRUD Actions
export const FETCH_ISSUES_REQUEST = 'FETCH_ISSUES_REQUEST';
export const FETCH_ISSUES_SUCCESS = 'FETCH_ISSUES_SUCCESS';
export const FETCH_ISSUES_FAILURE = 'FETCH_ISSUES_FAILURE';

export const FETCH_ISSUE_BY_ID_REQUEST = 'FETCH_ISSUE_BY_ID_REQUEST';
export const FETCH_ISSUE_BY_ID_SUCCESS = 'FETCH_ISSUE_BY_ID_SUCCESS';
export const FETCH_ISSUE_BY_ID_FAILURE = 'FETCH_ISSUE_BY_ID_FAILURE';

export const CREATE_ISSUE_REQUEST = 'CREATE_ISSUE_REQUEST';
export const CREATE_ISSUE_SUCCESS = 'CREATE_ISSUE_SUCCESS';
export const CREATE_ISSUE_FAILURE = 'CREATE_ISSUE_FAILURE';

export const UPDATE_ISSUE_REQUEST = 'UPDATE_ISSUE_REQUEST';
export const UPDATE_ISSUE_SUCCESS = 'UPDATE_ISSUE_SUCCESS';
export const UPDATE_ISSUE_FAILURE = 'UPDATE_ISSUE_FAILURE';

export const DELETE_ISSUE_REQUEST = 'DELETE_ISSUE_REQUEST';
export const DELETE_ISSUE_SUCCESS = 'DELETE_ISSUE_SUCCESS';
export const DELETE_ISSUE_FAILURE = 'DELETE_ISSUE_FAILURE';

// Vehicle-specific Issues
export const FETCH_ISSUES_BY_VEHICLE_REQUEST = 'FETCH_ISSUES_BY_VEHICLE_REQUEST';
export const FETCH_ISSUES_BY_VEHICLE_SUCCESS = 'FETCH_ISSUES_BY_VEHICLE_SUCCESS';
export const FETCH_ISSUES_BY_VEHICLE_FAILURE = 'FETCH_ISSUES_BY_VEHICLE_FAILURE';

// Reference Data Actions
export const FETCH_ISSUE_CATEGORIES_REQUEST = 'FETCH_ISSUE_CATEGORIES_REQUEST';
export const FETCH_ISSUE_CATEGORIES_SUCCESS = 'FETCH_ISSUE_CATEGORIES_SUCCESS';
export const FETCH_ISSUE_CATEGORIES_FAILURE = 'FETCH_ISSUE_CATEGORIES_FAILURE';

export const FETCH_ISSUE_PRIORITIES_REQUEST = 'FETCH_ISSUE_PRIORITIES_REQUEST';
export const FETCH_ISSUE_PRIORITIES_SUCCESS = 'FETCH_ISSUE_PRIORITIES_SUCCESS';
export const FETCH_ISSUE_PRIORITIES_FAILURE = 'FETCH_ISSUE_PRIORITIES_FAILURE';

export const FETCH_ISSUE_STATUSES_REQUEST = 'FETCH_ISSUE_STATUSES_REQUEST';
export const FETCH_ISSUE_STATUSES_SUCCESS = 'FETCH_ISSUE_STATUSES_SUCCESS';
export const FETCH_ISSUE_STATUSES_FAILURE = 'FETCH_ISSUE_STATUSES_FAILURE';

// Analytics Actions
export const FETCH_ISSUE_ANALYTICS_REQUEST = 'FETCH_ISSUE_ANALYTICS_REQUEST';
export const FETCH_ISSUE_ANALYTICS_SUCCESS = 'FETCH_ISSUE_ANALYTICS_SUCCESS';
export const FETCH_ISSUE_ANALYTICS_FAILURE = 'FETCH_ISSUE_ANALYTICS_FAILURE';

// Export Actions
export const EXPORT_ISSUE_REPORT_REQUEST = 'EXPORT_ISSUE_REPORT_REQUEST';
export const EXPORT_ISSUE_REPORT_SUCCESS = 'EXPORT_ISSUE_REPORT_SUCCESS';
export const EXPORT_ISSUE_REPORT_FAILURE = 'EXPORT_ISSUE_REPORT_FAILURE';

// Bulk Operations
export const BULK_ASSIGN_ISSUES_REQUEST = 'BULK_ASSIGN_ISSUES_REQUEST';
export const BULK_ASSIGN_ISSUES_SUCCESS = 'BULK_ASSIGN_ISSUES_SUCCESS';
export const BULK_ASSIGN_ISSUES_FAILURE = 'BULK_ASSIGN_ISSUES_FAILURE';

export const BULK_UPDATE_STATUS_REQUEST = 'BULK_UPDATE_STATUS_REQUEST';
export const BULK_UPDATE_STATUS_SUCCESS = 'BULK_UPDATE_STATUS_SUCCESS';
export const BULK_UPDATE_STATUS_FAILURE = 'BULK_UPDATE_STATUS_FAILURE';

// GPS Integration Actions
export const CREATE_ISSUE_FROM_GPS_REQUEST = 'CREATE_ISSUE_FROM_GPS_REQUEST';
export const CREATE_ISSUE_FROM_GPS_SUCCESS = 'CREATE_ISSUE_FROM_GPS_SUCCESS';
export const CREATE_ISSUE_FROM_GPS_FAILURE = 'CREATE_ISSUE_FROM_GPS_FAILURE';

export const MONITOR_VEHICLE_GPS_REQUEST = 'MONITOR_VEHICLE_GPS_REQUEST';
export const MONITOR_VEHICLE_GPS_SUCCESS = 'MONITOR_VEHICLE_GPS_SUCCESS';
export const MONITOR_VEHICLE_GPS_FAILURE = 'MONITOR_VEHICLE_GPS_FAILURE';

// UI State Actions
export const SET_CURRENT_ISSUE = 'SET_CURRENT_ISSUE';
export const CLEAR_CURRENT_ISSUE = 'CLEAR_CURRENT_ISSUE';
export const SET_FILTERS = 'SET_FILTERS';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
export const SET_LOADING_STATE = 'SET_LOADING_STATE';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const SET_SELECTED_ISSUES = 'SET_SELECTED_ISSUES';
export const CLEAR_SELECTED_ISSUES = 'CLEAR_SELECTED_ISSUES';

// Form State Actions
export const SET_FORM_DATA = 'SET_FORM_DATA';
export const CLEAR_FORM_DATA = 'CLEAR_FORM_DATA';
export const SET_FORM_ERRORS = 'SET_FORM_ERRORS';
export const CLEAR_FORM_ERRORS = 'CLEAR_FORM_ERRORS';
export const SET_FORM_DIRTY = 'SET_FORM_DIRTY';

// Dashboard Actions
export const FETCH_DASHBOARD_STATS_REQUEST = 'FETCH_DASHBOARD_STATS_REQUEST';
export const FETCH_DASHBOARD_STATS_SUCCESS = 'FETCH_DASHBOARD_STATS_SUCCESS';
export const FETCH_DASHBOARD_STATS_FAILURE = 'FETCH_DASHBOARD_STATS_FAILURE';

// Real-time Updates (SignalR)
export const ISSUE_CREATED_NOTIFICATION = 'ISSUE_CREATED_NOTIFICATION';
export const ISSUE_UPDATED_NOTIFICATION = 'ISSUE_UPDATED_NOTIFICATION';
export const ISSUE_DELETED_NOTIFICATION = 'ISSUE_DELETED_NOTIFICATION';
export const GPS_ISSUE_DETECTED_NOTIFICATION = 'GPS_ISSUE_DETECTED_NOTIFICATION';
