-- File: calibration-learning-systemconfig.sql
-- Purpose: Seeds Calibration.* SystemConfiguration rows required for FMS learned calibration.
-- Compatibility: MySQL 5.5.6+
-- Dependencies: systemconfigurations table with a unique index on ConfigurationKey.
-- Last Modified: 2026-03-24

INSERT INTO `systemconfigurations`
(
    `ConfigurationKey`,
    `ConfigurationValue`,
    `Description`,
    `DataType`,
    `Category`,
    `IsActive`,
    `IsEditable`,
    `CreatedBy`,
    `UpdatedBy`,
    `ValidationPattern`,
    `MinValue`,
    `MaxValue`,
    `DefaultValue`,
    `CreatedAt`,
    `UpdatedAt`
)
VALUES
(
    'Calibration.LearningEnabled',
    'false',
    'Global toggle for the FMS learned and detected calibration workflow.',
    'Boolean',
    'Calibration',
    1,
    1,
    'System',
    'System',
    '^(true|false|1|0)$',
    NULL,
    NULL,
    'false',
    NOW(),
    NOW()
),
(
    'Calibration.HeightIntervalMm',
    '50',
    'Height bucket size in millimetres used to group learned calibration observations.',
    'Int32',
    'Calibration',
    1,
    1,
    'System',
    'System',
    '^[0-9]+$',
    1,
    1000,
    '50',
    NOW(),
    NOW()
),
(
    'Calibration.MinObservationsPerInterval',
    '5',
    'Minimum number of observations required before a learned-calibration interval is considered usable.',
    'Int32',
    'Calibration',
    1,
    1,
    'System',
    'System',
    '^[0-9]+$',
    1,
    1000,
    '5',
    NOW(),
    NOW()
),
(
    'Calibration.StabilityWindowMinutes',
    '5',
    'Required quiet window before and after an event to treat probe readings as stable.',
    'Int32',
    'Calibration',
    1,
    1,
    'System',
    'System',
    '^[0-9]+$',
    1,
    1440,
    '5',
    NOW(),
    NOW()
),
(
    'Calibration.MaxHeightVarianceMm',
    '2.0',
    'Maximum probe fluctuation allowed within the stability window, in millimetres.',
    'Decimal',
    'Calibration',
    1,
    1,
    'System',
    'System',
    '^([0-9]+)(\\.[0-9]+)?$',
    0,
    100,
    '2.0',
    NOW(),
    NOW()
),
(
    'Calibration.MinVolumeChangeLitres',
    '10.0',
    'Minimum usable volume change, in litres, when extracting learned calibration data points.',
    'Decimal',
    'Calibration',
    1,
    1,
    'System',
    'System',
    '^([0-9]+)(\\.[0-9]+)?$',
    0,
    100000,
    '10.0',
    NOW(),
    NOW()
),
(
    'Calibration.BackgroundTriggerThreshold',
    '10',
    'Number of newly accumulated learned-calibration data points required before readiness notification should be raised.',
    'Int32',
    'Calibration',
    1,
    1,
    'System',
    'System',
    '^[0-9]+$',
    1,
    100000,
    '10',
    NOW(),
    NOW()
)
ON DUPLICATE KEY UPDATE
    `ConfigurationValue` = VALUES(`ConfigurationValue`),
    `Description` = VALUES(`Description`),
    `DataType` = VALUES(`DataType`),
    `Category` = VALUES(`Category`),
    `IsActive` = VALUES(`IsActive`),
    `IsEditable` = VALUES(`IsEditable`),
    `UpdatedBy` = VALUES(`UpdatedBy`),
    `ValidationPattern` = VALUES(`ValidationPattern`),
    `MinValue` = VALUES(`MinValue`),
    `MaxValue` = VALUES(`MaxValue`),
    `DefaultValue` = VALUES(`DefaultValue`),
    `UpdatedAt` = VALUES(`UpdatedAt`);