/**
 * App Version Configuration
 * Auto-generated by increment-version.ps1
 * DO NOT EDIT MANUALLY
 */

export const APP_VERSION = {
  major: 1,
  minor: 2,
  patch: 3,
  build: 111,
  versionName: '1.2.3',
  versionCode: 111,
  displayName: 'Hyoung FMS v1.2.3',
  fullVersion: 'v1.2.3 (build 111)',
};

export default APP_VERSION;