/**
 * App Version Configuration
 * Auto-generated by increment-version.ps1
 * DO NOT EDIT MANUALLY
 */

export const APP_VERSION = {
  major: 1,
  minor: 2,
  patch: 6,
  build: 114,
  versionName: '1.2.6',
  versionCode: 114,
  displayName: 'Hyoung FMS v1.2.6',
  fullVersion: 'v1.2.6 (build 114)',
};

export default APP_VERSION;