/**
 * App Version Configuration
 * Auto-generated by increment-version.ps1
 * DO NOT EDIT MANUALLY
 */

export const APP_VERSION = {
  major: 1,
  minor: 2,
  patch: 11,
  build: 120,
  versionName: '1.2.11',
  versionCode: 120,
  displayName: 'Hyoung FMS v1.2.11',
  fullVersion: 'v1.2.11 (build 120)',
};

export default APP_VERSION;