name: Deploy

on:
  push:
    branches: [ productionv1 ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v4
        with:
          clean: false  # Don't clean the repository before checkout
          fetch-depth: 0  # Fetch full history
          
      # Your deployment steps here
