name: Manual Deployment Test
on:
  workflow_dispatch:
    inputs:
      deploymentType:
        description: 'What to deploy'
        required: true
        default: 'full'
        type: choice
        options:
        - full
        - frontend
        - backend
      buildOnServer:
        description: 'Build on server'
        required: true
        default: 'true'
        type: boolean

jobs:
  manual-deployment:
    runs-on: [self-hosted, Windows, X64, HYFMS]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute deployment (Frontend only)
        if: ${{ inputs.deploymentType == 'frontend' }}
        run: |
          echo "Running frontend-only deployment test..."
          powershell -File ./deploy.ps1 -frontendOnly -logFile "./frontend_test_deploy_log.txt"
          echo "Test deployment completed with exit code %ERRORLEVEL%"
          powershell -Command "Get-Content -Path './frontend_test_deploy_log.txt' -Tail 10"
        shell: cmd

      - name: Execute deployment (Backend only)
        if: ${{ inputs.deploymentType == 'backend' }}
        run: |
          echo "Running backend-only deployment test..."
          powershell -File ./deploy.ps1 -backendOnly -buildOnServer:${{ inputs.buildOnServer }} -logFile "./backend_test_deploy_log.txt"
          echo "Test deployment completed with exit code %ERRORLEVEL%"
          powershell -Command "Get-Content -Path './backend_test_deploy_log.txt' -Tail 10"
        shell: cmd

      - name: Execute deployment (Full)
        if: ${{ inputs.deploymentType == 'full' }}
        run: |
          echo "Running full deployment test..."
          powershell -File ./deploy.ps1 -buildOnServer:${{ inputs.buildOnServer }} -logFile "./full_test_deploy_log.txt"
          echo "Test deployment completed with exit code %ERRORLEVEL%"
          powershell -Command "Get-Content -Path './full_test_deploy_log.txt' -Tail 10"
        shell: cmd
